[package]
name = "verifiable_inference_engine"
version = "4.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-ff = "0.4.2"
ark-relations = "0.4.0"
ark-bls12-381 = "0.4.0"
ark-groth16 = "0.4.0"
ark-snark = "0.4.0"
ark-serialize = "0.4.2"
hex = "0.4.3"
rand = "0.8.5"
rand_chacha = "0.3.1"

[build-dependencies]
nul-zk = { path = "../../../00_BABYLON_SHIELD/crates/nul-zk" }
