// [C5-REAL] Exergy-Maximized
//! CORTEX Curriculum Generator — Test-Time RL (TTRL) Pattern
//!
//! Inverse AlphaProof architecture: Given a hard target problem,
//! generate a curriculum of progressively easier variants that
//! build toward the solution.
//!
//! Implements 4 mutation operators from the TTRL literature:
//!   1. Simplification: Reduce the number of premises/constraints
//!   2. Specialization: Substitute concrete values for abstract ones
//!   3. Decomposition: Split a hard problem into independent subgoals
//!   4. Analogical: Swap domain objects while preserving structure
//!
//! The curriculum forms a DAG where edges represent "is-easier-than"
//! relationships, enabling the RL agent to climb from solved variants
//! toward the hard target.
//!
//! Reality Level: C5-REAL

use serde::{Deserialize, Serialize};

use std::collections::HashMap;
use std::time::Instant;
use sha2::{Digest, Sha256};

// ─────────────────────────────────────────────────────────────
// §1 — Core Types
// ─────────────────────────────────────────────────────────────

/// Unique problem identifier (content-addressable hash)
pub type ProblemId = [u8; 32];

/// A formal problem statement
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Problem {
    pub id: ProblemId,
    /// The premises / given conditions
    pub premises: Vec<String>,
    /// The goal to prove or compute
    pub goal: String,
    /// Estimated difficulty (0.0 = trivial, 1.0 = open research)
    pub difficulty: f64,
    /// How this problem was generated
    pub origin: ProblemOrigin,
    /// Optional: formal encoding (e.g. Lean 4 statement)
    pub formal: Option<String>,
}

/// How a problem variant was generated
#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ProblemOrigin {
    /// The original hard target problem
    Target,
    /// Generated by simplification (removed premises)
    Simplified { parent: ProblemId, removed: Vec<String> },
    /// Generated by specialization (substituted concrete values)
    Specialized { parent: ProblemId, substitutions: Vec<(String, String)> },
    /// Generated by decomposition (subgoal of parent)
    Decomposed { parent: ProblemId, subgoal_index: usize, total_subgoals: usize },
    /// Generated by analogy (swapped domain objects)
    Analogical { parent: ProblemId, swaps: Vec<(String, String)> },
}

/// Result of attempting to solve a problem variant
#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum SolveStatus {
    Unsolved,
    Solved { proof_steps: Vec<String>, time_us: u64 },
    Timeout { time_us: u64 },
    Error(String),
}

/// A curriculum node: problem + its solve status + edges
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct CurriculumNode {
    pub problem: Problem,
    pub status: SolveStatus,
    /// IDs of easier variants (children in the difficulty ladder)
    pub easier_variants: Vec<ProblemId>,
    /// ID of the harder parent (if this was generated from one)
    pub parent: Option<ProblemId>,
    /// Elo-style difficulty rating (updated by solve attempts)
    pub elo: f64,
}

/// Statistics for the curriculum generation
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct CurriculumStats {
    pub total_variants: usize,
    pub solved_count: usize,
    pub unsolved_count: usize,
    pub max_difficulty: f64,
    pub min_difficulty: f64,
    pub avg_difficulty: f64,
    pub generation_time_us: u64,
    pub depth_distribution: HashMap<u32, usize>,
}

// ─────────────────────────────────────────────────────────────
// §2 — Problem Hashing
// ─────────────────────────────────────────────────────────────

/// Content-addressable hash for deduplication
fn hash_problem(premises: &[String], goal: &str) -> ProblemId {
    let mut hasher = Sha256::new();
    for p in premises {
        hasher.update(p.as_bytes());
        hasher.update(b"|");
    }
    hasher.update(b"=>");
    hasher.update(goal.as_bytes());
    let result = hasher.finalize();
    let mut id = [0u8; 32];
    id.copy_from_slice(&result);
    id
}

// ─────────────────────────────────────────────────────────────
// §3 — Mutation Operators
// ─────────────────────────────────────────────────────────────

/// Simplification: Remove one premise at a time to create easier variants
fn simplify(problem: &Problem) -> Vec<Problem> {
    if problem.premises.len() <= 1 {
        return Vec::new();
    }

    (0..problem.premises.len())
        .map(|i| {
            let mut new_premises = problem.premises.clone();
            let removed = new_premises.remove(i);
            let id = hash_problem(&new_premises, &problem.goal);
            Problem {
                id,
                premises: new_premises,
                goal: problem.goal.clone(),
                difficulty: (problem.difficulty * 0.7).max(0.0),
                origin: ProblemOrigin::Simplified {
                    parent: problem.id,
                    removed: vec![removed],
                },
                formal: None,
            }
        })
        .collect()
}

/// Specialization: Replace abstract terms with concrete instances
fn specialize(problem: &Problem, substitutions: &[(String, String)]) -> Vec<Problem> {
    substitutions
        .iter()
        .map(|(from, to)| {
            let new_premises: Vec<String> = problem.premises.iter()
                .map(|p| p.replace(from.as_str(), to.as_str()))
                .collect();
            let new_goal = problem.goal.replace(from.as_str(), to.as_str());
            let id = hash_problem(&new_premises, &new_goal);
            Problem {
                id,
                premises: new_premises,
                goal: new_goal,
                difficulty: (problem.difficulty * 0.8).max(0.0),
                origin: ProblemOrigin::Specialized {
                    parent: problem.id,
                    substitutions: vec![(from.clone(), to.clone())],
                },
                formal: None,
            }
        })
        .collect()
}

/// Decomposition: Split the goal into subgoals
fn decompose(problem: &Problem, subgoals: &[String]) -> Vec<Problem> {
    let total = subgoals.len();
    subgoals
        .iter()
        .enumerate()
        .map(|(i, subgoal)| {
            let id = hash_problem(&problem.premises, subgoal);
            Problem {
                id,
                premises: problem.premises.clone(),
                goal: subgoal.clone(),
                difficulty: (problem.difficulty * 0.6).max(0.0),
                origin: ProblemOrigin::Decomposed {
                    parent: problem.id,
                    subgoal_index: i,
                    total_subgoals: total,
                },
                formal: None,
            }
        })
        .collect()
}

/// Analogical: Swap domain objects while preserving structure
fn analogize(problem: &Problem, swaps: &[(String, String)]) -> Vec<Problem> {
    let mut new_premises = problem.premises.clone();
    let mut new_goal = problem.goal.clone();

    for (from, to) in swaps {
        new_premises = new_premises.iter()
            .map(|p| p.replace(from.as_str(), to.as_str()))
            .collect();
        new_goal = new_goal.replace(from.as_str(), to.as_str());
    }

    let id = hash_problem(&new_premises, &new_goal);
    vec![Problem {
        id,
        premises: new_premises,
        goal: new_goal,
        difficulty: problem.difficulty, // Analogues have similar difficulty
        origin: ProblemOrigin::Analogical {
            parent: problem.id,
            swaps: swaps.to_vec(),
        },
        formal: None,
    }]
}

// ─────────────────────────────────────────────────────────────
// §4 — The Curriculum Engine
// ─────────────────────────────────────────────────────────────

/// The TTRL Curriculum Engine: generates and manages a difficulty
/// ladder of problem variants around a hard target.
pub struct CurriculumEngine {
    nodes: HashMap<ProblemId, CurriculumNode>,
    target: Option<ProblemId>,
    /// Default substitution table for specialization
    substitution_table: Vec<(String, String)>,
}

impl CurriculumEngine {
    pub fn new() -> Self {
        CurriculumEngine {
            nodes: HashMap::new(),
            target: None,
            substitution_table: Vec::new(),
        }
    }

    /// Set the hard target problem that the curriculum builds toward
    pub fn set_target(&mut self, premises: Vec<String>, goal: String, difficulty: f64) -> ProblemId {
        let id = hash_problem(&premises, &goal);
        let problem = Problem {
            id,
            premises,
            goal,
            difficulty,
            origin: ProblemOrigin::Target,
            formal: None,
        };
        let node = CurriculumNode {
            problem,
            status: SolveStatus::Unsolved,
            easier_variants: Vec::new(),
            parent: None,
            elo: difficulty * 1000.0,
        };
        self.nodes.insert(id, node);
        self.target = Some(id);
        id
    }

    /// Add a substitution pair for the specialization operator
    pub fn add_substitution(&mut self, from: String, to: String) {
        self.substitution_table.push((from, to));
    }

    /// Generate N levels of the curriculum by recursively mutating
    pub fn generate(&mut self, depth: u32) -> usize {
        let start = Instant::now();
        let mut total_generated = 0;

        for _level in 0..depth {
            // Collect current unsolved problems to mutate
            let problems: Vec<Problem> = self.nodes.values()
                .filter(|n| matches!(n.status, SolveStatus::Unsolved))
                .map(|n| n.problem.clone())
                .collect();

            let mut new_problems: Vec<(ProblemId, Problem)> = Vec::new();

            for problem in &problems {
                // Apply all mutation operators
                let simplified = simplify(problem);
                let specialized = specialize(problem, &self.substitution_table);

                for variant in simplified.into_iter().chain(specialized) {
                    if !self.nodes.contains_key(&variant.id) && !new_problems.iter().any(|(id, _)| *id == variant.id) {
                        new_problems.push((variant.id, variant));
                    }
                }
            }

            if new_problems.is_empty() {
                break; // No more variants to generate
            }

            for (id, problem) in new_problems {
                let parent_id = match &problem.origin {
                    ProblemOrigin::Simplified { parent, .. } => Some(*parent),
                    ProblemOrigin::Specialized { parent, .. } => Some(*parent),
                    ProblemOrigin::Decomposed { parent, .. } => Some(*parent),
                    ProblemOrigin::Analogical { parent, .. } => Some(*parent),
                    ProblemOrigin::Target => None,
                };

                // Register edge: parent → this variant
                if let Some(pid) = parent_id {
                    if let Some(parent_node) = self.nodes.get_mut(&pid) {
                        parent_node.easier_variants.push(id);
                    }
                }

                let node = CurriculumNode {
                    problem,
                    status: SolveStatus::Unsolved,
                    easier_variants: Vec::new(),
                    parent: parent_id,
                    elo: 500.0,
                };
                self.nodes.insert(id, node);
                total_generated += 1;
            }
        }

        let _elapsed = start.elapsed();
        total_generated
    }

    /// Generate variants using decomposition (requires explicit subgoals)
    pub fn decompose_target(&mut self, subgoals: Vec<String>) -> Vec<ProblemId> {
        let target_id = match self.target {
            Some(id) => id,
            None => return Vec::new(),
        };

        let target_problem = match self.nodes.get(&target_id) {
            Some(node) => node.problem.clone(),
            None => return Vec::new(),
        };

        let decomposed = decompose(&target_problem, &subgoals);
        let mut ids = Vec::new();

        for variant in decomposed {
            let id = variant.id;
            if !self.nodes.contains_key(&id) {
                if let Some(parent_node) = self.nodes.get_mut(&target_id) {
                    parent_node.easier_variants.push(id);
                }
                let node = CurriculumNode {
                    problem: variant,
                    status: SolveStatus::Unsolved,
                    easier_variants: Vec::new(),
                    parent: Some(target_id),
                    elo: 500.0,
                };
                self.nodes.insert(id, node);
            }
            ids.push(id);
        }

        ids
    }

    /// Generate variants using analogy (requires explicit object swaps)
    pub fn analogize_target(&mut self, swaps: Vec<(String, String)>) -> Vec<ProblemId> {
        let target_id = match self.target {
            Some(id) => id,
            None => return Vec::new(),
        };

        let target_problem = match self.nodes.get(&target_id) {
            Some(node) => node.problem.clone(),
            None => return Vec::new(),
        };

        let analogues = analogize(&target_problem, &swaps);
        let mut ids = Vec::new();

        for variant in analogues {
            let id = variant.id;
            if !self.nodes.contains_key(&id) {
                if let Some(parent_node) = self.nodes.get_mut(&target_id) {
                    parent_node.easier_variants.push(id);
                }
                let node = CurriculumNode {
                    problem: variant,
                    status: SolveStatus::Unsolved,
                    easier_variants: Vec::new(),
                    parent: Some(target_id),
                    elo: 500.0,
                };
                self.nodes.insert(id, node);
            }
            ids.push(id);
        }

        ids
    }

    /// Mark a problem as solved and propagate Elo updates
    pub fn mark_solved(&mut self, id: &ProblemId, proof_steps: Vec<String>, time_us: u64) {
        if let Some(node) = self.nodes.get_mut(id) {
            node.status = SolveStatus::Solved { proof_steps, time_us };
            // Elo update: solved problems decrease their rating
            node.elo = (node.elo * 0.8).max(100.0);
        }

        // Propagate: if all easier variants of a parent are solved,
        // decrease the parent's Elo (it's now more approachable)
        let parent_id = self.nodes.get(id).and_then(|n| n.parent);
        if let Some(pid) = parent_id {
            let all_children_solved = {
                if let Some(parent) = self.nodes.get(&pid) {
                    parent.easier_variants.iter().all(|child_id| {
                        self.nodes.get(child_id)
                            .map(|n| matches!(n.status, SolveStatus::Solved { .. }))
                            .unwrap_or(false)
                    })
                } else {
                    false
                }
            };

            if all_children_solved {
                if let Some(parent) = self.nodes.get_mut(&pid) {
                    parent.elo *= 0.9; // Parent becomes easier after children solved
                }
            }
        }
    }

    /// Get the next best problem to attempt (lowest unsolved Elo)
    pub fn next_problem(&self) -> Option<&Problem> {
        self.nodes.values()
            .filter(|n| matches!(n.status, SolveStatus::Unsolved))
            .min_by(|a, b| a.elo.partial_cmp(&b.elo).unwrap_or(std::cmp::Ordering::Equal))
            .map(|n| &n.problem)
    }

    /// Get curriculum statistics
    pub fn stats(&self) -> CurriculumStats {
        let total = self.nodes.len();
        let solved = self.nodes.values()
            .filter(|n| matches!(n.status, SolveStatus::Solved { .. }))
            .count();
        let difficulties: Vec<f64> = self.nodes.values()
            .map(|n| n.problem.difficulty)
            .collect();
        let max_d = difficulties.iter().cloned().fold(0.0_f64, f64::max);
        let min_d = difficulties.iter().cloned().fold(1.0_f64, f64::min);
        let avg_d = if total > 0 { difficulties.iter().sum::<f64>() / total as f64 } else { 0.0 };

        // Depth distribution (by curriculum generation depth)
        let mut depth_dist: HashMap<u32, usize> = HashMap::new();
        for node in self.nodes.values() {
            let depth = self.node_depth(&node.problem.id);
            *depth_dist.entry(depth).or_insert(0) += 1;
        }

        CurriculumStats {
            total_variants: total,
            solved_count: solved,
            unsolved_count: total - solved,
            max_difficulty: max_d,
            min_difficulty: min_d,
            avg_difficulty: avg_d,
            generation_time_us: 0,
            depth_distribution: depth_dist,
        }
    }

    /// Calculate the depth of a node in the curriculum tree
    fn node_depth(&self, id: &ProblemId) -> u32 {
        let mut depth = 0;
        let mut current = *id;
        while let Some(node) = self.nodes.get(&current) {
            if let Some(parent) = node.parent {
                depth += 1;
                current = parent;
            } else {
                break;
            }
        }
        depth
    }

    /// Get the difficulty ladder: ordered path from easiest to target
    pub fn difficulty_ladder(&self) -> Vec<&Problem> {
        let mut problems: Vec<&CurriculumNode> = self.nodes.values().collect();
        problems.sort_by(|a, b| a.elo.partial_cmp(&b.elo).unwrap_or(std::cmp::Ordering::Equal));
        problems.iter().map(|n| &n.problem).collect()
    }

    /// Total node count
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Check if empty
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// Check if the target problem is solved
    pub fn is_target_solved(&self) -> bool {
        self.target
            .and_then(|id| self.nodes.get(&id))
            .map(|n| matches!(n.status, SolveStatus::Solved { .. }))
            .unwrap_or(false)
    }

    /// Get solve rate (fraction of solved problems)
    pub fn solve_rate(&self) -> f64 {
        let total = self.nodes.len();
        if total == 0 { return 0.0; }
        let solved = self.nodes.values()
            .filter(|n| matches!(n.status, SolveStatus::Solved { .. }))
            .count();
        solved as f64 / total as f64
    }
}

// ─────────────────────────────────────────────────────────────
// §5 — Tests
// ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_curriculum_generation() {
        let mut engine = CurriculumEngine::new();

        // Set a target problem (e.g., geometry theorem)
        let _target_id = engine.set_target(
            vec![
                "triangle(A,B,C)".into(),
                "midpoint(M,A,B)".into(),
                "perpendicular(L,M,AB)".into(),
                "circle(O,A,B,C)".into(),
            ],
            "passes_through(L,O)".into(),
            0.9,
        );

        // Add substitutions for specialization
        engine.add_substitution("triangle".into(), "right_triangle".into());
        engine.add_substitution("circle".into(), "unit_circle".into());

        // Generate 3 levels of curriculum
        let generated = engine.generate(3);
        assert!(generated > 0, "Should generate variants");

        let stats = engine.stats();
        assert!(stats.total_variants > 1);
        assert!(stats.min_difficulty < 0.9);

        // tracing::info!("═══════════════════════════════════════════");
        // tracing::info!("  TTRL CURRICULUM GENERATION");
        // tracing::info!("═══════════════════════════════════════════");
        // tracing::info!("  Target:       {:?}...", &target_id[..4]);
        // tracing::info!("  Generated:    {} variants", generated);
        // tracing::info!("  Total nodes:  {}", stats.total_variants);
        // tracing::info!("  Difficulty:   [{:.2}, {:.2}] avg={:.2}",
        //     stats.min_difficulty, stats.max_difficulty, stats.avg_difficulty);
        // tracing::info!("═══════════════════════════════════════════");
    }

    #[test]
    fn test_simplification() {
        let problem = Problem {
            id: hash_problem(&["a".into(), "b".into(), "c".into()], "goal"),
            premises: vec!["a".into(), "b".into(), "c".into()],
            goal: "goal".into(),
            difficulty: 0.8,
            origin: ProblemOrigin::Target,
            formal: None,
        };
        let simplified = simplify(&problem);
        assert_eq!(simplified.len(), 3, "Should create N variants for N premises");
        for s in &simplified {
            assert_eq!(s.premises.len(), 2, "Each variant removes one premise");
            assert!(s.difficulty < problem.difficulty);
        }
    }

    #[test]
    fn test_decomposition() {
        let mut engine = CurriculumEngine::new();
        engine.set_target(
            vec!["premise_1".into(), "premise_2".into()],
            "hard_goal".into(),
            0.95,
        );

        let subgoal_ids = engine.decompose_target(vec![
            "subgoal_1".into(),
            "subgoal_2".into(),
            "subgoal_3".into(),
        ]);

        assert_eq!(subgoal_ids.len(), 3);
        assert_eq!(engine.len(), 4); // target + 3 subgoals
    }

    #[test]
    fn test_analogy() {
        let mut engine = CurriculumEngine::new();
        engine.set_target(
            vec!["triangle(A,B,C)".into()],
            "area(A,B,C) > 0".into(),
            0.5,
        );

        let analogue_ids = engine.analogize_target(vec![
            ("A".into(), "X".into()),
            ("B".into(), "Y".into()),
            ("C".into(), "Z".into()),
        ]);

        assert_eq!(analogue_ids.len(), 1);
        let analogue = engine.nodes.get(&analogue_ids[0]).unwrap();
        assert!(analogue.problem.premises[0].contains("X"));
        assert!(analogue.problem.goal.contains("X"));
    }

    #[test]
    fn test_solve_and_elo_propagation() {
        let mut engine = CurriculumEngine::new();
        let _target_id = engine.set_target(
            vec!["p1".into(), "p2".into(), "p3".into()],
            "goal".into(),
            0.9,
        );

        engine.add_substitution("p1".into(), "q1".into());
        engine.generate(1);

        // Get the easiest problem
        let easiest = engine.next_problem().unwrap().clone();
        let easiest_id = easiest.id;

        // Solve it
        engine.mark_solved(&easiest_id, vec!["step1".into()], 100);

        // Verify it's marked solved
        let node = engine.nodes.get(&easiest_id).unwrap();
        assert!(matches!(node.status, SolveStatus::Solved { .. }));

        // Verify Elo decreased
        assert!(node.elo < 500.0);
    }

    #[test]
    fn test_difficulty_ladder() {
        let mut engine = CurriculumEngine::new();
        engine.set_target(
            vec!["p1".into(), "p2".into(), "p3".into(), "p4".into()],
            "goal".into(),
            0.95,
        );
        engine.add_substitution("p1".into(), "q1".into());
        engine.generate(2);

        let ladder = engine.difficulty_ladder();
        assert!(ladder.len() > 1);

        // Verify ordering: each should be <= the next in Elo
        for window in ladder.windows(2) {
            assert!(window[0].difficulty <= window[1].difficulty + 0.001);
        }
    }

    #[test]
    fn test_generation_throughput() {
        let mut engine = CurriculumEngine::new();
        engine.set_target(
            (0..20).map(|i| format!("premise_{}", i)).collect(),
            "complex_goal".into(),
            0.99,
        );
        engine.add_substitution("premise_0".into(), "concrete_0".into());
        engine.add_substitution("premise_1".into(), "concrete_1".into());

        let start = Instant::now();
        let generated = engine.generate(3);
        let elapsed = start.elapsed();
        let _rate = generated as f64 / elapsed.as_secs_f64();

        // tracing::info!("═══════════════════════════════════════════");
        // tracing::info!("  CURRICULUM THROUGHPUT BENCHMARK");
        // tracing::info!("═══════════════════════════════════════════");
        // tracing::info!("  Premises:    20");
        // tracing::info!("  Depth:       3 levels");
        // tracing::info!("  Generated:   {} variants", generated);
        // tracing::info!("  Elapsed:     {:.4?}", elapsed);
        // tracing::info!("  Rate:        {:.0} variants/sec", rate);
        // tracing::info!("═══════════════════════════════════════════");

        assert!(generated > 20, "Should generate many variants from 20 premises");
    }
}
