# [C5-REAL] Exergy-Maximized
"""
CORTEX Commit Poet Engine Data - LORCA-Ω
=========================================
Metaphors, signals, and heuristics for the sovereign CommitPoet engine.
Extracted to maintain O(1) complexity in the core engine.
"""

import re

# ── Commit type detection heuristics ──────────────────────────────────────────

TYPE_SIGNALS: dict[str, list[str]] = {
    "feat": ["new file", "added", "create", "implement", "introduce", "add"],
    "fix": ["fix", "bug", "error", "crash", "patch", "repair", "resolve"],
    "refactor": ["rename", "move", "restructure", "reorganize", "extract", "simplify"],
    "perf": ["optimize", "cache", "speed", "latency", "benchmark", "fast"],
    "docs": ["readme", "doc", "comment", "changelog", "license", "manifest"],
    "test": ["test", "spec", "assert", "mock", "fixture", "coverage"],
    "ci": ["ci", "github", "workflow", "pipeline", "deploy", "docker"],
    "style": ["lint", "format", "whitespace", "indent", "ruff", "pyright"],
    "chore": ["bump", "update", "upgrade", "dependency", "cleanup", "misc"],
}

# Precompiled O(1) regex for ultra-fast matching
TYPE_REGEX = {
    ctype: re.compile(r"\b(?:" + "|".join(map(re.escape, signals)) + r")\b", re.IGNORECASE)
    for ctype, signals in TYPE_SIGNALS.items()
}

# ── Metaphorical templates per commit type ────────────────────────────────────

TEMPLATES: dict[str, list[str]] = {
    "feat": [
        "ignite the {scope} reactor",
        "forge {scope} from the sovereign anvil",
        "crystallize {scope} into existence",
        "birth the {scope} neural pathway",
        "weave {scope} into the living membrane",
        "conjure {scope} from the thermodynamic void",
        "plant the {scope} seed in the sovereign garden",
        "give {scope} its first heartbeat",
        "awaken {scope} from the dormant lattice",
        "mint {scope} on the sovereign ledger",
        "carve {scope} into the bedrock",
        "distill {scope} from raw entropy",
        "unfurl the {scope} constellation",
        "lay the {scope} keystone",
        "inject {scope} into the bloodstream",
        "spark the {scope} ignition sequence",
        "graft {scope} onto the living architecture",
        "cast {scope} in sovereign alloy",
        "encode {scope} into the double helix",
        "terraform {scope} for habitation",
        "architect the {scope} cantilever",
        "nucleate {scope} in the supersaturated solution",
        "bootstrap {scope} from first principles",
        "deploy the {scope} vanguard",
        "summon {scope} through the event horizon",
        "initiate the autopoietic synthesis of {scope}",
        "harden the cryptographically secure vault of {scope}",
        "align {scope} with sovereign consensus invariants",
        "inject {scope} into the zero-copy ring lattice",
        "crystallize the Shannon entropy boundary of {scope}",
    ],
    "fix": [
        "cauterize the wound in {scope}",
        "exorcise the ghost haunting {scope}",
        "suture the breach in {scope}",
        "neutralize the pathogen in {scope}",
        "seal the entropy leak in {scope}",
        "realign the fractured {scope} axis",
        "purge the toxic residue from {scope}",
        "restore the broken symmetry of {scope}",
        "mend the torn fabric of {scope}",
        "extinguish the cascade failure in {scope}",
        "inoculate {scope} against regression",
        "quench the thermal runaway in {scope}",
        "stabilize the {scope} orbit decay",
        "drain the abscess from {scope}",
        "rethread the severed {scope} nerve",
        "annihilate the phantom signal in {scope}",
        "close the gravitational wound in {scope}",
        "extract the embedded shrapnel from {scope}",
        "recalibrate the {scope} drift correction",
        "defuse the silent detonator in {scope}",
        "resolve non-deterministic state drift in {scope}",
        "mitigate thermodynamic leakage in {scope}",
        "patch the cryptographic vulnerability in {scope}",
        "heal the fractured memory manifold of {scope}",
        "reconcile split-brain consensus in {scope}",
        "enforce cache coherence in {scope}",
    ],
    "refactor": [
        "metamorphose {scope} to its sovereign form",
        "annihilate entropy accumulated in {scope}",
        "purify the {scope} signal",
        "distill {scope} to its irreducible essence",
        "transmute the {scope} lead into gold",
        "strip {scope} to the structural bone",
        "reforge {scope} in the crucible",
        "compress the {scope} wavefunction",
        "untangle the {scope} gordian knot",
        "temper {scope} through sovereign heat treatment",
        "sculpt {scope} with subtractive precision",
        "realign {scope} along the geodesic",
        "collapse the {scope} redundancy manifold",
        "anoint {scope} with O(1) clarity",
        "shed the vestigial exoskeleton of {scope}",
        "elevate {scope} from clay to marble",
        "decouple the {scope} gravitational binding",
        "crystallize {scope} into its final polymorph",
        "extract the {scope} signal from thermal noise",
        "prune the {scope} dead branches",
        "compress {scope} to its minimum entropy boundary",
        "decouple {scope} to unlock lock-free execution",
        "transmute {scope} to a zero-copy representation",
        "flatten the recursive abstraction stack in {scope}",
    ],
    "perf": [
        "accelerate {scope} beyond escape velocity",
        "compress spacetime in the {scope} pipeline",
        "shatter the {scope} latency barrier",
        "overclock the {scope} throughput reactor",
        "eliminate the {scope} friction coefficient",
        "superconduct the {scope} critical path",
        "collapse the {scope} computational manifold",
        "inject nitrous into the {scope} engine",
        "achieve {scope} terminal velocity",
        "liquefy the {scope} bottleneck",
        "tune {scope} to resonant frequency",
        "strip aerodynamic drag from {scope}",
        "unlock the {scope} warp drive",
        "anneal {scope} for zero-resistance flow",
        "vaporize the {scope} memory overhead",
        "reduce {scope} latency to O(1) complexity",
        "streamline the zero-copy pathway in {scope}",
        "optimize thermodynamic efficiency in {scope}",
        "minimize latency spikes in {scope}",
    ],
    "docs": [
        "inscribe the scripture of {scope}",
        "illuminate the dark matter of {scope}",
        "chart the {scope} territory for future navigators",
        "engrave {scope} wisdom into the stone tablet",
        "decode the {scope} rosetta stone",
        "author the {scope} survival manual",
        "map the {scope} cartography for the swarm",
        "chronicle the {scope} epoch transition",
        "translate {scope} from machine to human",
        "annotate the {scope} archaeological record",
        "index the {scope} sovereign knowledge base",
        "publish the {scope} field reconnaissance",
    ],
    "test": [
        "deploy the verification membrane around {scope}",
        "probe the structural integrity of {scope}",
        "fire the {scope} stress test barrage",
        "inoculate {scope} with regression antibodies",
        "construct the {scope} byzantine fault detector",
        "erect the {scope} perimeter defense grid",
        "simulate {scope} under adversarial conditions",
        "calibrate the {scope} truth oracle",
        "arm the {scope} tripwire network",
        "subject {scope} to sovereign audit",
        "validate the {scope} invariant fortress",
        "deploy chaos probes against {scope}",
        "deploy invariant validation guards for {scope}",
        "stress-test the Byzantine fault limits of {scope}",
        "probe the entropic boundary of {scope}",
        "fuzz the cryptographic inputs of {scope}",
    ],
    "ci": [
        "wire the {scope} deployment pipeline",
        "automate the {scope} launch sequence",
        "install the {scope} continuous forge",
        "activate the {scope} autonomous build reactor",
        "harden the {scope} delivery corridor",
        "establish the {scope} sovereign supply chain",
        "provision the {scope} orbital deployment",
        "arm the {scope} release catapult",
    ],
    "style": [
        "polish the {scope} sovereign surface",
        "align the {scope} crystalline lattice",
        "discipline the {scope} visual rhythm",
        "harmonize the {scope} typographic frequency",
        "enforce the {scope} aesthetic constitution",
        "calibrate the {scope} formatting resonance",
    ],
    "chore": [
        "maintain the {scope} sovereign substrate",
        "renew the {scope} cosmic infrastructure",
        "tend the {scope} orbital machinery",
        "recycle the {scope} thermal waste",
        "service the {scope} autonomous systems",
        "lubricate the {scope} kinetic bearings",
        "rotate the {scope} cryptographic seals",
        "restock the {scope} supply depot",
    ],
    "revert": [
        "reverse the {scope} temporal anomaly",
        "undo the {scope} spacetime distortion",
        "roll back the {scope} failed mutation",
        "recall the {scope} defective deployment",
    ],
}

# ── Emoji signatures per commit type ──────────────────────────────────────────

EMOJI_MAP: dict[str, list[str]] = {
    "feat": ["⚡", "🧬", "🔮", "🌱", "🏗️", "💎", "🚀", "🔥", "✨", "🧊"],
    "fix": ["🩹", "🔧", "🛡️", "💉", "🩺", "⚕️", "🔒", "🧯", "🪡", "🗡️"],
    "refactor": ["♻️", "🔬", "⚗️", "🪨", "🧹", "🧹", "🌀", "🔭", "🪞", "🫧", "🧱"],
    "perf": ["⚡", "🏎️", "💨", "🔋", "⏱️", "🦅", "🌊", "🧲", "🔩", "🛸"],
    "docs": ["📜", "🗺️", "📡", "🔍", "📖", "🧭", "📐", "📐", "🏛️", "📋", "🪶"],
    "test": ["🧪", "🛡️", "🎯", "🔬", "🧫", "🏹", "⚔️", "🪤", "🔎", "🧿"],
    "ci": ["🏭", "🤖", "⚙️", "🔗", "🛰️", "📦", "🧰", "🪝"],
    "style": ["🎨", "💅", "📏", "✏️", "🖋️", "🔲"],
    "chore": ["🔄", "🧹", "🛠️", "📎", "🗂️", "🪛", "⛽", "🧴"],
    "revert": ["⏪", "🔙", "↩️", "🕐"],
}

# ── Scope extraction from file paths ─────────────────────────────────────────

SCOPE_MAP: dict[str, str] = {
    "engine": "engine",
    "memory": "memory",
    "search": "search",
    "graph": "graph",
    "cli": "cli",
    "api": "api",
    "routes": "routes",
    "mcp": "mcp",
    "auth": "auth",
    "crypto": "crypto",
    "security": "security",
    "guards": "guards",
    "audit": "audit",
    "ledger": "ledger",
    "embeddings": "embeddings",
    "llm": "llm",
    "agents": "agents",
    "swarm": "swarm",
    "tests": "tests",
    "daemon": "daemon",
    "config": "config",
    "migrate": "migrations",
    "notifications": "notifications",
    "telemetry": "telemetry",
    "evolution": "evolution",
    "axioms": "axioms",
    "skills": "skills",
    "immune": "immune",
    "consensus": "consensus",
    "git": "git",
    "web": "web",
    "docs": "docs",
    "scripts": "scripts",
    "compaction": "compaction",
    "context": "context",
    "storage": "storage",
    "database": "database",
    "sync": "sync",
    "hive": "hive",
    "alma": "alma",
    "thinking": "thinking",
    "perception": "perception",
    "platform": "platform",
    "signals": "signals",
    "events": "events",
    "sovereign": "sovereign",
    "hypervisor": "hypervisor",
    "adk": "adk",
    "compat": "compat",
    "compliance": "compliance",
    "composer": "composer",
    "darknet": "darknet",
    "delivery": "delivery",
    "enrichment": "enrichment",
    "facts": "facts",
    "forensics": "forensics",
    "gateway": "gateway",
    "http": "http",
    "mac_maestro": "mac_maestro",
    "mcts": "mcts",
    "pipeline": "pipeline",
    "router": "router",
    "services": "services",
    "shannon": "shannon",
    "types": "types",
    "utils": "utils",
    "verification": "verification",
    "worker": "worker",
    "ouroboros": "ouroboros",
    "aeon": "aeon",
    "ring_buffer": "ring_buffer",
    "aof": "aof",
    "cortex_rs": "cortex_rs",
}
