# C5-REAL EXERGY CERTIFIED
[workspace]
resolver = "2"
members = [
    "src/cortex-engine/kernel",
    "src/cortex-engine/cortex-wasm",
    "src/cortex-engine/cortex-persist/kernel_rs",
    "src/cortex-engine/strike-rs",
    "src/moskv-daemon",
    "src/legion-engine/legion-core",
    "src/legion-engine/legion-apfs",
    "src/legion-engine/legion-exergy",
    "src/legion-engine/legion-healer",
    "src/legion-engine/legion-cli",
    "src/legion-engine/legion-lang",
    "tests/compliance-suite"
]

# Perfil para desarrollo rápido (Alineado con el C5-REAL)
[profile.dev]
opt-level = 0
debug = true

# Perfil C5-REAL para despliegue
[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort" # Invariante Fail-Stop: no hacer unrolling de stack en errores críticos
