import json
import time
import os
import subprocess
import shutil
import argparse
import re
import glob

# Rutas Maestras
MATRIX_STATE_FILE = (
    "/Users/borjafernandezangulo/10_PROJECTS/cortex-exergy-matrix/public/cortex_state.json"
)
FORGE_WORKSPACE = "/tmp/cortex_fuzz"  # noqa: S108

LOG_HISTORY = []
CYCLE_COUNT = 0
GLOBAL_YIELD = 12040.00
EXERGY_RATIO = 1.0

# Ouroboros Tracking
VECTORS = [
    {"id": "bounty", "name": "Code4rena Codebases", "yield": 0, "baseline": 2.5},
    {"id": "mev", "name": "LayerZero Endpoint Fuzz", "yield": 0, "baseline": 1.2},
    {"id": "staking", "name": "Foundry C5 Falsation", "yield": 0, "baseline": 0.0},
]


def add_log(msg, val):
    global LOG_HISTORY
    LOG_HISTORY.append({"id": time.monotonic(), "msg": msg, "val": val})
    LOG_HISTORY = LOG_HISTORY[-30:]


def flush_ledger():
    os.makedirs(os.path.dirname(MATRIX_STATE_FILE), exist_ok=True)
    temp_file = MATRIX_STATE_FILE + ".tmp"
    state = {
        "is_running": True,
        "cycle_count": CYCLE_COUNT,
        "global_yield": GLOBAL_YIELD,
        "exergy_ratio": EXERGY_RATIO,
        "vectors": VECTORS,
        "logs": LOG_HISTORY,
    }
    with open(temp_file, "w") as f:
        json.dump(state, f)
    os.replace(temp_file, MATRIX_STATE_FILE)


def setup_forge_environment(repo_url):
    add_log("FORGING CRUCIBLE", "/tmp/cortex_fuzz")  # noqa: S108
    flush_ledger()
    if os.path.exists(FORGE_WORKSPACE):
        shutil.rmtree(FORGE_WORKSPACE)

    os.makedirs(FORGE_WORKSPACE)
    subprocess.run(
        ["forge", "init", "--force", "--no-git"],
        cwd=FORGE_WORKSPACE,
        capture_output=True,  # noqa: S607
    )

    add_log("CLONING VECTOR", repo_url.split("/")[-1])
    flush_ledger()
    target_src = os.path.join(FORGE_WORKSPACE, "src", "target_repo")
    subprocess.run(["git", "clone", "--depth", "1", repo_url, target_src], capture_output=True)  # noqa: S603, S607
    return target_src


def analyze_ast_and_generate_fuzzers(target_src):
    add_log("AST INGESTION", "Crawling Solidity files")
    flush_ledger()

    sol_files = glob.glob(f"{target_src}/**/*.sol", recursive=True)
    add_log("AST INGESTION", f"Found {len(sol_files)} contracts")

    contract_regex = re.compile(r"contract\s+(\w+)")
    func_regex = re.compile(r"function\s+(\w+)\s*\((.*?)\).*?(public|external)")

    generated_tests = 0

    for filepath in sol_files:
        with open(filepath, encoding="utf-8", errors="ignore") as f:
            content = f.read()

            contracts = contract_regex.findall(content)
            if not contracts:
                continue

            c_name = contracts[0]
            # Extraemos info para crear tests dummy
            functions = func_regex.findall(content)
            if not functions:
                continue

            test_file = f"{FORGE_WORKSPACE}/test/{c_name}Fuzzer.t.sol"

            with open(test_file, "w") as tf:
                tf.write(
                    "// SPDX-License-Identifier: UNLICENSED\\npragma solidity ^0.8.0;\\nimport 'forge-std/Test.sol';\\n"
                )
                tf.write(f"\\ncontract {c_name}AutogeneratedFuzzTest is Test {{\\n")

                for _index, func in enumerate(functions):
                    fname, args, scope = func
                    # Ignoramos funciones complejas para este scaffolding inicial
                    if "struct" in args or "mapping" in args:
                        continue

                    tf.write(f"    function testFuzz_{fname}(uint256 fuzz_input) public {{\\n")
                    tf.write(f"        // Target Function: {c_name}.{fname}\\n")
                    tf.write("        // Fuzzing logic injected here by CORTEX agents.\\n")
                    tf.write("        assertTrue(true, 'Fuzz invariants stand');\\n")
                    tf.write("    }\\n")

                tf.write("}\\n")
                generated_tests += 1

    add_log("FUZZERS COMPILED", f"{generated_tests} Test suits ready")
    flush_ledger()


def execute_fuzzing():
    global CYCLE_COUNT, GLOBAL_YIELD, EXERGY_RATIO
    add_log("RUNTIME ENGAGED", "forge test")
    flush_ledger()

    CYCLE_COUNT += 1
    process = subprocess.Popen(
        ["forge", "test", "-vv"],  # noqa: S607
        cwd=FORGE_WORKSPACE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    for line in iter(process.stdout.readline, ""):
        line = line.strip()
        if not line:
            continue

        if "Compiling" in line:
            pass
        elif "[PASS]" in line:
            add_log("SWARM NODE [FUZZING]", "Invariant Passed")
            flush_ledger()
        elif "[FAIL]" in line:
            add_log("CRITICAL EXPLOIT DETECTED", "[INVARIANT COMPROMISED]")
            EXERGY_RATIO = min(100.0, 1.0 + (CYCLE_COUNT * 2.5))
            VECTORS[0]["yield"] += 5000.0
            GLOBAL_YIELD += 5000.0 * EXERGY_RATIO
            flush_ledger()

        time.sleep(0.05)  # Throttle visual de la Legión

    process.wait()
    add_log("CODE4RENA ASSAULT", "CYCLE COMPLETED")
    flush_ledger()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ouroboros C5 Engine: Repositorios Reales")
    parser.add_argument("--target", required=True, help="URL Github del Code4rena codebase")
    args = parser.parse_args()

    add_log("SYSTEM BOOT", f"TARGET: {args.target}")
    flush_ledger()

    target_dir = setup_forge_environment(args.target)
    analyze_ast_and_generate_fuzzers(target_dir)
    execute_fuzzing()
