#!/usr/bin/env python3
"""
∴ CORTEX-IMMUNEFI-REPORT-GENERATOR v1.0
Generates submission-ready Immunefi reports from C5-REAL verified exploits.

Input: STRIKEResult + HoundFinding
Output: Markdown report ready for Immunefi submission

∴ Axiom Ω₉: Only C5-REAL findings generate reports. C5-PENDING is rejected.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
REPORTS_DIR = SCRIPTS_DIR.parent / "reports" / "immunefi"

C = {
    "B": "\033[38;2;43;59;229m",
    "G": "\033[38;2;0;255;136m",
    "R": "\033[38;2;255;59;48m",
    "D": "\033[38;2;90;90;90m",
    "W": "\033[97m",
    "X": "\033[0m",
}

SEVERITY_MAP = {
    "critical": {"label": "Critical", "impact": "Direct theft or permanent freezing of funds"},
    "high": {"label": "High", "impact": "Temporary freezing of funds or protocol disruption"},
    "medium": {"label": "Medium", "impact": "Griefing or limited state corruption"},
    "low": {"label": "Low", "impact": "Informational or best practice violation"},
}


@dataclass
class ReportInput:
    """All data needed to generate a submission report."""
    target_name: str
    vuln_type: str
    hypothesis: str
    severity: str
    target_url: str
    STRIKE_code: str
    forge_output: str
    target_code_snippet: str
    exploit_plan: str


def generate_report(report_input: ReportInput) -> Path:
    """Generate a submission-ready Immunefi report in Markdown."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    severity_info = SEVERITY_MAP.get(report_input.severity.lower(), SEVERITY_MAP["critical"])
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    safe_name = report_input.target_name.replace(" ", "_").replace("/", "_")[:40]
    report_filename = f"report_{safe_name}_{report_input.vuln_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path = REPORTS_DIR / report_filename

    # Extract test results from forge output
    test_summary = _extract_test_summary(report_input.forge_output)

    report_content = f"""# Bug Report: {report_input.vuln_type.replace('_', ' ').title()} in {report_input.target_name}

**Submitted via**: Immunefi Bug Bounty Program
**Date**: {timestamp}
**Severity**: {severity_info['label']}
**Impact Category**: {severity_info['impact']}

---

## Summary

A {report_input.vuln_type.replace('_', ' ')} vulnerability was identified in **{report_input.target_name}**. This vulnerability allows an attacker to {report_input.hypothesis.lower()}.

**Target**: {report_input.target_url}

## Vulnerability Details

### Root Cause

{report_input.exploit_plan}

### Affected Code

```solidity
{report_input.target_code_snippet[:3000]}
```

## Impact

**Severity**: {severity_info['label']}

{_generate_impact_description(report_input)}

## Proof of Concept

The following Foundry test demonstrates the vulnerability. It can be executed with:

```bash
forge test --match-test testExploit -vvv
```

### Test Contract

```solidity
{report_input.STRIKE_code}
```

### Test Output

```
{test_summary}
```

## Recommendation

{_generate_recommendation(report_input)}

---

*Generated by CORTEX-Autodidact-Ω — C5-REAL Verified*
"""

    report_path.write_text(report_content.strip(), encoding="utf-8")

    print(f"\n{C['G']}[✓] Report generated:{C['X']} {report_path}")
    print(f"  {C['D']}Severity:{C['X']} {severity_info['label']}")
    print(f"  {C['D']}Length:{C['X']} {len(report_content)} chars")

    return report_path


def _extract_test_summary(forge_output: str) -> str:
    """Extract the relevant portions of forge test output."""
    lines = forge_output.split("\n")
    relevant = []
    capture = False
    for line in lines:
        if "Running" in line or "Test result" in line or "EXPLOIT" in line:
            capture = True
        if capture:
            relevant.append(line)
        if len(relevant) > 30:
            break
    return "\n".join(relevant) if relevant else forge_output[:1000]


def _generate_impact_description(report_input: ReportInput) -> str:
    """Generate an impact description based on vulnerability type."""
    vuln = report_input.vuln_type.lower()
    if "reentrancy" in vuln:
        return (
            "An attacker can re-enter the withdrawal function before the state is updated, "
            "draining all funds from the contract. The proof of concept demonstrates that "
            "the attacker can extract more than their deposited amount in a single transaction."
        )
    elif "flash" in vuln:
        return (
            "An attacker can use a flash loan to manipulate the protocol's internal state, "
            "extracting value without providing collateral. The demonstrated attack is atomic "
            "and requires no upfront capital."
        )
    elif "access" in vuln:
        return (
            "An unprivileged user can invoke functions intended only for administrators, "
            "potentially modifying critical protocol parameters, pausing the contract, "
            "or directly extracting funds."
        )
    elif "oracle" in vuln or "price" in vuln:
        return (
            "An attacker can manipulate the price oracle used by the protocol, allowing them "
            "to borrow against inflated collateral or liquidate positions at incorrect prices. "
            "This can lead to protocol insolvency."
        )
    return (
        f"The {report_input.vuln_type} vulnerability allows an attacker to "
        f"{report_input.hypothesis}. See the proof of concept for full details."
    )


def _generate_recommendation(report_input: ReportInput) -> str:
    """Generate a fix recommendation based on vulnerability type."""
    vuln = report_input.vuln_type.lower()
    if "reentrancy" in vuln:
        return (
            "1. Apply the checks-effects-interactions pattern\n"
            "2. Use OpenZeppelin's `ReentrancyGuard` (`nonReentrant` modifier)\n"
            "3. Update state variables before making external calls"
        )
    elif "flash" in vuln:
        return (
            "1. Implement flash loan-resistant price oracles (TWAP)\n"
            "2. Add minimum holding period checks\n"
            "3. Use access control to restrict flash loan callbacks"
        )
    elif "access" in vuln:
        return (
            "1. Implement proper access control (OpenZeppelin `Ownable` or `AccessControl`)\n"
            "2. Add `onlyOwner` or role-based modifiers to privileged functions\n"
            "3. Review all state-changing functions for missing authorization checks"
        )
    elif "oracle" in vuln or "price" in vuln:
        return (
            "1. Use time-weighted average price (TWAP) oracles\n"
            "2. Implement circuit breakers for large price deviations\n"
            "3. Use multiple independent oracle sources (Chainlink, TWAP, etc.)"
        )
    return "Review and patch the vulnerable code path identified in the proof of concept."


if __name__ == "__main__":
    # Self-test
    test_input = ReportInput(
        target_name="TestProtocol",
        vuln_type="reentrancy",
        hypothesis="drain all funds from the vault contract via recursive withdraw calls",
        severity="critical",
        target_url="https://github.com/example/protocol",
        STRIKE_code="// Self-test genesis",
        forge_output="Test result: ok (1 passed)",
        target_code_snippet="function withdraw() external { /* vulnerable */ }",
        exploit_plan="The withdraw function sends ETH before updating the balance state variable.",
    )
    path = generate_report(test_input)
    print(f"Report written to: {path}")
