(ns agent.reflexion
  "Reflexion Loop — Self-Healing for GitHub Actions (Level 5).

   Implements the same Reflexion pattern as cortex/engine/reflexion.py
   but in Clojure, operating on GitHub Actions workflow runs:

   1. MONITOR — Observe workflow run outcomes
   2. DIAGNOSE — Classify failure patterns
   3. REFLECT — Generate structured analysis
   4. REWRITE — Modify workflow YAML to prevent recurrence

   This is the meta-agent that thinks about its own CI/CD pipeline.

   Reality Level: C5-REAL"
  (:require [agent.github :as gh]
            [agent.workflow :as wf]
            [clojure.string :as str]))


;; ─── Failure Pattern Database ───────────────────────────────────


(def failure-patterns
  "Deterministic diagnosis patterns. Each maps error signals to
   structured reflections and proposed fixes."
  [{:id       :timeout
    :match-fn (fn [run] (= "timed_out" (:conclusion run)))
    :diagnosis "Workflow exceeded time limit. Likely I/O bound step or hung process."
    :fix-fn   (fn [workflow]
                (wf/add-timeout-to-jobs workflow 30))}

   {:id       :cancelled
    :match-fn (fn [run] (= "cancelled" (:conclusion run)))
    :diagnosis "Run was cancelled — likely superseded by a newer commit push."
    :fix-fn   (fn [workflow]
                (wf/add-concurrency-guard workflow
                  "${{ github.workflow }}-${{ github.ref }}" true))}

   {:id       :flaky-test
    :match-fn (fn [run]
                (and (= "failure" (:conclusion run))
                     (> (:run_attempt run) 1)))
    :diagnosis "Test flakiness detected — run succeeded on retry, indicating non-determinism."
    :fix-fn   identity}  ; Log only, no auto-fix for flakiness

   {:id       :action-version-drift
    :match-fn (fn [run]
                (and (= "failure" (:conclusion run))
                     (some-> run :name (str/includes? "checkout"))))
    :diagnosis "Possible action version incompatibility or drift."
    :fix-fn   (fn [workflow]
                (wf/pin-action-version workflow "actions/checkout" "v4"))}])


;; ─── Reflection Data Structure ──────────────────────────────────


(defn create-reflection
  "Create a structured reflection from a failed workflow run."
  [run pattern]
  {:run-id      (:id run)
   :workflow    (:name run)
   :conclusion  (:conclusion run)
   :attempt     (:run_attempt run)
   :pattern-id  (:id pattern)
   :diagnosis   (:diagnosis pattern)
   :timestamp   (System/currentTimeMillis)
   :branch      (get-in run [:head_branch])
   :commit      (get-in run [:head_sha])})


;; ─── Diagnosis Engine ───────────────────────────────────────────


(defn diagnose-run
  "Analyze a workflow run against known failure patterns.
   Returns the first matching pattern, or a generic reflection."
  [run]
  (or (first (filter #((:match-fn %) run) failure-patterns))
      {:id        :unknown
       :match-fn  (constantly true)
       :diagnosis (str "Unclassified failure: " (:conclusion run)
                       " in workflow '" (:name run) "'")
       :fix-fn    identity}))


(defn diagnose-recent-failures
  "Analyze all recent failed runs and return structured reflections."
  [ctx & {:keys [limit] :or {limit 10}}]
  (let [runs (-> (gh/list-workflow-runs ctx :status "failure" :per-page limit)
                 :workflow_runs)]
    (for [run runs
          :let [pattern (diagnose-run run)]]
      (create-reflection run pattern))))


;; ─── Self-Healing Actions ───────────────────────────────────────


(defn apply-fix
  "Apply a fix function to a workflow YAML string.
   Returns the modified YAML string.

   This is the L7 moment: the agent reads its own workflow,
   manipulates it as data, and produces a corrected version."
  [workflow-yaml-str pattern]
  (let [workflow (wf/parse-workflow workflow-yaml-str)
        fixed    ((:fix-fn pattern) workflow)]
    (wf/emit-workflow fixed)))


(defn generate-reflexion-report
  "Generate a markdown report from accumulated reflections."
  [reflections]
  (let [by-pattern (group-by :pattern-id reflections)]
    (str "## 🔄 CORTEX Reflexion Report\n\n"
         "| Pattern | Count | Last Diagnosis |\n"
         "|---------|-------|----------------|\n"
         (str/join "\n"
           (for [[pattern-id items] by-pattern]
             (str "| `" (name pattern-id) "` "
                  "| " (count items) " "
                  "| " (:diagnosis (last items)) " |")))
         "\n\n"
         "**Total failures analyzed:** " (count reflections) "\n"
         "**Unique patterns:** " (count by-pattern) "\n"
         "**Generated by:** MÖBIUS (Clojure/Babashka) — ∞ code IS data\n")))


;; ─── The Reflexion Loop ─────────────────────────────────────────


(defn reflexion-cycle!
  "Execute one full reflexion cycle:
   1. Monitor recent failures
   2. Diagnose patterns
   3. Generate report
   4. Optionally apply fixes

   Returns: {:reflections [...] :report \"...\" :fixes-applied [...]}

   This is the main entry point for the GitHub Actions workflow."
  [ctx & {:keys [auto-fix? workflow-path]
          :or   {auto-fix? false
                 workflow-path ".github/workflows/ci.yml"}}]
  (println "🔄 [REFLEXION] Starting reflexion cycle...")

  ;; 1. MONITOR — Fetch recent failures
  (let [reflections (diagnose-recent-failures ctx :limit 10)]

    (if (empty? reflections)
      (do
        (println "✅ [REFLEXION] No recent failures. System healthy.")
        {:reflections [] :report "No failures detected." :fixes-applied []})

      (let [;; 2. DIAGNOSE — Already done in diagnose-recent-failures
            report (generate-reflexion-report reflections)

            ;; 3. REFLECT — Print report
            _ (println report)

            ;; 4. REWRITE — Apply fixes if enabled
            fixes-applied
            (when auto-fix?
              (let [file-data (gh/get-file-content ctx workflow-path)
                    yaml-str  (:decoded-content file-data)]
                (when yaml-str
                  (let [patterns  (distinct (map :pattern-id reflections))
                        ;; Apply all matching fix functions in sequence
                        fixed-yaml (reduce
                                     (fn [yaml pid]
                                       (let [pattern (first (filter #(= pid (:id %))
                                                                   failure-patterns))]
                                         (if pattern
                                           (apply-fix yaml pattern)
                                           yaml)))
                                     yaml-str
                                     patterns)]
                    (when (not= yaml-str fixed-yaml)
                      (println "🔧 [REFLEXION] Applying fixes to" workflow-path)
                      [{:path workflow-path
                        :original-size (count yaml-str)
                        :fixed-size (count fixed-yaml)
                        :patterns-applied patterns}])))))]

        {:reflections    (vec reflections)
         :report         report
         :fixes-applied  (or fixes-applied [])}))))
