/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`batch_store_v1_facts_batch_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BatchStoreV1FactsBatchPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cast_vote_v1_facts_fact_id_vote_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CastVoteV1FactsFactIdVotePostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cast_vote_v2_v1_facts_fact_id_vote_v2_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CastVoteV2V1FactsFactIdVoteV2PostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`deprecate_fact_v1_facts_fact_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeprecateFactV1FactsFactIdDeleteError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_causal_chain_v1_facts_fact_id_chain_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCausalChainV1FactsFactIdChainGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_fact_by_id_v1_facts_fact_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFactByIdV1FactsFactIdGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_fact_history_v1_facts_fact_id_history_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFactHistoryV1FactsFactIdHistoryGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_all_facts_v1_facts_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListAllFactsV1FactsGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_votes_v1_facts_fact_id_votes_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListVotesV1FactsFactIdVotesGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`propagate_taint_v1_facts_fact_id_taint_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PropagateTaintV1FactsFactIdTaintPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`recall_facts_v1_projects_project_facts_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecallFactsV1ProjectsProjectFactsGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_facts_v1_facts_search_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchFactsV1FactsSearchPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`store_fact_v1_facts_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StoreFactV1FactsPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`verify_ledger_v1_facts_verify_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyLedgerV1FactsVerifyGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}


/// Batch store up to 100 facts in a single request.
pub async fn batch_store_v1_facts_batch_post(configuration: &configuration::Configuration, batch_store_request: models::BatchStoreRequest, authorization: Option<&str>) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<BatchStoreV1FactsBatchPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_batch_store_request = batch_store_request;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/batch", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    req_builder = req_builder.json(&p_body_batch_store_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BatchStoreV1FactsBatchPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Cast a consensus vote (verify/dispute) on a fact.
pub async fn cast_vote_v1_facts_fact_id_vote_post(configuration: &configuration::Configuration, fact_id: i32, vote_request: models::VoteRequest, authorization: Option<&str>) -> Result<models::VoteResponse, Error<CastVoteV1FactsFactIdVotePostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_body_vote_request = vote_request;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}/vote", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    req_builder = req_builder.json(&p_body_vote_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VoteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VoteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CastVoteV1FactsFactIdVotePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Cast a reputation-weighted consensus vote (RWC).
pub async fn cast_vote_v2_v1_facts_fact_id_vote_v2_post(configuration: &configuration::Configuration, fact_id: i32, vote_v2_request: models::VoteV2Request, authorization: Option<&str>) -> Result<models::VoteResponse, Error<CastVoteV2V1FactsFactIdVoteV2PostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_body_vote_v2_request = vote_v2_request;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}/vote-v2", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    req_builder = req_builder.json(&p_body_vote_v2_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VoteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VoteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CastVoteV2V1FactsFactIdVoteV2PostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Soft-deprecate a fact (mark as invalid).
pub async fn deprecate_fact_v1_facts_fact_id_delete(configuration: &configuration::Configuration, fact_id: i32, authorization: Option<&str>) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<DeprecateFactV1FactsFactIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeprecateFactV1FactsFactIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the causal chain for a fact (up=ancestors, down=descendants).
pub async fn get_causal_chain_v1_facts_fact_id_chain_get(configuration: &configuration::Configuration, fact_id: i32, direction: Option<&str>, max_depth: Option<i32>, authorization: Option<&str>) -> Result<Vec<std::collections::HashMap<String, serde_json::Value>>, Error<GetCausalChainV1FactsFactIdChainGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_query_direction = direction;
    let p_query_max_depth = max_depth;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}/chain", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_direction {
        req_builder = req_builder.query(&[("direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_depth {
        req_builder = req_builder.query(&[("max_depth", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;std::collections::HashMap&lt;String, serde_json::Value&gt;&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;std::collections::HashMap&lt;String, serde_json::Value&gt;&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCausalChainV1FactsFactIdChainGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a single fact by ID.
pub async fn get_fact_by_id_v1_facts_fact_id_get(configuration: &configuration::Configuration, fact_id: i32, authorization: Option<&str>) -> Result<models::FactResponse, Error<GetFactByIdV1FactsFactIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FactResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FactResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFactByIdV1FactsFactIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve version history for a specific fact.
pub async fn get_fact_history_v1_facts_fact_id_history_get(configuration: &configuration::Configuration, fact_id: i32, authorization: Option<&str>) -> Result<Vec<models::FactResponse>, Error<GetFactHistoryV1FactsFactIdHistoryGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}/history", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFactHistoryV1FactsFactIdHistoryGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_all_facts_v1_facts_get(configuration: &configuration::Configuration, limit: Option<i32>, authorization: Option<&str>) -> Result<Vec<models::FactResponse>, Error<ListAllFactsV1FactsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_limit = limit;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListAllFactsV1FactsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve all votes for a specific fact (Tenant Isolated).
pub async fn list_votes_v1_facts_fact_id_votes_get(configuration: &configuration::Configuration, fact_id: i32, authorization: Option<&str>) -> Result<Vec<std::collections::HashMap<String, serde_json::Value>>, Error<ListVotesV1FactsFactIdVotesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}/votes", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;std::collections::HashMap&lt;String, serde_json::Value&gt;&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;std::collections::HashMap&lt;String, serde_json::Value&gt;&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListVotesV1FactsFactIdVotesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Trigger Ω₁₃ taint propagation from a compromised/invalidated fact.
pub async fn propagate_taint_v1_facts_fact_id_taint_post(configuration: &configuration::Configuration, fact_id: i32, authorization: Option<&str>) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<PropagateTaintV1FactsFactIdTaintPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fact_id = fact_id;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/{fact_id}/taint", configuration.base_path, fact_id=p_path_fact_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PropagateTaintV1FactsFactIdTaintPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Recall facts for a specific project with tenant isolation.
pub async fn recall_facts_v1_projects_project_facts_get(configuration: &configuration::Configuration, project: &str, limit: Option<i32>, authorization: Option<&str>) -> Result<Vec<models::FactResponse>, Error<RecallFactsV1ProjectsProjectFactsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project = project;
    let p_query_limit = limit;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/projects/{project}/facts", configuration.base_path, project=crate::apis::urlencode(p_path_project));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RecallFactsV1ProjectsProjectFactsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Semantic search across all facts (scoped to tenant).
pub async fn search_facts_v1_facts_search_post(configuration: &configuration::Configuration, search_memory_request: models::SearchMemoryRequest, authorization: Option<&str>) -> Result<Vec<models::FactResponse>, Error<SearchFactsV1FactsSearchPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_search_memory_request = search_memory_request;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/search", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    req_builder = req_builder.json(&p_body_search_memory_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::FactResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchFactsV1FactsSearchPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Store a fact (scoped to authenticated tenant).
pub async fn store_fact_v1_facts_post(configuration: &configuration::Configuration, store_request: models::StoreRequest, authorization: Option<&str>) -> Result<models::StoreResponse, Error<StoreFactV1FactsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_store_request = store_request;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    req_builder = req_builder.json(&p_body_store_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StoreResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StoreResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StoreFactV1FactsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Verify cryptographic integrity of the memory ledger.
pub async fn verify_ledger_v1_facts_verify_get(configuration: &configuration::Configuration, authorization: Option<&str>) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<VerifyLedgerV1FactsVerifyGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/facts/verify", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<VerifyLedgerV1FactsVerifyGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

