/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`translate_texts_v1_translate_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TranslateTextsV1TranslatePostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}


/// OMNI-TRANSLATE: Sovereign Core translation endpoint.  Translates a dictionary of texts into multiple target languages simultaneously using Gemini 2.0 Flash for optimal speed and cost. Ensures that the output strictly matches the input schema.
pub async fn translate_texts_v1_translate_post(configuration: &configuration::Configuration, translate_request: models::TranslateRequest, authorization: Option<&str>) -> Result<models::TranslateResponse, Error<TranslateTextsV1TranslatePostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_translate_request = translate_request;
    let p_header_authorization = authorization;

    let uri_str = format!("{}/v1/translate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    req_builder = req_builder.json(&p_body_translate_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TranslateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TranslateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TranslateTextsV1TranslatePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

