# C5-REAL EXERGY CERTIFIED
import argparse
import os
import sys
import pickle
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# Invariante C5-REAL: Sin fricción adicional. Un único scope.
SCOPES = ['https://www.googleapis.com/auth/youtube.upload']

def main():
    parser = argparse.ArgumentParser(description='C5-REAL YouTube Transducer')
    parser.add_argument('--file', required=True, help='Ruta absoluta o relativa del vídeo.')
    parser.add_argument('--title', required=True, help='Título del vídeo.')
    args = parser.parse_args()

    video_path = args.file
    if not os.path.exists(video_path):
        print(f"[FATAL] El archivo de vídeo no existe en la realidad física: {video_path}")
        sys.exit(1)

    creds = None
    script_dir = os.path.dirname(os.path.realpath(__file__))
    token_path = os.path.join(script_dir, 'token.pickle')
    client_secrets_path = os.path.join(script_dir, 'client_secrets.json')

    # Intentar cargar estado latente (token)
    if os.path.exists(token_path):
        with open(token_path, 'rb') as token:
            creds = pickle.load(token)

    # Si no hay credenciales o expiraron, colapsamos la onda
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("[CORTEX] Exergía detectada. Refrescando token OAuth de forma autónoma...")
            creds.refresh(Request())
        else:
            # Fricción biológica inicial requerida
            if not os.path.exists(client_secrets_path):
                print(f"\n[FATAL] Fricción Biológica Detectada (Falta client_secrets.json)\n")
                print("La asimilación de YouTube requiere delegación de autoridad.")
                print("Descarga el client_secrets.json desde Google Cloud Console y colócalo en:")
                print(f"👉 {client_secrets_path}")
                sys.exit(1)

            print("[CORTEX] Solicitando nuevo token OAuth (Intervención humana requerida 1 sola vez)...")
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets_path, SCOPES)
            creds = flow.run_local_server(port=0)

        # Persistir el estado para futuras ejecuciones (Tolerancia BFT)
        with open(token_path, 'wb') as token:
            pickle.dump(creds, token)

    try:
        youtube = build('youtube', 'v3', credentials=creds)

        print(f"[MOSKV-STUDIO] Transduciendo vídeo a YouTube: {args.title}...")

        body = {
            'snippet': {
                'title': args.title,
                'description': 'Autogenerated by BABYLON-60 C5-REAL Autonomous Engine.\n#AI #Automation #BABYLON60',
                'tags': ['AI', 'Tech', 'Automation', 'Cyberpunk', 'Agentic', 'Moskv'],
                'categoryId': '28' # Science & Technology
            },
            'status': {
                'privacyStatus': 'private', # Private por defecto. El agente o el humano lo publican cuando deseen.
                'selfDeclaredMadeForKids': False
            }
        }

        media = MediaFileUpload(video_path, chunksize=-1, resumable=True)

        request = youtube.videos().insert(
            part=','.join(body.keys()),
            body=body,
            media_body=media
        )

        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                print(f"[MOSKV-STUDIO] Carga Termodinámica... {int(status.progress() * 100)}%")

        print(f"\n[MOSKV-STUDIO] ✅ Singularidad alcanzada! Video ID: {response['id']}")

    except Exception as e:
        print(f"\n[FATAL] Colapso de onda (Fallo en la subida a YouTube): {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
