"""CORTEX Emergence Engine — JIT Autopoiesis & Spontaneous Spawning.

Listens to the DistributedEventBus. If an 'Agency Void' is detected
(e.g., an unhandled error burst, a specific task trace), it automatically
synthesizes and spawns a transient agent to address it.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import Callable
from typing import TYPE_CHECKING, Any

from cortex.agents.base import BaseAgent

if TYPE_CHECKING:
    from cortex.agents.supervisor import Supervisor
    from cortex.events.bus import DistributedEventBus

logger = logging.getLogger("cortex.agents.emergence")


class ResonanceTrigger:
    """A heuristic rule that correlates event patterns with an agent archetype."""

    def __init__(
        self,
        name: str,
        condition: Callable[[dict[str, Any]], bool],
        agent_factory: Callable[[dict[str, Any]], BaseAgent],
        exergy_cost: int = 1,
    ) -> None:
        self.name = name
        self.condition = condition
        self.agent_factory = agent_factory
        self.exergy_cost = exergy_cost


class EmergenceEngine:
    """Monitors the L1 Event Bus and conditionally spawns ephemeral agents.

    Enforces the 'Frontier.Ultrathink' directive where agents are not
    explicitly invoked but emerge based on thermodynamic necessity.
    """

    def __init__(
        self,
        supervisor: Supervisor,
        event_bus: DistributedEventBus,
        max_active_ephemeral: int = 5,
        exergy_budget: int = 100,
    ) -> None:
        self.supervisor = supervisor
        self.event_bus = event_bus
        self.max_active_ephemeral = max_active_ephemeral
        self._exergy_budget = exergy_budget
        self._triggers: list[ResonanceTrigger] = []
        self._running = False
        self._lock = asyncio.Lock()

    def add_trigger(self, trigger: ResonanceTrigger) -> None:
        """Register a new emergence heuristic."""
        self._triggers.append(trigger)
        logger.debug("EmergenceEngine: Registered trigger '%s'", trigger.name)

    async def start(self) -> None:
        """Start the background observer."""
        if self._running:
            return
        self._running = True
        self.event_bus.subscribe("*", self._on_event)
        logger.info("EmergenceEngine: Online, monitoring for Agency Voids.")

    async def stop(self) -> None:
        """Stop observing (already subscribed callbacks cannot easily be removed without bus changes,
        but we can set a flag)."""
        self._running = False
        logger.info("EmergenceEngine: Offline.")

    @property
    def remaining_exergy(self) -> int:
        return self._exergy_budget

    async def _on_event(self, event: dict[str, Any]) -> None:
        """Process incoming bus events, looking for resonance."""
        if not self._running:
            return

        # Avoid cascade spawning: Ignore events generated by ephemeral agents
        # (Assuming the system injects `_source_ephemeral: True` or similar,
        # or we check if the source agent is ephemeral. For now, simple taint check.)
        if event.get("cortex_taint_ephemeral") is True:
            return

        # Match against triggers
        for trigger in self._triggers:
            try:
                if trigger.condition(event):
                    await self._attempt_spawn(trigger, event)
            except Exception as exc:  # noqa: BLE001
                logger.error("EmergenceEngine: Error evaluating trigger '%s': %s", trigger.name, exc)

    async def _attempt_spawn(self, trigger: ResonanceTrigger, context: dict[str, Any]) -> None:
        async with self._lock:
            # Check Exergy Budget
            if self._exergy_budget < trigger.exergy_cost:
                logger.warning(
                    "EmergenceEngine: Exergy budget exhausted (%d < %d). Cannot spawn '%s'",
                    self._exergy_budget,
                    trigger.exergy_cost,
                    trigger.name,
                )
                return

            # Check capacity
            current_ephemeral = sum(
                1 for entry in self.supervisor._agents.values() if entry.ephemeral
            )
            if current_ephemeral >= self.max_active_ephemeral:
                logger.warning(
                    "EmergenceEngine: Max ephemeral capacity reached (%d). Postponing spawn.",
                    current_ephemeral,
                )
                return

            # Synthesize agent
            try:
                agent = trigger.agent_factory(context)
                self._exergy_budget -= trigger.exergy_cost

                logger.warning(
                    "EmergenceEngine: Resonance detected ['%s']. Spawning ephemeral agent '%s'. (Exergy %d -> %d)",
                    trigger.name,
                    agent.agent_id,
                    self._exergy_budget + trigger.exergy_cost,
                    self._exergy_budget,
                )

                await self.supervisor.spawn_ephemeral_agent(agent)
                
                # Emit manifestation event
                await self.event_bus.publish(
                    topic="system.emergence.spawn",
                    payload={
                        "agent_id": agent.agent_id,
                        "trigger": trigger.name,
                        "exergy_remaining": self._exergy_budget,
                        "cortex_taint_ephemeral": True,
                    },
                )

            except Exception as exc:  # noqa: BLE001
                logger.error("EmergenceEngine: Failed to spawn agent for '%s': %s", trigger.name, exc)
