"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAskResponse = instanceOfAskResponse;
exports.AskResponseFromJSON = AskResponseFromJSON;
exports.AskResponseFromJSONTyped = AskResponseFromJSONTyped;
exports.AskResponseToJSON = AskResponseToJSON;
exports.AskResponseToJSONTyped = AskResponseToJSONTyped;
const AskSource_1 = require("./AskSource");
/**
 * Check if a given object implements the AskResponse interface.
 */
function instanceOfAskResponse(value) {
    if (!('answer' in value) || value['answer'] === undefined)
        return false;
    if (!('sources' in value) || value['sources'] === undefined)
        return false;
    if (!('model' in value) || value['model'] === undefined)
        return false;
    if (!('provider' in value) || value['provider'] === undefined)
        return false;
    if (!('factsFound' in value) || value['factsFound'] === undefined)
        return false;
    return true;
}
function AskResponseFromJSON(json) {
    return AskResponseFromJSONTyped(json, false);
}
function AskResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'answer': json['answer'],
        'sources': (json['sources'].map(AskSource_1.AskSourceFromJSON)),
        'model': json['model'],
        'provider': json['provider'],
        'factsFound': json['facts_found'],
    };
}
function AskResponseToJSON(json) {
    return AskResponseToJSONTyped(json, false);
}
function AskResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'answer': value['answer'],
        'sources': (value['sources'].map(AskSource_1.AskSourceToJSON)),
        'model': value['model'],
        'provider': value['provider'],
        'facts_found': value['factsFound'],
    };
}
