"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAskRequest = instanceOfAskRequest;
exports.AskRequestFromJSON = AskRequestFromJSON;
exports.AskRequestFromJSONTyped = AskRequestFromJSONTyped;
exports.AskRequestToJSON = AskRequestToJSON;
exports.AskRequestToJSONTyped = AskRequestToJSONTyped;
/**
 * Check if a given object implements the AskRequest interface.
 */
function instanceOfAskRequest(value) {
    if (!('query' in value) || value['query'] === undefined)
        return false;
    return true;
}
function AskRequestFromJSON(json) {
    return AskRequestFromJSONTyped(json, false);
}
function AskRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'query': json['query'],
        'project': json['project'] == null ? undefined : json['project'],
        'k': json['k'] == null ? undefined : json['k'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'systemPrompt': json['system_prompt'] == null ? undefined : json['system_prompt'],
    };
}
function AskRequestToJSON(json) {
    return AskRequestToJSONTyped(json, false);
}
function AskRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'query': value['query'],
        'project': value['project'],
        'k': value['k'],
        'temperature': value['temperature'],
        'max_tokens': value['maxTokens'],
        'system_prompt': value['systemPrompt'],
    };
}
