/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AskSource } from './AskSource';
import {
    AskSourceFromJSON,
    AskSourceFromJSONTyped,
    AskSourceToJSON,
    AskSourceToJSONTyped,
} from './AskSource';

/**
 * RAG response with answer and sources.
 * @export
 * @interface AskResponse
 */
export interface AskResponse {
    /**
     * 
     * @type {string}
     * @memberof AskResponse
     */
    answer: string;
    /**
     * 
     * @type {Array<AskSource>}
     * @memberof AskResponse
     */
    sources: Array<AskSource>;
    /**
     * 
     * @type {string}
     * @memberof AskResponse
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof AskResponse
     */
    provider: string;
    /**
     * 
     * @type {number}
     * @memberof AskResponse
     */
    factsFound: number;
}

/**
 * Check if a given object implements the AskResponse interface.
 */
export function instanceOfAskResponse(value: object): value is AskResponse {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('factsFound' in value) || value['factsFound'] === undefined) return false;
    return true;
}

export function AskResponseFromJSON(json: any): AskResponse {
    return AskResponseFromJSONTyped(json, false);
}

export function AskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'sources': ((json['sources'] as Array<any>).map(AskSourceFromJSON)),
        'model': json['model'],
        'provider': json['provider'],
        'factsFound': json['facts_found'],
    };
}

export function AskResponseToJSON(json: any): AskResponse {
    return AskResponseToJSONTyped(json, false);
}

export function AskResponseToJSONTyped(value?: AskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'sources': ((value['sources'] as Array<any>).map(AskSourceToJSON)),
        'model': value['model'],
        'provider': value['provider'],
        'facts_found': value['factsFound'],
    };
}

