/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckpointId } from './CheckpointId';
import {
    CheckpointIdFromJSON,
    CheckpointIdFromJSONTyped,
    CheckpointIdToJSON,
    CheckpointIdToJSONTyped,
} from './CheckpointId';

/**
 * 
 * @export
 * @interface CheckpointResponse
 */
export interface CheckpointResponse {
    /**
     * 
     * @type {CheckpointId}
     * @memberof CheckpointResponse
     */
    checkpointId: CheckpointId | null;
    /**
     * 
     * @type {string}
     * @memberof CheckpointResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof CheckpointResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the CheckpointResponse interface.
 */
export function instanceOfCheckpointResponse(value: object): value is CheckpointResponse {
    if (!('checkpointId' in value) || value['checkpointId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CheckpointResponseFromJSON(json: any): CheckpointResponse {
    return CheckpointResponseFromJSONTyped(json, false);
}

export function CheckpointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckpointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'checkpointId': CheckpointIdFromJSON(json['checkpoint_id']),
        'message': json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CheckpointResponseToJSON(json: any): CheckpointResponse {
    return CheckpointResponseToJSONTyped(json, false);
}

export function CheckpointResponseToJSONTyped(value?: CheckpointResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkpoint_id': CheckpointIdToJSON(value['checkpointId']),
        'message': value['message'],
        'status': value['status'],
    };
}

