"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfConfidence = instanceOfConfidence;
exports.ConfidenceFromJSON = ConfidenceFromJSON;
exports.ConfidenceFromJSONTyped = ConfidenceFromJSONTyped;
exports.ConfidenceToJSON = ConfidenceToJSON;
exports.ConfidenceToJSONTyped = ConfidenceToJSONTyped;
/**
 * Check if a given object implements the Confidence interface.
 */
function instanceOfConfidence(value) {
    return true;
}
function ConfidenceFromJSON(json) {
    return ConfidenceFromJSONTyped(json, false);
}
function ConfidenceFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ConfidenceToJSON(json) {
    return ConfidenceToJSONTyped(json, false);
}
function ConfidenceToJSONTyped(value, ignoreDiscriminator = false) {
    return value;
}
