"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDimensionResultModel = instanceOfDimensionResultModel;
exports.DimensionResultModelFromJSON = DimensionResultModelFromJSON;
exports.DimensionResultModelFromJSONTyped = DimensionResultModelFromJSONTyped;
exports.DimensionResultModelToJSON = DimensionResultModelToJSON;
exports.DimensionResultModelToJSONTyped = DimensionResultModelToJSONTyped;
/**
 * Check if a given object implements the DimensionResultModel interface.
 */
function instanceOfDimensionResultModel(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('score' in value) || value['score'] === undefined)
        return false;
    if (!('weight' in value) || value['weight'] === undefined)
        return false;
    return true;
}
function DimensionResultModelFromJSON(json) {
    return DimensionResultModelFromJSONTyped(json, false);
}
function DimensionResultModelFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'score': json['score'],
        'weight': json['weight'],
        'findings': json['findings'] == null ? undefined : json['findings'],
    };
}
function DimensionResultModelToJSON(json) {
    return DimensionResultModelToJSONTyped(json, false);
}
function DimensionResultModelToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'score': value['score'],
        'weight': value['weight'],
        'findings': value['findings'],
    };
}
