/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for project memory export.
 * @export
 * @interface ExportResponse
 */
export interface ExportResponse {
    /**
     * 
     * @type {string}
     * @memberof ExportResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportResponse
     */
    project: string;
    /**
     * 
     * @type {string}
     * @memberof ExportResponse
     */
    artifact: string;
    /**
     * 
     * @type {string}
     * @memberof ExportResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ExportResponse interface.
 */
export function instanceOfExportResponse(value: object): value is ExportResponse {
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('artifact' in value) || value['artifact'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ExportResponseFromJSON(json: any): ExportResponse {
    return ExportResponseFromJSONTyped(json, false);
}

export function ExportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'project': json['project'],
        'artifact': json['artifact'],
        'message': json['message'],
    };
}

export function ExportResponseToJSON(json: any): ExportResponse {
    return ExportResponseToJSONTyped(json, false);
}

export function ExportResponseToJSONTyped(value?: ExportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'project': value['project'],
        'artifact': value['artifact'],
        'message': value['message'],
    };
}

