"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGateApprovalRequest = instanceOfGateApprovalRequest;
exports.GateApprovalRequestFromJSON = GateApprovalRequestFromJSON;
exports.GateApprovalRequestFromJSONTyped = GateApprovalRequestFromJSONTyped;
exports.GateApprovalRequestToJSON = GateApprovalRequestToJSON;
exports.GateApprovalRequestToJSONTyped = GateApprovalRequestToJSONTyped;
/**
 * Check if a given object implements the GateApprovalRequest interface.
 */
function instanceOfGateApprovalRequest(value) {
    if (!('signature' in value) || value['signature'] === undefined)
        return false;
    return true;
}
function GateApprovalRequestFromJSON(json) {
    return GateApprovalRequestFromJSONTyped(json, false);
}
function GateApprovalRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'signature': json['signature'],
        'operatorId': json['operator_id'] == null ? undefined : json['operator_id'],
    };
}
function GateApprovalRequestToJSON(json) {
    return GateApprovalRequestToJSONTyped(json, false);
}
function GateApprovalRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'signature': value['signature'],
        'operator_id': value['operatorId'],
    };
}
