/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GateActionResponse
 */
export interface GateActionResponse {
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    actionId: string;
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    level: string;
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GateActionResponse
     */
    command?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    project?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    approvedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GateActionResponse
     */
    operatorId?: string | null;
}

/**
 * Check if a given object implements the GateActionResponse interface.
 */
export function instanceOfGateActionResponse(value: object): value is GateActionResponse {
    if (!('actionId' in value) || value['actionId'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GateActionResponseFromJSON(json: any): GateActionResponse {
    return GateActionResponseFromJSONTyped(json, false);
}

export function GateActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GateActionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actionId': json['action_id'],
        'level': json['level'],
        'description': json['description'],
        'command': json['command'] == null ? undefined : json['command'],
        'project': json['project'] == null ? undefined : json['project'],
        'status': json['status'],
        'createdAt': json['created_at'],
        'approvedAt': json['approved_at'] == null ? undefined : json['approved_at'],
        'operatorId': json['operator_id'] == null ? undefined : json['operator_id'],
    };
}

export function GateActionResponseToJSON(json: any): GateActionResponse {
    return GateActionResponseToJSONTyped(json, false);
}

export function GateActionResponseToJSONTyped(value?: GateActionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action_id': value['actionId'],
        'level': value['level'],
        'description': value['description'],
        'command': value['command'],
        'project': value['project'],
        'status': value['status'],
        'created_at': value['createdAt'],
        'approved_at': value['approvedAt'],
        'operator_id': value['operatorId'],
    };
}

