"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfHeartbeatRequest = instanceOfHeartbeatRequest;
exports.HeartbeatRequestFromJSON = HeartbeatRequestFromJSON;
exports.HeartbeatRequestFromJSONTyped = HeartbeatRequestFromJSONTyped;
exports.HeartbeatRequestToJSON = HeartbeatRequestToJSON;
exports.HeartbeatRequestToJSONTyped = HeartbeatRequestToJSONTyped;
/**
 * Check if a given object implements the HeartbeatRequest interface.
 */
function instanceOfHeartbeatRequest(value) {
    if (!('project' in value) || value['project'] === undefined)
        return false;
    return true;
}
function HeartbeatRequestFromJSON(json) {
    return HeartbeatRequestFromJSONTyped(json, false);
}
function HeartbeatRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'project': json['project'],
        'entity': json['entity'] == null ? undefined : json['entity'],
        'category': json['category'] == null ? undefined : json['category'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'language': json['language'] == null ? undefined : json['language'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}
function HeartbeatRequestToJSON(json) {
    return HeartbeatRequestToJSONTyped(json, false);
}
function HeartbeatRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'project': value['project'],
        'entity': value['entity'],
        'category': value['category'],
        'branch': value['branch'],
        'language': value['language'],
        'meta': value['meta'],
    };
}
