/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobExecutionResult
 */
export interface JobExecutionResult {
    /**
     * 
     * @type {string}
     * @memberof JobExecutionResult
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof JobExecutionResult
     */
    status: string;
    /**
     * Graph-RAG context (subgraph or related entities)
     * @type {{ [key: string]: any; }}
     * @memberof JobExecutionResult
     */
    result: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof JobExecutionResult
     */
    proof: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobExecutionResult
     */
    executedAt: string;
}

/**
 * Check if a given object implements the JobExecutionResult interface.
 */
export function instanceOfJobExecutionResult(value: object): value is JobExecutionResult {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('proof' in value) || value['proof'] === undefined) return false;
    if (!('executedAt' in value) || value['executedAt'] === undefined) return false;
    return true;
}

export function JobExecutionResultFromJSON(json: any): JobExecutionResult {
    return JobExecutionResultFromJSONTyped(json, false);
}

export function JobExecutionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobExecutionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'status': json['status'],
        'result': json['result'],
        'proof': json['proof'],
        'executedAt': json['executed_at'],
    };
}

export function JobExecutionResultToJSON(json: any): JobExecutionResult {
    return JobExecutionResultToJSONTyped(json, false);
}

export function JobExecutionResultToJSONTyped(value?: JobExecutionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'status': value['status'],
        'result': value['result'],
        'proof': value['proof'],
        'executed_at': value['executedAt'],
    };
}

