/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LedgerReportResponse
 */
export interface LedgerReportResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LedgerReportResponse
     */
    valid: boolean;
    /**
     * 
     * @type {Array<{ [key: string]: any; } | null>}
     * @memberof LedgerReportResponse
     */
    violations: Array<{ [key: string]: any; } | null>;
    /**
     * 
     * @type {number}
     * @memberof LedgerReportResponse
     */
    txChecked?: number;
    /**
     * 
     * @type {number}
     * @memberof LedgerReportResponse
     */
    rootsChecked?: number;
    /**
     * 
     * @type {number}
     * @memberof LedgerReportResponse
     */
    votesChecked?: number;
    /**
     * 
     * @type {number}
     * @memberof LedgerReportResponse
     */
    voteCheckpointsChecked?: number;
}

/**
 * Check if a given object implements the LedgerReportResponse interface.
 */
export function instanceOfLedgerReportResponse(value: object): value is LedgerReportResponse {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    if (!('violations' in value) || value['violations'] === undefined) return false;
    return true;
}

export function LedgerReportResponseFromJSON(json: any): LedgerReportResponse {
    return LedgerReportResponseFromJSONTyped(json, false);
}

export function LedgerReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'],
        'violations': json['violations'],
        'txChecked': json['tx_checked'] == null ? undefined : json['tx_checked'],
        'rootsChecked': json['roots_checked'] == null ? undefined : json['roots_checked'],
        'votesChecked': json['votes_checked'] == null ? undefined : json['votes_checked'],
        'voteCheckpointsChecked': json['vote_checkpoints_checked'] == null ? undefined : json['vote_checkpoints_checked'],
    };
}

export function LedgerReportResponseToJSON(json: any): LedgerReportResponse {
    return LedgerReportResponseToJSONTyped(json, false);
}

export function LedgerReportResponseToJSONTyped(value?: LedgerReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'violations': value['violations'],
        'tx_checked': value['txChecked'],
        'roots_checked': value['rootsChecked'],
        'votes_checked': value['votesChecked'],
        'vote_checkpoints_checked': value['voteCheckpointsChecked'],
    };
}

