/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MafiaNodeProposal
 */
export interface MafiaNodeProposal {
    /**
     * 
     * @type {string}
     * @memberof MafiaNodeProposal
     */
    node: string;
}

/**
 * Check if a given object implements the MafiaNodeProposal interface.
 */
export function instanceOfMafiaNodeProposal(value: object): value is MafiaNodeProposal {
    if (!('node' in value) || value['node'] === undefined) return false;
    return true;
}

export function MafiaNodeProposalFromJSON(json: any): MafiaNodeProposal {
    return MafiaNodeProposalFromJSONTyped(json, false);
}

export function MafiaNodeProposalFromJSONTyped(json: any, ignoreDiscriminator: boolean): MafiaNodeProposal {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'],
    };
}

export function MafiaNodeProposalToJSON(json: any): MafiaNodeProposal {
    return MafiaNodeProposalToJSONTyped(json, false);
}

export function MafiaNodeProposalToJSONTyped(value?: MafiaNodeProposal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node': value['node'],
    };
}

