"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfMejoraloShipResponse = instanceOfMejoraloShipResponse;
exports.MejoraloShipResponseFromJSON = MejoraloShipResponseFromJSON;
exports.MejoraloShipResponseFromJSONTyped = MejoraloShipResponseFromJSONTyped;
exports.MejoraloShipResponseToJSON = MejoraloShipResponseToJSON;
exports.MejoraloShipResponseToJSONTyped = MejoraloShipResponseToJSONTyped;
const ShipSealModel_1 = require("./ShipSealModel");
/**
 * Check if a given object implements the MejoraloShipResponse interface.
 */
function instanceOfMejoraloShipResponse(value) {
    if (!('project' in value) || value['project'] === undefined)
        return false;
    if (!('ready' in value) || value['ready'] === undefined)
        return false;
    if (!('seals' in value) || value['seals'] === undefined)
        return false;
    if (!('passed' in value) || value['passed'] === undefined)
        return false;
    return true;
}
function MejoraloShipResponseFromJSON(json) {
    return MejoraloShipResponseFromJSONTyped(json, false);
}
function MejoraloShipResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'project': json['project'],
        'ready': json['ready'],
        'seals': (json['seals'].map(ShipSealModel_1.ShipSealModelFromJSON)),
        'passed': json['passed'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}
function MejoraloShipResponseToJSON(json) {
    return MejoraloShipResponseToJSONTyped(json, false);
}
function MejoraloShipResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'project': value['project'],
        'ready': value['ready'],
        'seals': (value['seals'].map(ShipSealModel_1.ShipSealModelToJSON)),
        'passed': value['passed'],
        'total': value['total'],
    };
}
