"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfMissionLaunchRequest = instanceOfMissionLaunchRequest;
exports.MissionLaunchRequestFromJSON = MissionLaunchRequestFromJSON;
exports.MissionLaunchRequestFromJSONTyped = MissionLaunchRequestFromJSONTyped;
exports.MissionLaunchRequestToJSON = MissionLaunchRequestToJSON;
exports.MissionLaunchRequestToJSONTyped = MissionLaunchRequestToJSONTyped;
/**
 * Check if a given object implements the MissionLaunchRequest interface.
 */
function instanceOfMissionLaunchRequest(value) {
    if (!('project' in value) || value['project'] === undefined)
        return false;
    if (!('goal' in value) || value['goal'] === undefined)
        return false;
    return true;
}
function MissionLaunchRequestFromJSON(json) {
    return MissionLaunchRequestFromJSONTyped(json, false);
}
function MissionLaunchRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'project': json['project'],
        'goal': json['goal'],
        'formation': json['formation'] == null ? undefined : json['formation'],
        'agents': json['agents'] == null ? undefined : json['agents'],
    };
}
function MissionLaunchRequestToJSON(json) {
    return MissionLaunchRequestToJSONTyped(json, false);
}
function MissionLaunchRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'project': value['project'],
        'goal': value['goal'],
        'formation': value['formation'],
        'agents': value['agents'],
    };
}
