/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to trigger The Oracle audit on a target.
 * @export
 * @interface OracleRequest
 */
export interface OracleRequest {
    /**
     * 
     * @type {string}
     * @memberof OracleRequest
     */
    targetUrl: string;
    /**
     * 
     * @type {string}
     * @memberof OracleRequest
     */
    agentType?: string;
    /**
     * 
     * @type {number}
     * @memberof OracleRequest
     */
    depth?: number;
}

/**
 * Check if a given object implements the OracleRequest interface.
 */
export function instanceOfOracleRequest(value: object): value is OracleRequest {
    if (!('targetUrl' in value) || value['targetUrl'] === undefined) return false;
    return true;
}

export function OracleRequestFromJSON(json: any): OracleRequest {
    return OracleRequestFromJSONTyped(json, false);
}

export function OracleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OracleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetUrl': json['target_url'],
        'agentType': json['agent_type'] == null ? undefined : json['agent_type'],
        'depth': json['depth'] == null ? undefined : json['depth'],
    };
}

export function OracleRequestToJSON(json: any): OracleRequest {
    return OracleRequestToJSONTyped(json, false);
}

export function OracleRequestToJSONTyped(value?: OracleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_url': value['targetUrl'],
        'agent_type': value['agentType'],
        'depth': value['depth'],
    };
}

