/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Report of the agent's memory recovery status during boot.
 * @export
 * @interface RecoveryReport
 */
export interface RecoveryReport {
    /**
     * 
     * @type {RecoveryReportStatusEnum}
     * @memberof RecoveryReport
     */
    status: RecoveryReportStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof RecoveryReport
     */
    recoveredItems: number;
    /**
     * 
     * @type {number}
     * @memberof RecoveryReport
     */
    failedItems: number;
    /**
     * 
     * @type {string}
     * @memberof RecoveryReport
     */
    lastCheckpointId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecoveryReport
     */
    warnings?: Array<string>;
}


/**
 * @export
 */
export const RecoveryReportStatusEnum = {
    Clean: 'clean',
    Recovered: 'recovered',
    Failed: 'failed'
} as const;
export type RecoveryReportStatusEnum = typeof RecoveryReportStatusEnum[keyof typeof RecoveryReportStatusEnum];


/**
 * Check if a given object implements the RecoveryReport interface.
 */
export function instanceOfRecoveryReport(value: object): value is RecoveryReport {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('recoveredItems' in value) || value['recoveredItems'] === undefined) return false;
    if (!('failedItems' in value) || value['failedItems'] === undefined) return false;
    return true;
}

export function RecoveryReportFromJSON(json: any): RecoveryReport {
    return RecoveryReportFromJSONTyped(json, false);
}

export function RecoveryReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryReport {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'recoveredItems': json['recovered_items'],
        'failedItems': json['failed_items'],
        'lastCheckpointId': json['last_checkpoint_id'] == null ? undefined : json['last_checkpoint_id'],
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
    };
}

export function RecoveryReportToJSON(json: any): RecoveryReport {
    return RecoveryReportToJSONTyped(json, false);
}

export function RecoveryReportToJSONTyped(value?: RecoveryReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'recovered_items': value['recoveredItems'],
        'failed_items': value['failedItems'],
        'last_checkpoint_id': value['lastCheckpointId'],
        'warnings': value['warnings'],
    };
}

