/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchRequest
 */
export interface SearchRequest {
    /**
     * Natural language search query
     * @type {string}
     * @memberof SearchRequest
     */
    query: string;
    /**
     * Number of results
     * @type {number}
     * @memberof SearchRequest
     */
    k?: number;
    /**
     * Filter by project
     * @type {string}
     * @memberof SearchRequest
     */
    project?: string | null;
    /**
     * Temporal filter (ISO 8601)
     * @type {string}
     * @memberof SearchRequest
     */
    asOf?: string | null;
    /**
     * Filter by fact type
     * @type {string}
     * @memberof SearchRequest
     */
    factType?: string | null;
    /**
     * Filter by tags
     * @type {Array<string>}
     * @memberof SearchRequest
     */
    tags?: Array<string> | null;
    /**
     * Enable Graph-RAG (0=off, >0=depth of context traversal)
     * @type {number}
     * @memberof SearchRequest
     */
    graphDepth?: number;
    /**
     * Include the localized context subgraph in response
     * @type {boolean}
     * @memberof SearchRequest
     */
    includeGraph?: boolean;
}

/**
 * Check if a given object implements the SearchRequest interface.
 */
export function instanceOfSearchRequest(value: object): value is SearchRequest {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function SearchRequestFromJSON(json: any): SearchRequest {
    return SearchRequestFromJSONTyped(json, false);
}

export function SearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'k': json['k'] == null ? undefined : json['k'],
        'project': json['project'] == null ? undefined : json['project'],
        'asOf': json['as_of'] == null ? undefined : json['as_of'],
        'factType': json['fact_type'] == null ? undefined : json['fact_type'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'graphDepth': json['graph_depth'] == null ? undefined : json['graph_depth'],
        'includeGraph': json['include_graph'] == null ? undefined : json['include_graph'],
    };
}

export function SearchRequestToJSON(json: any): SearchRequest {
    return SearchRequestToJSONTyped(json, false);
}

export function SearchRequestToJSONTyped(value?: SearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'k': value['k'],
        'project': value['project'],
        'as_of': value['asOf'],
        'fact_type': value['factType'],
        'tags': value['tags'],
        'graph_depth': value['graphDepth'],
        'include_graph': value['includeGraph'],
    };
}

