/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipSealModel
 */
export interface ShipSealModel {
    /**
     * 
     * @type {string}
     * @memberof ShipSealModel
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShipSealModel
     */
    passed: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShipSealModel
     */
    detail?: string;
}

/**
 * Check if a given object implements the ShipSealModel interface.
 */
export function instanceOfShipSealModel(value: object): value is ShipSealModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('passed' in value) || value['passed'] === undefined) return false;
    return true;
}

export function ShipSealModelFromJSON(json: any): ShipSealModel {
    return ShipSealModelFromJSONTyped(json, false);
}

export function ShipSealModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipSealModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'passed': json['passed'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ShipSealModelToJSON(json: any): ShipSealModel {
    return ShipSealModelToJSONTyped(json, false);
}

export function ShipSealModelToJSONTyped(value?: ShipSealModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'passed': value['passed'],
        'detail': value['detail'],
    };
}

