/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
    /**
     * 
     * @type {string}
     * @memberof StatusResponse
     */
    version: string;
    /**
     * 
     * @type {number}
     * @memberof StatusResponse
     */
    totalFacts: number;
    /**
     * 
     * @type {number}
     * @memberof StatusResponse
     */
    activeFacts: number;
    /**
     * 
     * @type {number}
     * @memberof StatusResponse
     */
    deprecated: number;
    /**
     * 
     * @type {number}
     * @memberof StatusResponse
     */
    projects: number;
    /**
     * 
     * @type {number}
     * @memberof StatusResponse
     */
    embeddings: number;
    /**
     * 
     * @type {number}
     * @memberof StatusResponse
     */
    transactions: number;
    /**
     * 
     * @type {number}
     * @memberof StatusResponse
     */
    dbSizeMb: number;
}

/**
 * Check if a given object implements the StatusResponse interface.
 */
export function instanceOfStatusResponse(value: object): value is StatusResponse {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('totalFacts' in value) || value['totalFacts'] === undefined) return false;
    if (!('activeFacts' in value) || value['activeFacts'] === undefined) return false;
    if (!('deprecated' in value) || value['deprecated'] === undefined) return false;
    if (!('projects' in value) || value['projects'] === undefined) return false;
    if (!('embeddings' in value) || value['embeddings'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('dbSizeMb' in value) || value['dbSizeMb'] === undefined) return false;
    return true;
}

export function StatusResponseFromJSON(json: any): StatusResponse {
    return StatusResponseFromJSONTyped(json, false);
}

export function StatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'totalFacts': json['total_facts'],
        'activeFacts': json['active_facts'],
        'deprecated': json['deprecated'],
        'projects': json['projects'],
        'embeddings': json['embeddings'],
        'transactions': json['transactions'],
        'dbSizeMb': json['db_size_mb'],
    };
}

export function StatusResponseToJSON(json: any): StatusResponse {
    return StatusResponseToJSONTyped(json, false);
}

export function StatusResponseToJSONTyped(value?: StatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'total_facts': value['totalFacts'],
        'active_facts': value['activeFacts'],
        'deprecated': value['deprecated'],
        'projects': value['projects'],
        'embeddings': value['embeddings'],
        'transactions': value['transactions'],
        'db_size_mb': value['dbSizeMb'],
    };
}

