"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfStoreRequest = instanceOfStoreRequest;
exports.StoreRequestFromJSON = StoreRequestFromJSON;
exports.StoreRequestFromJSONTyped = StoreRequestFromJSONTyped;
exports.StoreRequestToJSON = StoreRequestToJSON;
exports.StoreRequestToJSONTyped = StoreRequestToJSONTyped;
/**
 * Check if a given object implements the StoreRequest interface.
 */
function instanceOfStoreRequest(value) {
    if (!('project' in value) || value['project'] === undefined)
        return false;
    if (!('content' in value) || value['content'] === undefined)
        return false;
    return true;
}
function StoreRequestFromJSON(json) {
    return StoreRequestFromJSONTyped(json, false);
}
function StoreRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'project': json['project'],
        'content': json['content'],
        'factType': json['fact_type'] == null ? undefined : json['fact_type'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'source': json['source'] == null ? undefined : json['source'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}
function StoreRequestToJSON(json) {
    return StoreRequestToJSONTyped(json, false);
}
function StoreRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'project': value['project'],
        'content': value['content'],
        'fact_type': value['factType'],
        'tags': value['tags'],
        'source': value['source'],
        'confidence': value['confidence'],
        'meta': value['meta'],
    };
}
