"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSwarmStatusResponse = instanceOfSwarmStatusResponse;
exports.SwarmStatusResponseFromJSON = SwarmStatusResponseFromJSON;
exports.SwarmStatusResponseFromJSONTyped = SwarmStatusResponseFromJSONTyped;
exports.SwarmStatusResponseToJSON = SwarmStatusResponseToJSON;
exports.SwarmStatusResponseToJSONTyped = SwarmStatusResponseToJSONTyped;
/**
 * Check if a given object implements the SwarmStatusResponse interface.
 */
function instanceOfSwarmStatusResponse(value) {
    if (!('activeWorktrees' in value) || value['activeWorktrees'] === undefined)
        return false;
    if (!('totalWorktrees' in value) || value['totalWorktrees'] === undefined)
        return false;
    if (!('agentPids' in value) || value['agentPids'] === undefined)
        return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined)
        return false;
    return true;
}
function SwarmStatusResponseFromJSON(json) {
    return SwarmStatusResponseFromJSONTyped(json, false);
}
function SwarmStatusResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'activeWorktrees': json['active_worktrees'],
        'totalWorktrees': json['total_worktrees'],
        'agentPids': json['agent_pids'],
        'timestamp': json['timestamp'],
    };
}
function SwarmStatusResponseToJSON(json) {
    return SwarmStatusResponseToJSONTyped(json, false);
}
function SwarmStatusResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'active_worktrees': value['activeWorktrees'],
        'total_worktrees': value['totalWorktrees'],
        'agent_pids': value['agentPids'],
        'timestamp': value['timestamp'],
    };
}
