"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTimeSummaryResponse = instanceOfTimeSummaryResponse;
exports.TimeSummaryResponseFromJSON = TimeSummaryResponseFromJSON;
exports.TimeSummaryResponseFromJSONTyped = TimeSummaryResponseFromJSONTyped;
exports.TimeSummaryResponseToJSON = TimeSummaryResponseToJSON;
exports.TimeSummaryResponseToJSONTyped = TimeSummaryResponseToJSONTyped;
/**
 * Check if a given object implements the TimeSummaryResponse interface.
 */
function instanceOfTimeSummaryResponse(value) {
    if (!('totalSeconds' in value) || value['totalSeconds'] === undefined)
        return false;
    if (!('totalHours' in value) || value['totalHours'] === undefined)
        return false;
    if (!('byCategory' in value) || value['byCategory'] === undefined)
        return false;
    if (!('byProject' in value) || value['byProject'] === undefined)
        return false;
    if (!('entries' in value) || value['entries'] === undefined)
        return false;
    if (!('heartbeats' in value) || value['heartbeats'] === undefined)
        return false;
    if (!('topEntities' in value) || value['topEntities'] === undefined)
        return false;
    return true;
}
function TimeSummaryResponseFromJSON(json) {
    return TimeSummaryResponseFromJSONTyped(json, false);
}
function TimeSummaryResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'totalSeconds': json['total_seconds'],
        'totalHours': json['total_hours'],
        'byCategory': json['by_category'],
        'byProject': json['by_project'],
        'entries': json['entries'],
        'heartbeats': json['heartbeats'],
        'topEntities': json['top_entities'],
    };
}
function TimeSummaryResponseToJSON(json) {
    return TimeSummaryResponseToJSONTyped(json, false);
}
function TimeSummaryResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'total_seconds': value['totalSeconds'],
        'total_hours': value['totalHours'],
        'by_category': value['byCategory'],
        'by_project': value['byProject'],
        'entries': value['entries'],
        'heartbeats': value['heartbeats'],
        'top_entities': value['topEntities'],
    };
}
