"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTranslateRequest = instanceOfTranslateRequest;
exports.TranslateRequestFromJSON = TranslateRequestFromJSON;
exports.TranslateRequestFromJSONTyped = TranslateRequestFromJSONTyped;
exports.TranslateRequestToJSON = TranslateRequestToJSON;
exports.TranslateRequestToJSONTyped = TranslateRequestToJSONTyped;
/**
 * Check if a given object implements the TranslateRequest interface.
 */
function instanceOfTranslateRequest(value) {
    if (!('texts' in value) || value['texts'] === undefined)
        return false;
    if (!('targetLanguages' in value) || value['targetLanguages'] === undefined)
        return false;
    return true;
}
function TranslateRequestFromJSON(json) {
    return TranslateRequestFromJSONTyped(json, false);
}
function TranslateRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'texts': json['texts'],
        'targetLanguages': json['target_languages'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}
function TranslateRequestToJSON(json) {
    return TranslateRequestToJSONTyped(json, false);
}
function TranslateRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'texts': value['texts'],
        'target_languages': value['targetLanguages'],
        'context': value['context'],
    };
}
