/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrustProfileResponse
 */
export interface TrustProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof TrustProfileResponse
     */
    agentId: string;
    /**
     * 
     * @type {number}
     * @memberof TrustProfileResponse
     */
    trustScore: number;
    /**
     * 
     * @type {number}
     * @memberof TrustProfileResponse
     */
    successes: number;
    /**
     * 
     * @type {number}
     * @memberof TrustProfileResponse
     */
    failures: number;
    /**
     * 
     * @type {number}
     * @memberof TrustProfileResponse
     */
    taintEvents: number;
    /**
     * 
     * @type {string}
     * @memberof TrustProfileResponse
     */
    lastSuccess?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrustProfileResponse
     */
    lastIncident?: string | null;
}

/**
 * Check if a given object implements the TrustProfileResponse interface.
 */
export function instanceOfTrustProfileResponse(value: object): value is TrustProfileResponse {
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('trustScore' in value) || value['trustScore'] === undefined) return false;
    if (!('successes' in value) || value['successes'] === undefined) return false;
    if (!('failures' in value) || value['failures'] === undefined) return false;
    if (!('taintEvents' in value) || value['taintEvents'] === undefined) return false;
    return true;
}

export function TrustProfileResponseFromJSON(json: any): TrustProfileResponse {
    return TrustProfileResponseFromJSONTyped(json, false);
}

export function TrustProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrustProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'agentId': json['agent_id'],
        'trustScore': json['trust_score'],
        'successes': json['successes'],
        'failures': json['failures'],
        'taintEvents': json['taint_events'],
        'lastSuccess': json['last_success'] == null ? undefined : json['last_success'],
        'lastIncident': json['last_incident'] == null ? undefined : json['last_incident'],
    };
}

export function TrustProfileResponseToJSON(json: any): TrustProfileResponse {
    return TrustProfileResponseToJSONTyped(json, false);
}

export function TrustProfileResponseToJSONTyped(value?: TrustProfileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_id': value['agentId'],
        'trust_score': value['trustScore'],
        'successes': value['successes'],
        'failures': value['failures'],
        'taint_events': value['taintEvents'],
        'last_success': value['lastSuccess'],
        'last_incident': value['lastIncident'],
    };
}

