/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoteV2Request
 */
export interface VoteV2Request {
    /**
     * UUID of the registered agent
     * @type {string}
     * @memberof VoteV2Request
     */
    agentId: string;
    /**
     * 1 to verify, -1 to dispute, 0 to remove
     * @type {number}
     * @memberof VoteV2Request
     */
    vote: number;
    /**
     * 
     * @type {string}
     * @memberof VoteV2Request
     */
    reason?: string | null;
    /**
     * Optional cryptographic signature
     * @type {string}
     * @memberof VoteV2Request
     */
    signature?: string | null;
}

/**
 * Check if a given object implements the VoteV2Request interface.
 */
export function instanceOfVoteV2Request(value: object): value is VoteV2Request {
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('vote' in value) || value['vote'] === undefined) return false;
    return true;
}

export function VoteV2RequestFromJSON(json: any): VoteV2Request {
    return VoteV2RequestFromJSONTyped(json, false);
}

export function VoteV2RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoteV2Request {
    if (json == null) {
        return json;
    }
    return {
        
        'agentId': json['agent_id'],
        'vote': json['vote'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'signature': json['signature'] == null ? undefined : json['signature'],
    };
}

export function VoteV2RequestToJSON(json: any): VoteV2Request {
    return VoteV2RequestToJSONTyped(json, false);
}

export function VoteV2RequestToJSONTyped(value?: VoteV2Request | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_id': value['agentId'],
        'vote': value['vote'],
        'reason': value['reason'],
        'signature': value['signature'],
    };
}

