/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorktreeResponse
 */
export interface WorktreeResponse {
    /**
     * 
     * @type {string}
     * @memberof WorktreeResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorktreeResponse
     */
    branchName: string;
    /**
     * 
     * @type {string}
     * @memberof WorktreeResponse
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof WorktreeResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof WorktreeResponse
     */
    createdAt: string;
}

/**
 * Check if a given object implements the WorktreeResponse interface.
 */
export function instanceOfWorktreeResponse(value: object): value is WorktreeResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('branchName' in value) || value['branchName'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function WorktreeResponseFromJSON(json: any): WorktreeResponse {
    return WorktreeResponseFromJSONTyped(json, false);
}

export function WorktreeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorktreeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'branchName': json['branch_name'],
        'path': json['path'],
        'status': json['status'],
        'createdAt': json['created_at'],
    };
}

export function WorktreeResponseToJSON(json: any): WorktreeResponse {
    return WorktreeResponseToJSONTyped(json, false);
}

export function WorktreeResponseToJSONTyped(value?: WorktreeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'branch_name': value['branchName'],
        'path': value['path'],
        'status': value['status'],
        'created_at': value['createdAt'],
    };
}

