/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentRegisterRequest {
    #[serde(rename = "name")]
    pub name: String,
    /// ai, human, oracle, system
    #[serde(rename = "agent_type", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<String>,
    /// Optional Ed25519 public key
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
}

impl AgentRegisterRequest {
    pub fn new(name: String) -> AgentRegisterRequest {
        AgentRegisterRequest {
            name,
            agent_type: None,
            public_key: None,
        }
    }
}

