/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AskSource : A source fact that contributed to the answer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AskSource {
    #[serde(rename = "fact_id")]
    pub fact_id: i32,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "score")]
    pub score: f64,
    #[serde(rename = "project")]
    pub project: String,
}

impl AskSource {
    /// A source fact that contributed to the answer.
    pub fn new(fact_id: i32, content: String, score: f64, project: String) -> AskSource {
        AskSource {
            fact_id,
            content,
            score,
            project,
        }
    }
}

