/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CategoriesResponse : Response for the categories endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoriesResponse {
    #[serde(rename = "categories")]
    pub categories: std::collections::HashMap<String, i32>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "lang")]
    pub lang: String,
}

impl CategoriesResponse {
    /// Response for the categories endpoint.
    pub fn new(categories: std::collections::HashMap<String, i32>, total: i32, lang: String) -> CategoriesResponse {
        CategoriesResponse {
            categories,
            total,
            lang,
        }
    }
}

