/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobRequest {
    #[serde(rename = "task_type")]
    pub task_type: String,
    #[serde(rename = "payload")]
    pub payload: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "sla")]
    pub sla: Box<models::JobSla>,
}

impl JobRequest {
    pub fn new(task_type: String, payload: std::collections::HashMap<String, serde_json::Value>, sla: models::JobSla) -> JobRequest {
        JobRequest {
            task_type,
            payload,
            sla: Box::new(sla),
        }
    }
}

