/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobQuote {
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "estimated_cost_credits")]
    pub estimated_cost_credits: f64,
    #[serde(rename = "estimated_time_ms")]
    pub estimated_time_ms: i32,
}

impl JobQuote {
    pub fn new(job_id: String, estimated_cost_credits: f64, estimated_time_ms: i32) -> JobQuote {
        JobQuote {
            job_id,
            estimated_cost_credits,
            estimated_time_ms,
        }
    }
}

