/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MejoraloShipResponse {
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "ready")]
    pub ready: bool,
    #[serde(rename = "seals")]
    pub seals: Vec<models::ShipSealModel>,
    #[serde(rename = "passed")]
    pub passed: i32,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl MejoraloShipResponse {
    pub fn new(project: String, ready: bool, seals: Vec<models::ShipSealModel>, passed: i32) -> MejoraloShipResponse {
        MejoraloShipResponse {
            project,
            ready,
            seals,
            passed,
            total: None,
        }
    }
}

