/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MejoraloSessionRequest {
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "score_before")]
    pub score_before: i32,
    #[serde(rename = "score_after")]
    pub score_after: i32,
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<String>>,
}

impl MejoraloSessionRequest {
    pub fn new(project: String, score_before: i32, score_after: i32) -> MejoraloSessionRequest {
        MejoraloSessionRequest {
            project,
            score_before,
            score_after,
            actions: None,
        }
    }
}

