/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OracleRequest : Request to trigger The Oracle audit on a target.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OracleRequest {
    #[serde(rename = "target_url")]
    pub target_url: String,
    #[serde(rename = "agent_type", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<String>,
    #[serde(rename = "depth", skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
}

impl OracleRequest {
    /// Request to trigger The Oracle audit on a target.
    pub fn new(target_url: String) -> OracleRequest {
        OracleRequest {
            target_url,
            agent_type: None,
            depth: None,
        }
    }
}

