/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PsychohistoryRequest {
    /// The catastrophic scenario to simulate
    #[serde(rename = "scenario_name")]
    pub scenario_name: String,
    /// Number of years to simulate into the future
    #[serde(rename = "simulated_years", skip_serializing_if = "Option::is_none")]
    pub simulated_years: Option<i32>,
    /// Project namespace to save the crystal
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// Maximum concurrency for LLM calls
    #[serde(rename = "max_concurrency", skip_serializing_if = "Option::is_none")]
    pub max_concurrency: Option<i32>,
}

impl PsychohistoryRequest {
    pub fn new(scenario_name: String) -> PsychohistoryRequest {
        PsychohistoryRequest {
            scenario_name,
            simulated_years: None,
            project: None,
            max_concurrency: None,
        }
    }
}

