/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecoveryReport : Report of the agent's memory recovery status during boot.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecoveryReport {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "recovered_items")]
    pub recovered_items: i32,
    #[serde(rename = "failed_items")]
    pub failed_items: i32,
    #[serde(rename = "last_checkpoint_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_checkpoint_id: Option<Option<String>>,
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<String>>,
}

impl RecoveryReport {
    /// Report of the agent's memory recovery status during boot.
    pub fn new(status: Status, recovered_items: i32, failed_items: i32) -> RecoveryReport {
        RecoveryReport {
            status,
            recovered_items,
            failed_items,
            last_checkpoint_id: None,
            warnings: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "clean")]
    Clean,
    #[serde(rename = "recovered")]
    Recovered,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Clean
    }
}

