/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShipSealModel {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "passed")]
    pub passed: bool,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

impl ShipSealModel {
    pub fn new(name: String, passed: bool) -> ShipSealModel {
        ShipSealModel {
            name,
            passed,
            detail: None,
        }
    }
}

