/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignupResponse : Signup result with API credentials.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignupResponse {
    #[serde(rename = "api_key")]
    pub api_key: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "calls_limit")]
    pub calls_limit: i32,
    #[serde(rename = "quickstart_url")]
    pub quickstart_url: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl SignupResponse {
    /// Signup result with API credentials.
    pub fn new(api_key: String, tenant_id: String, plan: String, calls_limit: i32, quickstart_url: String, message: String) -> SignupResponse {
        SignupResponse {
            api_key,
            tenant_id,
            plan,
            calls_limit,
            quickstart_url,
            message,
        }
    }
}

