/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwarmStatusResponse {
    #[serde(rename = "active_worktrees")]
    pub active_worktrees: i32,
    #[serde(rename = "total_worktrees")]
    pub total_worktrees: i32,
    #[serde(rename = "agent_pids")]
    pub agent_pids: Vec<i32>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl SwarmStatusResponse {
    pub fn new(active_worktrees: i32, total_worktrees: i32, agent_pids: Vec<i32>, timestamp: String) -> SwarmStatusResponse {
        SwarmStatusResponse {
            active_worktrees,
            total_worktrees,
            agent_pids,
            timestamp,
        }
    }
}

