/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TelemetryIngestRequest {
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "agent_id")]
    pub agent_id: String,
    #[serde(rename = "payload")]
    pub payload: Box<models::TelemetryPayload>,
    #[serde(rename = "logos_signature", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logos_signature: Option<Option<String>>,
}

impl TelemetryIngestRequest {
    pub fn new(timestamp: i32, agent_id: String, payload: models::TelemetryPayload) -> TelemetryIngestRequest {
        TelemetryIngestRequest {
            timestamp,
            agent_id,
            payload: Box::new(payload),
            logos_signature: None,
        }
    }
}

