/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeSummaryResponse {
    #[serde(rename = "total_seconds")]
    pub total_seconds: i32,
    #[serde(rename = "total_hours")]
    pub total_hours: f64,
    #[serde(rename = "by_category")]
    pub by_category: std::collections::HashMap<String, i32>,
    #[serde(rename = "by_project")]
    pub by_project: std::collections::HashMap<String, i32>,
    #[serde(rename = "entries")]
    pub entries: i32,
    #[serde(rename = "heartbeats")]
    pub heartbeats: i32,
    #[serde(rename = "top_entities")]
    pub top_entities: Vec<Vec<serde_json::Value>>,
}

impl TimeSummaryResponse {
    pub fn new(total_seconds: i32, total_hours: f64, by_category: std::collections::HashMap<String, i32>, by_project: std::collections::HashMap<String, i32>, entries: i32, heartbeats: i32, top_entities: Vec<Vec<serde_json::Value>>) -> TimeSummaryResponse {
        TimeSummaryResponse {
            total_seconds,
            total_hours,
            by_category,
            by_project,
            entries,
            heartbeats,
            top_entities,
        }
    }
}

