/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TipResponse : Serialized tip for API responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TipResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "lang")]
    pub lang: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "project", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project: Option<Option<String>>,
    #[serde(rename = "relevance", skip_serializing_if = "Option::is_none")]
    pub relevance: Option<f64>,
    #[serde(rename = "formatted", skip_serializing_if = "Option::is_none")]
    pub formatted: Option<String>,
}

impl TipResponse {
    /// Serialized tip for API responses.
    pub fn new(id: String, content: String, category: String, lang: String, source: String) -> TipResponse {
        TipResponse {
            id,
            content,
            category,
            lang,
            source,
            project: None,
            relevance: None,
            formatted: None,
        }
    }
}

