/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranslateRequest {
    /// Dictionary of key-value pairs to translate. Max 100 items.
    #[serde(rename = "texts")]
    pub texts: std::collections::HashMap<String, String>,
    /// List of target language codes (e.g., ['es', 'fr', 'zh']).
    #[serde(rename = "target_languages")]
    pub target_languages: Vec<String>,
    /// Optional context about the application or tone.
    #[serde(rename = "context", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub context: Option<Option<String>>,
}

impl TranslateRequest {
    pub fn new(texts: std::collections::HashMap<String, String>, target_languages: Vec<String>) -> TranslateRequest {
        TranslateRequest {
            texts,
            target_languages,
            context: None,
        }
    }
}

