/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrustProfileResponse {
    #[serde(rename = "agent_id")]
    pub agent_id: String,
    #[serde(rename = "trust_score")]
    pub trust_score: f64,
    #[serde(rename = "successes")]
    pub successes: i32,
    #[serde(rename = "failures")]
    pub failures: i32,
    #[serde(rename = "taint_events")]
    pub taint_events: i32,
    #[serde(rename = "last_success", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_success: Option<Option<String>>,
    #[serde(rename = "last_incident", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_incident: Option<Option<String>>,
}

impl TrustProfileResponse {
    pub fn new(agent_id: String, trust_score: f64, successes: i32, failures: i32, taint_events: i32) -> TrustProfileResponse {
        TrustProfileResponse {
            agent_id,
            trust_score,
            successes,
            failures,
            taint_events,
            last_success: None,
            last_incident: None,
        }
    }
}

