/*
 * CORTEX - Sovereign Memory API
 *
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationError {
    #[serde(rename = "loc")]
    pub loc: Vec<models::LocationInner>,
    #[serde(rename = "msg")]
    pub msg: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "input", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub input: Option<Option<serde_json::Value>>,
    #[serde(rename = "ctx", skip_serializing_if = "Option::is_none")]
    pub ctx: Option<serde_json::Value>,
}

impl ValidationError {
    pub fn new(loc: Vec<models::LocationInner>, msg: String, r#type: String) -> ValidationError {
        ValidationError {
            loc,
            msg,
            r#type,
            input: None,
            ctx: None,
        }
    }
}

