/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AskRequest,
    AskRequestFromJSON,
    AskRequestToJSON,
} from '../models/AskRequest';
import {
    type AskResponse,
    AskResponseFromJSON,
    AskResponseToJSON,
} from '../models/AskResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type LLMStatusResponse,
    LLMStatusResponseFromJSON,
    LLMStatusResponseToJSON,
} from '../models/LLMStatusResponse';

export interface AskCortexV1AskPostRequest {
    askRequest: AskRequest;
    authorization?: string | null;
}

export interface AskStreamV1AskStreamPostRequest {
    askRequest: AskRequest;
    authorization?: string | null;
}

export interface LlmStatusV1LlmStatusGetRequest {
    authorization?: string | null;
}

/**
 * 
 */
export class AskApi extends runtime.BaseAPI {

    /**
     * Creates request options for askCortexV1AskPost without sending the request
     */
    async askCortexV1AskPostRequestOpts(requestParameters: AskCortexV1AskPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['askRequest'] == null) {
            throw new runtime.RequiredError(
                'askRequest',
                'Required parameter "askRequest" was null or undefined when calling askCortexV1AskPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/ask`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AskRequestToJSON(requestParameters['askRequest']),
        };
    }

    /**
     * RAG endpoint: search → synthesize → answer.  Searches CORTEX memory for relevant facts, then uses the configured LLM to synthesize an answer grounded in those facts.  Returns 503 if no LLM provider is configured.
     * Ask Cortex
     */
    async askCortexV1AskPostRaw(requestParameters: AskCortexV1AskPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AskResponse>> {
        const requestOptions = await this.askCortexV1AskPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AskResponseFromJSON(jsonValue));
    }

    /**
     * RAG endpoint: search → synthesize → answer.  Searches CORTEX memory for relevant facts, then uses the configured LLM to synthesize an answer grounded in those facts.  Returns 503 if no LLM provider is configured.
     * Ask Cortex
     */
    async askCortexV1AskPost(requestParameters: AskCortexV1AskPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AskResponse> {
        const response = await this.askCortexV1AskPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for askStreamV1AskStreamPost without sending the request
     */
    async askStreamV1AskStreamPostRequestOpts(requestParameters: AskStreamV1AskStreamPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['askRequest'] == null) {
            throw new runtime.RequiredError(
                'askRequest',
                'Required parameter "askRequest" was null or undefined when calling askStreamV1AskStreamPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/ask/stream`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AskRequestToJSON(requestParameters['askRequest']),
        };
    }

    /**
     * Streaming RAG endpoint: search → synthesize → stream answer.  Yields SSE \'data: \' events containing text chunks.
     * Ask Stream
     */
    async askStreamV1AskStreamPostRaw(requestParameters: AskStreamV1AskStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.askStreamV1AskStreamPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Streaming RAG endpoint: search → synthesize → stream answer.  Yields SSE \'data: \' events containing text chunks.
     * Ask Stream
     */
    async askStreamV1AskStreamPost(requestParameters: AskStreamV1AskStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.askStreamV1AskStreamPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for llmStatusV1LlmStatusGet without sending the request
     */
    async llmStatusV1LlmStatusGetRequestOpts(requestParameters: LlmStatusV1LlmStatusGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llm/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check LLM provider status and list supported providers. [STATUS]
     * Llm Status
     */
    async llmStatusV1LlmStatusGetRaw(requestParameters: LlmStatusV1LlmStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LLMStatusResponse>> {
        const requestOptions = await this.llmStatusV1LlmStatusGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LLMStatusResponseFromJSON(jsonValue));
    }

    /**
     * Check LLM provider status and list supported providers. [STATUS]
     * Llm Status
     */
    async llmStatusV1LlmStatusGet(requestParameters: LlmStatusV1LlmStatusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LLMStatusResponse> {
        const response = await this.llmStatusV1LlmStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
