/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface StreamEventsV1EventsStreamGetRequest {
    types?: string | null;
    authorization?: string | null;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for streamEventsV1EventsStreamGet without sending the request
     */
    async streamEventsV1EventsStreamGetRequestOpts(requestParameters: StreamEventsV1EventsStreamGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/events/stream`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subscribe to CORTEX coordination events via SSE.
     * Stream Events
     */
    async streamEventsV1EventsStreamGetRaw(requestParameters: StreamEventsV1EventsStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.streamEventsV1EventsStreamGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Subscribe to CORTEX coordination events via SSE.
     * Stream Events
     */
    async streamEventsV1EventsStreamGet(requestParameters: StreamEventsV1EventsStreamGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.streamEventsV1EventsStreamGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for streamEventsV1PublicEventsStreamGet without sending the request
     */
    async streamEventsV1PublicEventsStreamGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/public/events/stream`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Server-Sent Events endpoint for real-time CORTEX telemetry.
     * Stream Events
     */
    async streamEventsV1PublicEventsStreamGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.streamEventsV1PublicEventsStreamGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Server-Sent Events endpoint for real-time CORTEX telemetry.
     * Stream Events
     */
    async streamEventsV1PublicEventsStreamGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.streamEventsV1PublicEventsStreamGetRaw(initOverrides);
        return await response.value();
    }

}
