"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.GovernanceApi = void 0;
const runtime = __importStar(require("../runtime"));
const ApiKeyListItem_1 = require("../models/ApiKeyListItem");
const ApiKeyResponse_1 = require("../models/ApiKeyResponse");
const DeepHealthResponse_1 = require("../models/DeepHealthResponse");
const ExportResponse_1 = require("../models/ExportResponse");
const StatusResponse_1 = require("../models/StatusResponse");
/**
 *
 */
class GovernanceApi extends runtime.BaseAPI {
    /**
     * Creates request options for createApiKeyV1AdminKeysPost without sending the request
     */
    async createApiKeyV1AdminKeysPostRequestOpts(requestParameters) {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError('name', 'Required parameter "name" was null or undefined when calling createApiKeyV1AdminKeysPost().');
        }
        const queryParameters = {};
        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }
        if (requestParameters['tenantId'] != null) {
            queryParameters['tenant_id'] = requestParameters['tenantId'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/admin/keys`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Sovereign Key Provisioning.  First key is self-provisioned (bootstrap). Subsequent keys require \'admin\' permission.
     * Create Api Key
     */
    async createApiKeyV1AdminKeysPostRaw(requestParameters, initOverrides) {
        const requestOptions = await this.createApiKeyV1AdminKeysPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, ApiKeyResponse_1.ApiKeyResponseFromJSON)(jsonValue));
    }
    /**
     * Sovereign Key Provisioning.  First key is self-provisioned (bootstrap). Subsequent keys require \'admin\' permission.
     * Create Api Key
     */
    async createApiKeyV1AdminKeysPost(requestParameters, initOverrides) {
        const response = await this.createApiKeyV1AdminKeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for deepHealthCheckV1HealthDeepGet without sending the request
     */
    async deepHealthCheckV1HealthDeepGetRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/health/deep`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Deep Health Check - probes all CORTEX subsystems.  Returns 200 if all checks pass, 503 if any subsystem is degraded. Designed for Kubernetes liveness/readiness probes.
     * Deep Health Check
     */
    async deepHealthCheckV1HealthDeepGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.deepHealthCheckV1HealthDeepGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, DeepHealthResponse_1.DeepHealthResponseFromJSON)(jsonValue));
    }
    /**
     * Deep Health Check - probes all CORTEX subsystems.  Returns 200 if all checks pass, 503 if any subsystem is degraded. Designed for Kubernetes liveness/readiness probes.
     * Deep Health Check
     */
    async deepHealthCheckV1HealthDeepGet(requestParameters = {}, initOverrides) {
        const response = await this.deepHealthCheckV1HealthDeepGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for executeCredibilityStrikeV1AdminCredibilityStrikePost without sending the request
     */
    async executeCredibilityStrikeV1AdminCredibilityStrikePostRequestOpts(requestParameters) {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError('project', 'Required parameter "project" was null or undefined when calling executeCredibilityStrikeV1AdminCredibilityStrikePost().');
        }
        const queryParameters = {};
        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }
        if (requestParameters['ultrathink'] != null) {
            queryParameters['ultrathink'] = requestParameters['ultrathink'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/admin/credibility-strike`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Execute a JIT credibility strike for a project.  Computes exergy, constructs Merkle roots, signs the root, performs replay validation, and takes database snapshots.
     * Execute Credibility Strike
     */
    async executeCredibilityStrikeV1AdminCredibilityStrikePostRaw(requestParameters, initOverrides) {
        const requestOptions = await this.executeCredibilityStrikeV1AdminCredibilityStrikePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response);
    }
    /**
     * Execute a JIT credibility strike for a project.  Computes exergy, constructs Merkle roots, signs the root, performs replay validation, and takes database snapshots.
     * Execute Credibility Strike
     */
    async executeCredibilityStrikeV1AdminCredibilityStrikePost(requestParameters, initOverrides) {
        const response = await this.executeCredibilityStrikeV1AdminCredibilityStrikePostRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for exportProjectV1ProjectsProjectExportGet without sending the request
     */
    async exportProjectV1ProjectsProjectExportGetRequestOpts(requestParameters) {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError('project', 'Required parameter "project" was null or undefined when calling exportProjectV1ProjectsProjectExportGet().');
        }
        const queryParameters = {};
        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }
        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/projects/{project}/export`;
        urlPath = urlPath.replace('{project}', encodeURIComponent(String(requestParameters['project'])));
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Sovereign Export - dumps project memory to a secure JSON artifact.  Enforces path incarceration to prevent directory traversal.
     * Export Project
     */
    async exportProjectV1ProjectsProjectExportGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.exportProjectV1ProjectsProjectExportGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, ExportResponse_1.ExportResponseFromJSON)(jsonValue));
    }
    /**
     * Sovereign Export - dumps project memory to a secure JSON artifact.  Enforces path incarceration to prevent directory traversal.
     * Export Project
     */
    async exportProjectV1ProjectsProjectExportGet(requestParameters, initOverrides) {
        const response = await this.exportProjectV1ProjectsProjectExportGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for generateHandoffContextV1HandoffPost without sending the request
     */
    async generateHandoffContextV1HandoffPostRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/handoff`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Manifest a session handoff artifact with hot context and recent episodes.  Used for transferring agentic state between platforms (macOS -> Web).
     * Generate Handoff Context
     */
    async generateHandoffContextV1HandoffPostRaw(requestParameters, initOverrides) {
        const requestOptions = await this.generateHandoffContextV1HandoffPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response);
    }
    /**
     * Manifest a session handoff artifact with hot context and recent episodes.  Used for transferring agentic state between platforms (macOS -> Web).
     * Generate Handoff Context
     */
    async generateHandoffContextV1HandoffPost(requestParameters = {}, initOverrides) {
        const response = await this.generateHandoffContextV1HandoffPostRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for getSystemStatusV1StatusGet without sending the request
     */
    async getSystemStatusV1StatusGetRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/status`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Expose engine diagnostics and memory health metrics.
     * Get System Status
     */
    async getSystemStatusV1StatusGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.getSystemStatusV1StatusGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, StatusResponse_1.StatusResponseFromJSON)(jsonValue));
    }
    /**
     * Expose engine diagnostics and memory health metrics.
     * Get System Status
     */
    async getSystemStatusV1StatusGet(requestParameters = {}, initOverrides) {
        const response = await this.getSystemStatusV1StatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for listApiKeysV1AdminKeysGet without sending the request
     */
    async listApiKeysV1AdminKeysGetRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/admin/keys`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Expose non-sensitive metadata for all provisioned keys.
     * List Api Keys
     */
    async listApiKeysV1AdminKeysGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.listApiKeysV1AdminKeysGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiKeyListItem_1.ApiKeyListItemFromJSON));
    }
    /**
     * Expose non-sensitive metadata for all provisioned keys.
     * List Api Keys
     */
    async listApiKeysV1AdminKeysGet(requestParameters = {}, initOverrides) {
        const response = await this.listApiKeysV1AdminKeysGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.GovernanceApi = GovernanceApi;
