"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.MissionsApi = void 0;
const runtime = __importStar(require("../runtime"));
const MissionLaunchRequest_1 = require("../models/MissionLaunchRequest");
const MissionResponse_1 = require("../models/MissionResponse");
/**
 *
 */
class MissionsApi extends runtime.BaseAPI {
    /**
     * Creates request options for launchMissionV1MissionsLaunchPost without sending the request
     */
    async launchMissionV1MissionsLaunchPostRequestOpts(requestParameters) {
        if (requestParameters['missionLaunchRequest'] == null) {
            throw new runtime.RequiredError('missionLaunchRequest', 'Required parameter "missionLaunchRequest" was null or undefined when calling launchMissionV1MissionsLaunchPost().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/missions/launch`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, MissionLaunchRequest_1.MissionLaunchRequestToJSON)(requestParameters['missionLaunchRequest']),
        };
    }
    /**
     * Launch a new swarm mission through the CORTEX Launchpad.
     * Launch Mission
     */
    async launchMissionV1MissionsLaunchPostRaw(requestParameters, initOverrides) {
        const requestOptions = await this.launchMissionV1MissionsLaunchPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, MissionResponse_1.MissionResponseFromJSON)(jsonValue));
    }
    /**
     * Launch a new swarm mission through the CORTEX Launchpad.
     * Launch Mission
     */
    async launchMissionV1MissionsLaunchPost(requestParameters, initOverrides) {
        const response = await this.launchMissionV1MissionsLaunchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for listMissionsV1MissionsGet without sending the request
     */
    async listMissionsV1MissionsGetRequestOpts(requestParameters) {
        const queryParameters = {};
        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/missions/`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * List recent mission intents and reports from the ledger.
     * List Missions
     */
    async listMissionsV1MissionsGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.listMissionsV1MissionsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response);
    }
    /**
     * List recent mission intents and reports from the ledger.
     * List Missions
     */
    async listMissionsV1MissionsGet(requestParameters = {}, initOverrides) {
        const response = await this.listMissionsV1MissionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.MissionsApi = MissionsApi;
