/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type MafiaNodeProposal,
    MafiaNodeProposalFromJSON,
    MafiaNodeProposalToJSON,
} from '../models/MafiaNodeProposal';
import {
    type TelemetryIngestRequest,
    TelemetryIngestRequestFromJSON,
    TelemetryIngestRequestToJSON,
} from '../models/TelemetryIngestRequest';

export interface AddMafiaNodeApiV1TelemetryNodesPostRequest {
    mafiaNodeProposal: MafiaNodeProposal;
}

export interface AddMafiaNodeTelemetryNodesPostRequest {
    mafiaNodeProposal: MafiaNodeProposal;
}

export interface AddMafiaNodeV1TelemetryNodesPostRequest {
    mafiaNodeProposal: MafiaNodeProposal;
}

export interface IngestTelemetryApiV1TelemetryIngestPostRequest {
    telemetryIngestRequest: TelemetryIngestRequest;
}

export interface IngestTelemetryTelemetryIngestPostRequest {
    telemetryIngestRequest: TelemetryIngestRequest;
}

export interface IngestTelemetryV1TelemetryIngestPostRequest {
    telemetryIngestRequest: TelemetryIngestRequest;
}

/**
 * 
 */
export class TelemetryApi extends runtime.BaseAPI {

    /**
     * Creates request options for addMafiaNodeApiV1TelemetryNodesPost without sending the request
     */
    async addMafiaNodeApiV1TelemetryNodesPostRequestOpts(requestParameters: AddMafiaNodeApiV1TelemetryNodesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mafiaNodeProposal'] == null) {
            throw new runtime.RequiredError(
                'mafiaNodeProposal',
                'Required parameter "mafiaNodeProposal" was null or undefined when calling addMafiaNodeApiV1TelemetryNodesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/telemetry/nodes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MafiaNodeProposalToJSON(requestParameters['mafiaNodeProposal']),
        };
    }

    /**
     * Add a new mafia node fact and push to all active extensions.
     * Add Mafia Node
     */
    async addMafiaNodeApiV1TelemetryNodesPostRaw(requestParameters: AddMafiaNodeApiV1TelemetryNodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.addMafiaNodeApiV1TelemetryNodesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add a new mafia node fact and push to all active extensions.
     * Add Mafia Node
     */
    async addMafiaNodeApiV1TelemetryNodesPost(requestParameters: AddMafiaNodeApiV1TelemetryNodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addMafiaNodeApiV1TelemetryNodesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addMafiaNodeTelemetryNodesPost without sending the request
     */
    async addMafiaNodeTelemetryNodesPostRequestOpts(requestParameters: AddMafiaNodeTelemetryNodesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mafiaNodeProposal'] == null) {
            throw new runtime.RequiredError(
                'mafiaNodeProposal',
                'Required parameter "mafiaNodeProposal" was null or undefined when calling addMafiaNodeTelemetryNodesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/telemetry/nodes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MafiaNodeProposalToJSON(requestParameters['mafiaNodeProposal']),
        };
    }

    /**
     * Add a new mafia node fact and push to all active extensions.
     * Add Mafia Node
     */
    async addMafiaNodeTelemetryNodesPostRaw(requestParameters: AddMafiaNodeTelemetryNodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.addMafiaNodeTelemetryNodesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add a new mafia node fact and push to all active extensions.
     * Add Mafia Node
     */
    async addMafiaNodeTelemetryNodesPost(requestParameters: AddMafiaNodeTelemetryNodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addMafiaNodeTelemetryNodesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addMafiaNodeV1TelemetryNodesPost without sending the request
     */
    async addMafiaNodeV1TelemetryNodesPostRequestOpts(requestParameters: AddMafiaNodeV1TelemetryNodesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mafiaNodeProposal'] == null) {
            throw new runtime.RequiredError(
                'mafiaNodeProposal',
                'Required parameter "mafiaNodeProposal" was null or undefined when calling addMafiaNodeV1TelemetryNodesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/telemetry/nodes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MafiaNodeProposalToJSON(requestParameters['mafiaNodeProposal']),
        };
    }

    /**
     * Add a new mafia node fact and push to all active extensions.
     * Add Mafia Node
     */
    async addMafiaNodeV1TelemetryNodesPostRaw(requestParameters: AddMafiaNodeV1TelemetryNodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.addMafiaNodeV1TelemetryNodesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add a new mafia node fact and push to all active extensions.
     * Add Mafia Node
     */
    async addMafiaNodeV1TelemetryNodesPost(requestParameters: AddMafiaNodeV1TelemetryNodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addMafiaNodeV1TelemetryNodesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMafiaNodesApiV1TelemetryNodesGet without sending the request
     */
    async getMafiaNodesApiV1TelemetryNodesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/telemetry/nodes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all active mafia nodes (base + dynamic).
     * Get Mafia Nodes
     */
    async getMafiaNodesApiV1TelemetryNodesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getMafiaNodesApiV1TelemetryNodesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Retrieve all active mafia nodes (base + dynamic).
     * Get Mafia Nodes
     */
    async getMafiaNodesApiV1TelemetryNodesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getMafiaNodesApiV1TelemetryNodesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMafiaNodesTelemetryNodesGet without sending the request
     */
    async getMafiaNodesTelemetryNodesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/telemetry/nodes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all active mafia nodes (base + dynamic).
     * Get Mafia Nodes
     */
    async getMafiaNodesTelemetryNodesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getMafiaNodesTelemetryNodesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Retrieve all active mafia nodes (base + dynamic).
     * Get Mafia Nodes
     */
    async getMafiaNodesTelemetryNodesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getMafiaNodesTelemetryNodesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMafiaNodesV1TelemetryNodesGet without sending the request
     */
    async getMafiaNodesV1TelemetryNodesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/telemetry/nodes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all active mafia nodes (base + dynamic).
     * Get Mafia Nodes
     */
    async getMafiaNodesV1TelemetryNodesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getMafiaNodesV1TelemetryNodesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Retrieve all active mafia nodes (base + dynamic).
     * Get Mafia Nodes
     */
    async getMafiaNodesV1TelemetryNodesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getMafiaNodesV1TelemetryNodesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestTelemetryApiV1TelemetryIngestPost without sending the request
     */
    async ingestTelemetryApiV1TelemetryIngestPostRequestOpts(requestParameters: IngestTelemetryApiV1TelemetryIngestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['telemetryIngestRequest'] == null) {
            throw new runtime.RequiredError(
                'telemetryIngestRequest',
                'Required parameter "telemetryIngestRequest" was null or undefined when calling ingestTelemetryApiV1TelemetryIngestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/telemetry/ingest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TelemetryIngestRequestToJSON(requestParameters['telemetryIngestRequest']),
        };
    }

    /**
     * Ingest sovereign telemetry facts (C5-REAL) from external edge sensors.
     * Ingest Telemetry
     */
    async ingestTelemetryApiV1TelemetryIngestPostRaw(requestParameters: IngestTelemetryApiV1TelemetryIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.ingestTelemetryApiV1TelemetryIngestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Ingest sovereign telemetry facts (C5-REAL) from external edge sensors.
     * Ingest Telemetry
     */
    async ingestTelemetryApiV1TelemetryIngestPost(requestParameters: IngestTelemetryApiV1TelemetryIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.ingestTelemetryApiV1TelemetryIngestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestTelemetryTelemetryIngestPost without sending the request
     */
    async ingestTelemetryTelemetryIngestPostRequestOpts(requestParameters: IngestTelemetryTelemetryIngestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['telemetryIngestRequest'] == null) {
            throw new runtime.RequiredError(
                'telemetryIngestRequest',
                'Required parameter "telemetryIngestRequest" was null or undefined when calling ingestTelemetryTelemetryIngestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/telemetry/ingest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TelemetryIngestRequestToJSON(requestParameters['telemetryIngestRequest']),
        };
    }

    /**
     * Ingest sovereign telemetry facts (C5-REAL) from external edge sensors.
     * Ingest Telemetry
     */
    async ingestTelemetryTelemetryIngestPostRaw(requestParameters: IngestTelemetryTelemetryIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.ingestTelemetryTelemetryIngestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Ingest sovereign telemetry facts (C5-REAL) from external edge sensors.
     * Ingest Telemetry
     */
    async ingestTelemetryTelemetryIngestPost(requestParameters: IngestTelemetryTelemetryIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.ingestTelemetryTelemetryIngestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestTelemetryV1TelemetryIngestPost without sending the request
     */
    async ingestTelemetryV1TelemetryIngestPostRequestOpts(requestParameters: IngestTelemetryV1TelemetryIngestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['telemetryIngestRequest'] == null) {
            throw new runtime.RequiredError(
                'telemetryIngestRequest',
                'Required parameter "telemetryIngestRequest" was null or undefined when calling ingestTelemetryV1TelemetryIngestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/telemetry/ingest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TelemetryIngestRequestToJSON(requestParameters['telemetryIngestRequest']),
        };
    }

    /**
     * Ingest sovereign telemetry facts (C5-REAL) from external edge sensors.
     * Ingest Telemetry
     */
    async ingestTelemetryV1TelemetryIngestPostRaw(requestParameters: IngestTelemetryV1TelemetryIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.ingestTelemetryV1TelemetryIngestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Ingest sovereign telemetry facts (C5-REAL) from external edge sensors.
     * Ingest Telemetry
     */
    async ingestTelemetryV1TelemetryIngestPost(requestParameters: IngestTelemetryV1TelemetryIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.ingestTelemetryV1TelemetryIngestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
