"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TipsApi = void 0;
const runtime = __importStar(require("../runtime"));
const CategoriesResponse_1 = require("../models/CategoriesResponse");
const TipsListResponse_1 = require("../models/TipsListResponse");
/**
 *
 */
class TipsApi extends runtime.BaseAPI {
    /**
     * Creates request options for getTipsByCategoryTipsCategoryCategoryGet without sending the request
     */
    async getTipsByCategoryTipsCategoryCategoryGetRequestOpts(requestParameters) {
        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError('category', 'Required parameter "category" was null or undefined when calling getTipsByCategoryTipsCategoryCategoryGet().');
        }
        const queryParameters = {};
        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/tips/category/{category}`;
        urlPath = urlPath.replace('{category}', encodeURIComponent(String(requestParameters['category'])));
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Get tips filtered by category.
     * Get Tips By Category
     */
    async getTipsByCategoryTipsCategoryCategoryGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.getTipsByCategoryTipsCategoryCategoryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, TipsListResponse_1.TipsListResponseFromJSON)(jsonValue));
    }
    /**
     * Get tips filtered by category.
     * Get Tips By Category
     */
    async getTipsByCategoryTipsCategoryCategoryGet(requestParameters, initOverrides) {
        const response = await this.getTipsByCategoryTipsCategoryCategoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for getTipsByProjectTipsProjectProjectGet without sending the request
     */
    async getTipsByProjectTipsProjectProjectGetRequestOpts(requestParameters) {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError('project', 'Required parameter "project" was null or undefined when calling getTipsByProjectTipsProjectProjectGet().');
        }
        const queryParameters = {};
        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/tips/project/{project}`;
        urlPath = urlPath.replace('{project}', encodeURIComponent(String(requestParameters['project'])));
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Get tips scoped to a specific project.
     * Get Tips By Project
     */
    async getTipsByProjectTipsProjectProjectGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.getTipsByProjectTipsProjectProjectGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, TipsListResponse_1.TipsListResponseFromJSON)(jsonValue));
    }
    /**
     * Get tips scoped to a specific project.
     * Get Tips By Project
     */
    async getTipsByProjectTipsProjectProjectGet(requestParameters, initOverrides) {
        const response = await this.getTipsByProjectTipsProjectProjectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for getTipsTipsGet without sending the request
     */
    async getTipsTipsGetRequestOpts(requestParameters) {
        const queryParameters = {};
        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }
        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/tips`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Get random contextual tips.
     * Get Tips
     */
    async getTipsTipsGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.getTipsTipsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, TipsListResponse_1.TipsListResponseFromJSON)(jsonValue));
    }
    /**
     * Get random contextual tips.
     * Get Tips
     */
    async getTipsTipsGet(requestParameters = {}, initOverrides) {
        const response = await this.getTipsTipsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for listCategoriesTipsCategoriesGet without sending the request
     */
    async listCategoriesTipsCategoriesGetRequestOpts(requestParameters) {
        const queryParameters = {};
        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/tips/categories`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * List all tip categories with counts.
     * List Categories
     */
    async listCategoriesTipsCategoriesGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.listCategoriesTipsCategoriesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, CategoriesResponse_1.CategoriesResponseFromJSON)(jsonValue));
    }
    /**
     * List all tip categories with counts.
     * List Categories
     */
    async listCategoriesTipsCategoriesGet(requestParameters = {}, initOverrides) {
        const response = await this.listCategoriesTipsCategoriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.TipsApi = TipsApi;
