"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CORTEX - Sovereign Memory API
 * Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsageApi = void 0;
const runtime = __importStar(require("../runtime"));
/**
 *
 */
class UsageApi extends runtime.BaseAPI {
    /**
     * Creates request options for getUsageBreakdownV1UsageBreakdownGet without sending the request
     */
    async getUsageBreakdownV1UsageBreakdownGetRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/usage/breakdown`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Get per-endpoint breakdown for current month.
     * Get Usage Breakdown
     */
    async getUsageBreakdownV1UsageBreakdownGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.getUsageBreakdownV1UsageBreakdownGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response);
    }
    /**
     * Get per-endpoint breakdown for current month.
     * Get Usage Breakdown
     */
    async getUsageBreakdownV1UsageBreakdownGet(requestParameters = {}, initOverrides) {
        const response = await this.getUsageBreakdownV1UsageBreakdownGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for getUsageHistoryV1UsageHistoryGet without sending the request
     */
    async getUsageHistoryV1UsageHistoryGetRequestOpts(requestParameters) {
        const queryParameters = {};
        if (requestParameters['months'] != null) {
            queryParameters['months'] = requestParameters['months'];
        }
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/usage/history`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Get usage history for the last N months.
     * Get Usage History
     */
    async getUsageHistoryV1UsageHistoryGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.getUsageHistoryV1UsageHistoryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response);
    }
    /**
     * Get usage history for the last N months.
     * Get Usage History
     */
    async getUsageHistoryV1UsageHistoryGet(requestParameters = {}, initOverrides) {
        const response = await this.getUsageHistoryV1UsageHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for getUsageV1UsageGet without sending the request
     */
    async getUsageV1UsageGetRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }
        let urlPath = `/v1/usage`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * Get current month\'s API usage for the authenticated tenant.
     * Get Usage
     */
    async getUsageV1UsageGetRaw(requestParameters, initOverrides) {
        const requestOptions = await this.getUsageV1UsageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response);
    }
    /**
     * Get current month\'s API usage for the authenticated tenant.
     * Get Usage
     */
    async getUsageV1UsageGet(requestParameters = {}, initOverrides) {
        const response = await this.getUsageV1UsageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.UsageApi = UsageApi;
