import os
import re

def main():
    yaml_path = "/Users/borjafernandezangulo/borjamoskv/Teorema-Robinson-Moskv/cortex/ontology/10000_space_taxonomy.yaml"
    output_path = "/Users/borjafernandezangulo/borjamoskv/Teorema-Robinson-Moskv/src-tauri/src/primitives_generated.rs"
    
    with open(yaml_path, 'r') as f:
        content = f.read()
    
    domains, primitives, modifiers, targets = {}, {}, {}, {}
    
    current_section = None
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if line.startswith('Domains_Context:'):
            current_section = 'domains'
            continue
        elif line.startswith('Primitives_Action:'):
            current_section = 'primitives'
            continue
        elif line.startswith('Modifiers_Constraint:'):
            current_section = 'modifiers'
            continue
        elif line.startswith('Targets_Vector:'):
            current_section = 'targets'
            continue
            
        match = re.match(r'(\d+):\s*"([^"]+)"', line)
        if match:
            idx = int(match.group(1))
            val = match.group(2)
            if current_section == 'domains':
                domains[idx] = val
            elif current_section == 'primitives':
                primitives[idx] = val
            elif current_section == 'modifiers':
                modifiers[idx] = val
            elif current_section == 'targets':
                targets[idx] = val

    assert len(domains) == 10
    assert len(primitives) == 10
    assert len(modifiers) == 10
    assert len(targets) == 10
    
    cases = []
    for d in range(10):
        for p in range(10):
            for m in range(10):
                for t in range(10):
                    code = d * 1000 + p * 100 + m * 10 + t
                    name = f"{domains[d]}-{primitives[p]}-{modifiers[m]}-{targets[t]}"
                    cases.append(f"        {code} => Some(|id| {{ println!(\"⚡ [{code:04}] {name} executed via generated retro-membrane.\"); }}),")
    
    rust_code = f"""// This file is auto-generated by generate_primitives.py. Do not edit.
use crate::kernel::PrimitiveIdentity;

pub fn get_generated_action(index: usize) -> Option<fn(&PrimitiveIdentity)> {{
    match index {{
{chr(10).join(cases)}
        _ => None,
    }}
}}
"""
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(rust_code)
    print(f"Generated {len(cases)} primitives in {output_path}")

if __name__ == "__main__":
    main()
