#!/usr/bin/env python3
import os
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent.resolve()
OUTPUT = ROOT / "C5_ABSOLUTE_ONTOLOGY.md"

IGNORE_DIRS = {".git", ".venv", "node_modules", "__pycache__", "target", ".ruff_cache", ".pytest_cache", ".cortex"}

def categorize(path: Path) -> str:
    ext = path.suffix.lower()
    name = path.name.lower()
    parent = path.parent.name.lower()
    
    if name == "status.md":
        return "Single Source of Truth (Binary State Ledger)."
    if name in ("agents.md", "ethos.md", "manifiesto_centuria.md"):
        return "System Invariants and Philosophical C5-REAL Directives."
    if ext == ".py":
        if "test" in name:
            return "Deterministic Oracle (Physical Validation of AST)."
        if "backend/routes" in str(path):
            return "IDE Fast API Socket (Network Transducer)."
        if "scripts" in str(path):
            return "Kinetic Arsenal (Physical Scripts for State Mutation)."
        return "Python Runtime Logic (Data processing & State Management)."
    if ext in (".js", ".html", ".css", ".jsx"):
        if "frontend" in str(path):
            return "Zero Context-Switching GUI (The Operating Theater)."
        if "extension" in str(path):
            return "Browser Alcove (MV3 Memory Injector)."
    if ext == ".rs":
        return "Tauri / Native execution block (High Exergy Apple Silicon Layer)."
    if ext == ".db" or ext == ".db-wal":
        return "SQLite Physical Ledger (BFT Consensus Memory or Graph)."
    if ext == ".md":
        return "Epistemic Artifact (Causal Documentation)."
    if ext in (".json", ".yaml", ".yml"):
        return "Configuration Matrix or Static Schema."
    
    return "Untyped Entropy (Pending Audit)."

def run() -> None:
    lines = [
        "# ABSOLUTE C5-REAL ONTOLOGY: BABYLON-60",
        f"> Generated by ULTRATHINK Agent at {datetime.utcnow().isoformat()}Z",
        "> **Directiva:** Cuestionar el PORQUÉ de la A a la Z.",
        ""
    ]
    
    files_mapped = 0
    
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in IGNORE_DIRS]
        
        current_dir = Path(dirpath)
        rel_dir = current_dir.relative_to(ROOT)
        if str(rel_dir) != ".":
            lines.append(f"## 📁 {rel_dir}")
            
        for f in sorted(filenames):
            if f.startswith(".fuse_hidden"): continue
            
            fpath = current_dir / f
            rel_file = fpath.relative_to(ROOT)
            causal_reason = categorize(fpath)
            lines.append(f"- **`{f}`**: {causal_reason}")
            files_mapped += 1
            
        lines.append("")
        
    lines.append(f"**Total Entidades Auditadas:** {files_mapped}")
    
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Ontology mapped to {OUTPUT} ({files_mapped} files)")

if __name__ == "__main__":
    run()
