/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// TaasAPIService TaasAPI service
type TaasAPIService service

type ApiExecuteJobV1TaasJobsJobIdExecutePostRequest struct {
	ctx context.Context
	ApiService *TaasAPIService
	jobId string
	authorization *string
}

// Bearer &lt;api-key&gt;
func (r ApiExecuteJobV1TaasJobsJobIdExecutePostRequest) Authorization(authorization string) ApiExecuteJobV1TaasJobsJobIdExecutePostRequest {
	r.authorization = &authorization
	return r
}

func (r ApiExecuteJobV1TaasJobsJobIdExecutePostRequest) Execute() (*JobExecutionResult, *http.Response, error) {
	return r.ApiService.ExecuteJobV1TaasJobsJobIdExecutePostExecute(r)
}

/*
ExecuteJobV1TaasJobsJobIdExecutePost Execute Job

Execute a previously quoted job and receive proof of execution.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param jobId
 @return ApiExecuteJobV1TaasJobsJobIdExecutePostRequest
*/
func (a *TaasAPIService) ExecuteJobV1TaasJobsJobIdExecutePost(ctx context.Context, jobId string) ApiExecuteJobV1TaasJobsJobIdExecutePostRequest {
	return ApiExecuteJobV1TaasJobsJobIdExecutePostRequest{
		ApiService: a,
		ctx: ctx,
		jobId: jobId,
	}
}

// Execute executes the request
//  @return JobExecutionResult
func (a *TaasAPIService) ExecuteJobV1TaasJobsJobIdExecutePostExecute(r ApiExecuteJobV1TaasJobsJobIdExecutePostRequest) (*JobExecutionResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *JobExecutionResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TaasAPIService.ExecuteJobV1TaasJobsJobIdExecutePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/taas/jobs/{job_id}/execute"
	localVarPath = strings.Replace(localVarPath, "{"+"job_id"+"}", url.PathEscape(parameterValueToString(r.jobId, "jobId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRequestJobQuoteV1TaasJobsQuotePostRequest struct {
	ctx context.Context
	ApiService *TaasAPIService
	jobRequest *JobRequest
	authorization *string
}

func (r ApiRequestJobQuoteV1TaasJobsQuotePostRequest) JobRequest(jobRequest JobRequest) ApiRequestJobQuoteV1TaasJobsQuotePostRequest {
	r.jobRequest = &jobRequest
	return r
}

// Bearer &lt;api-key&gt;
func (r ApiRequestJobQuoteV1TaasJobsQuotePostRequest) Authorization(authorization string) ApiRequestJobQuoteV1TaasJobsQuotePostRequest {
	r.authorization = &authorization
	return r
}

func (r ApiRequestJobQuoteV1TaasJobsQuotePostRequest) Execute() (*JobQuote, *http.Response, error) {
	return r.ApiService.RequestJobQuoteV1TaasJobsQuotePostExecute(r)
}

/*
RequestJobQuoteV1TaasJobsQuotePost Request Job Quote

Request a quote and SLA for an agent execution job.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRequestJobQuoteV1TaasJobsQuotePostRequest
*/
func (a *TaasAPIService) RequestJobQuoteV1TaasJobsQuotePost(ctx context.Context) ApiRequestJobQuoteV1TaasJobsQuotePostRequest {
	return ApiRequestJobQuoteV1TaasJobsQuotePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return JobQuote
func (a *TaasAPIService) RequestJobQuoteV1TaasJobsQuotePostExecute(r ApiRequestJobQuoteV1TaasJobsQuotePostRequest) (*JobQuote, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *JobQuote
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TaasAPIService.RequestJobQuoteV1TaasJobsQuotePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/taas/jobs/quote"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.jobRequest == nil {
		return localVarReturnValue, nil, reportError("jobRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	}
	// body params
	localVarPostBody = r.jobRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest struct {
	ctx context.Context
	ApiService *TaasAPIService
	jobId string
	proof *string
	authorization *string
}

func (r ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest) Proof(proof string) ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest {
	r.proof = &proof
	return r
}

// Bearer &lt;api-key&gt;
func (r ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest) Authorization(authorization string) ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest {
	r.authorization = &authorization
	return r
}

func (r ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.VerifyJobProofV1TaasJobsJobIdVerifyGetExecute(r)
}

/*
VerifyJobProofV1TaasJobsJobIdVerifyGet Verify Job Proof

Verify cryptographic proof of execution for a job.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param jobId
 @return ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest
*/
func (a *TaasAPIService) VerifyJobProofV1TaasJobsJobIdVerifyGet(ctx context.Context, jobId string) ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest {
	return ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest{
		ApiService: a,
		ctx: ctx,
		jobId: jobId,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *TaasAPIService) VerifyJobProofV1TaasJobsJobIdVerifyGetExecute(r ApiVerifyJobProofV1TaasJobsJobIdVerifyGetRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TaasAPIService.VerifyJobProofV1TaasJobsJobIdVerifyGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/taas/jobs/{job_id}/verify"
	localVarPath = strings.Replace(localVarPath, "{"+"job_id"+"}", url.PathEscape(parameterValueToString(r.jobId, "jobId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.proof == nil {
		return localVarReturnValue, nil, reportError("proof is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "proof", r.proof, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
