/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoreResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreResponse{}

// StoreResponse struct for StoreResponse
type StoreResponse struct {
	FactId int32 `json:"fact_id"`
	Project string `json:"project"`
	Message string `json:"message"`
}

type _StoreResponse StoreResponse

// NewStoreResponse instantiates a new StoreResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreResponse(factId int32, project string, message string) *StoreResponse {
	this := StoreResponse{}
	this.FactId = factId
	this.Project = project
	this.Message = message
	return &this
}

// NewStoreResponseWithDefaults instantiates a new StoreResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreResponseWithDefaults() *StoreResponse {
	this := StoreResponse{}
	return &this
}

// GetFactId returns the FactId field value
func (o *StoreResponse) GetFactId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FactId
}

// GetFactIdOk returns a tuple with the FactId field value
// and a boolean to check if the value has been set.
func (o *StoreResponse) GetFactIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FactId, true
}

// SetFactId sets field value
func (o *StoreResponse) SetFactId(v int32) {
	o.FactId = v
}

// GetProject returns the Project field value
func (o *StoreResponse) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *StoreResponse) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *StoreResponse) SetProject(v string) {
	o.Project = v
}

// GetMessage returns the Message field value
func (o *StoreResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *StoreResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *StoreResponse) SetMessage(v string) {
	o.Message = v
}

func (o StoreResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fact_id"] = o.FactId
	toSerialize["project"] = o.Project
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *StoreResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fact_id",
		"project",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreResponse := _StoreResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreResponse)

	if err != nil {
		return err
	}

	*o = StoreResponse(varStoreResponse)

	return err
}

type NullableStoreResponse struct {
	value *StoreResponse
	isSet bool
}

func (v NullableStoreResponse) Get() *StoreResponse {
	return v.value
}

func (v *NullableStoreResponse) Set(val *StoreResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreResponse(val *StoreResponse) *NullableStoreResponse {
	return &NullableStoreResponse{value: val, isSet: true}
}

func (v NullableStoreResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


