/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SwarmStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwarmStatusResponse{}

// SwarmStatusResponse struct for SwarmStatusResponse
type SwarmStatusResponse struct {
	ActiveWorktrees int32 `json:"active_worktrees"`
	TotalWorktrees int32 `json:"total_worktrees"`
	AgentPids []int32 `json:"agent_pids"`
	Timestamp string `json:"timestamp"`
}

type _SwarmStatusResponse SwarmStatusResponse

// NewSwarmStatusResponse instantiates a new SwarmStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwarmStatusResponse(activeWorktrees int32, totalWorktrees int32, agentPids []int32, timestamp string) *SwarmStatusResponse {
	this := SwarmStatusResponse{}
	this.ActiveWorktrees = activeWorktrees
	this.TotalWorktrees = totalWorktrees
	this.AgentPids = agentPids
	this.Timestamp = timestamp
	return &this
}

// NewSwarmStatusResponseWithDefaults instantiates a new SwarmStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwarmStatusResponseWithDefaults() *SwarmStatusResponse {
	this := SwarmStatusResponse{}
	return &this
}

// GetActiveWorktrees returns the ActiveWorktrees field value
func (o *SwarmStatusResponse) GetActiveWorktrees() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveWorktrees
}

// GetActiveWorktreesOk returns a tuple with the ActiveWorktrees field value
// and a boolean to check if the value has been set.
func (o *SwarmStatusResponse) GetActiveWorktreesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveWorktrees, true
}

// SetActiveWorktrees sets field value
func (o *SwarmStatusResponse) SetActiveWorktrees(v int32) {
	o.ActiveWorktrees = v
}

// GetTotalWorktrees returns the TotalWorktrees field value
func (o *SwarmStatusResponse) GetTotalWorktrees() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalWorktrees
}

// GetTotalWorktreesOk returns a tuple with the TotalWorktrees field value
// and a boolean to check if the value has been set.
func (o *SwarmStatusResponse) GetTotalWorktreesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalWorktrees, true
}

// SetTotalWorktrees sets field value
func (o *SwarmStatusResponse) SetTotalWorktrees(v int32) {
	o.TotalWorktrees = v
}

// GetAgentPids returns the AgentPids field value
func (o *SwarmStatusResponse) GetAgentPids() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.AgentPids
}

// GetAgentPidsOk returns a tuple with the AgentPids field value
// and a boolean to check if the value has been set.
func (o *SwarmStatusResponse) GetAgentPidsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentPids, true
}

// SetAgentPids sets field value
func (o *SwarmStatusResponse) SetAgentPids(v []int32) {
	o.AgentPids = v
}

// GetTimestamp returns the Timestamp field value
func (o *SwarmStatusResponse) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *SwarmStatusResponse) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *SwarmStatusResponse) SetTimestamp(v string) {
	o.Timestamp = v
}

func (o SwarmStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwarmStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active_worktrees"] = o.ActiveWorktrees
	toSerialize["total_worktrees"] = o.TotalWorktrees
	toSerialize["agent_pids"] = o.AgentPids
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *SwarmStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active_worktrees",
		"total_worktrees",
		"agent_pids",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSwarmStatusResponse := _SwarmStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSwarmStatusResponse)

	if err != nil {
		return err
	}

	*o = SwarmStatusResponse(varSwarmStatusResponse)

	return err
}

type NullableSwarmStatusResponse struct {
	value *SwarmStatusResponse
	isSet bool
}

func (v NullableSwarmStatusResponse) Get() *SwarmStatusResponse {
	return v.value
}

func (v *NullableSwarmStatusResponse) Set(val *SwarmStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSwarmStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSwarmStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwarmStatusResponse(val *SwarmStatusResponse) *NullableSwarmStatusResponse {
	return &NullableSwarmStatusResponse{value: val, isSet: true}
}

func (v NullableSwarmStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwarmStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


