/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MejoraloSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MejoraloSessionRequest{}

// MejoraloSessionRequest struct for MejoraloSessionRequest
type MejoraloSessionRequest struct {
	Project string `json:"project"`
	ScoreBefore int32 `json:"score_before"`
	ScoreAfter int32 `json:"score_after"`
	Actions []string `json:"actions,omitempty"`
}

type _MejoraloSessionRequest MejoraloSessionRequest

// NewMejoraloSessionRequest instantiates a new MejoraloSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMejoraloSessionRequest(project string, scoreBefore int32, scoreAfter int32) *MejoraloSessionRequest {
	this := MejoraloSessionRequest{}
	this.Project = project
	this.ScoreBefore = scoreBefore
	this.ScoreAfter = scoreAfter
	return &this
}

// NewMejoraloSessionRequestWithDefaults instantiates a new MejoraloSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMejoraloSessionRequestWithDefaults() *MejoraloSessionRequest {
	this := MejoraloSessionRequest{}
	return &this
}

// GetProject returns the Project field value
func (o *MejoraloSessionRequest) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *MejoraloSessionRequest) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *MejoraloSessionRequest) SetProject(v string) {
	o.Project = v
}

// GetScoreBefore returns the ScoreBefore field value
func (o *MejoraloSessionRequest) GetScoreBefore() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ScoreBefore
}

// GetScoreBeforeOk returns a tuple with the ScoreBefore field value
// and a boolean to check if the value has been set.
func (o *MejoraloSessionRequest) GetScoreBeforeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScoreBefore, true
}

// SetScoreBefore sets field value
func (o *MejoraloSessionRequest) SetScoreBefore(v int32) {
	o.ScoreBefore = v
}

// GetScoreAfter returns the ScoreAfter field value
func (o *MejoraloSessionRequest) GetScoreAfter() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ScoreAfter
}

// GetScoreAfterOk returns a tuple with the ScoreAfter field value
// and a boolean to check if the value has been set.
func (o *MejoraloSessionRequest) GetScoreAfterOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScoreAfter, true
}

// SetScoreAfter sets field value
func (o *MejoraloSessionRequest) SetScoreAfter(v int32) {
	o.ScoreAfter = v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *MejoraloSessionRequest) GetActions() []string {
	if o == nil || IsNil(o.Actions) {
		var ret []string
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MejoraloSessionRequest) GetActionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *MejoraloSessionRequest) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []string and assigns it to the Actions field.
func (o *MejoraloSessionRequest) SetActions(v []string) {
	o.Actions = v
}

func (o MejoraloSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MejoraloSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project"] = o.Project
	toSerialize["score_before"] = o.ScoreBefore
	toSerialize["score_after"] = o.ScoreAfter
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	return toSerialize, nil
}

func (o *MejoraloSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project",
		"score_before",
		"score_after",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMejoraloSessionRequest := _MejoraloSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMejoraloSessionRequest)

	if err != nil {
		return err
	}

	*o = MejoraloSessionRequest(varMejoraloSessionRequest)

	return err
}

type NullableMejoraloSessionRequest struct {
	value *MejoraloSessionRequest
	isSet bool
}

func (v NullableMejoraloSessionRequest) Get() *MejoraloSessionRequest {
	return v.value
}

func (v *NullableMejoraloSessionRequest) Set(val *MejoraloSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMejoraloSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMejoraloSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMejoraloSessionRequest(val *MejoraloSessionRequest) *NullableMejoraloSessionRequest {
	return &NullableMejoraloSessionRequest{value: val, isSet: true}
}

func (v NullableMejoraloSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMejoraloSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


