/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"fmt"
)

// checks if the HealthCheckDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthCheckDetail{}

// HealthCheckDetail Single health probe result.
type HealthCheckDetail struct {
	Status string `json:"status"`
	Detail NullableString `json:"detail,omitempty"`
	Version NullableString `json:"version,omitempty"`
	Expected NullableString `json:"expected,omitempty"`
	Actual NullableString `json:"actual,omitempty"`
	PendingUncheckpointed NullableInt32 `json:"pending_uncheckpointed,omitempty"`
	LastCheckpointTx NullableInt32 `json:"last_checkpoint_tx,omitempty"`
	ActiveConnections NullableInt32 `json:"active_connections,omitempty"`
	MaxConnections NullableInt32 `json:"max_connections,omitempty"`
	Utilization NullableString `json:"utilization,omitempty"`
	UsefulFactsRatio NullableFloat32 `json:"useful_facts_ratio,omitempty"`
	DuplicatesRatio NullableFloat32 `json:"duplicates_ratio,omitempty"`
	TotalFacts NullableInt32 `json:"total_facts,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HealthCheckDetail HealthCheckDetail

// NewHealthCheckDetail instantiates a new HealthCheckDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheckDetail(status string) *HealthCheckDetail {
	this := HealthCheckDetail{}
	this.Status = status
	return &this
}

// NewHealthCheckDetailWithDefaults instantiates a new HealthCheckDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheckDetailWithDefaults() *HealthCheckDetail {
	this := HealthCheckDetail{}
	return &this
}

// GetStatus returns the Status field value
func (o *HealthCheckDetail) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HealthCheckDetail) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HealthCheckDetail) SetStatus(v string) {
	o.Status = v
}

// GetDetail returns the Detail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetDetail() string {
	if o == nil || IsNil(o.Detail.Get()) {
		var ret string
		return ret
	}
	return *o.Detail.Get()
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Detail.Get(), o.Detail.IsSet()
}

// HasDetail returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasDetail() bool {
	if o != nil && o.Detail.IsSet() {
		return true
	}

	return false
}

// SetDetail gets a reference to the given NullableString and assigns it to the Detail field.
func (o *HealthCheckDetail) SetDetail(v string) {
	o.Detail.Set(&v)
}
// SetDetailNil sets the value for Detail to be an explicit nil
func (o *HealthCheckDetail) SetDetailNil() {
	o.Detail.Set(nil)
}

// UnsetDetail ensures that no value is present for Detail, not even an explicit nil
func (o *HealthCheckDetail) UnsetDetail() {
	o.Detail.Unset()
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *HealthCheckDetail) SetVersion(v string) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *HealthCheckDetail) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *HealthCheckDetail) UnsetVersion() {
	o.Version.Unset()
}

// GetExpected returns the Expected field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetExpected() string {
	if o == nil || IsNil(o.Expected.Get()) {
		var ret string
		return ret
	}
	return *o.Expected.Get()
}

// GetExpectedOk returns a tuple with the Expected field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetExpectedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Expected.Get(), o.Expected.IsSet()
}

// HasExpected returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasExpected() bool {
	if o != nil && o.Expected.IsSet() {
		return true
	}

	return false
}

// SetExpected gets a reference to the given NullableString and assigns it to the Expected field.
func (o *HealthCheckDetail) SetExpected(v string) {
	o.Expected.Set(&v)
}
// SetExpectedNil sets the value for Expected to be an explicit nil
func (o *HealthCheckDetail) SetExpectedNil() {
	o.Expected.Set(nil)
}

// UnsetExpected ensures that no value is present for Expected, not even an explicit nil
func (o *HealthCheckDetail) UnsetExpected() {
	o.Expected.Unset()
}

// GetActual returns the Actual field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetActual() string {
	if o == nil || IsNil(o.Actual.Get()) {
		var ret string
		return ret
	}
	return *o.Actual.Get()
}

// GetActualOk returns a tuple with the Actual field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetActualOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actual.Get(), o.Actual.IsSet()
}

// HasActual returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasActual() bool {
	if o != nil && o.Actual.IsSet() {
		return true
	}

	return false
}

// SetActual gets a reference to the given NullableString and assigns it to the Actual field.
func (o *HealthCheckDetail) SetActual(v string) {
	o.Actual.Set(&v)
}
// SetActualNil sets the value for Actual to be an explicit nil
func (o *HealthCheckDetail) SetActualNil() {
	o.Actual.Set(nil)
}

// UnsetActual ensures that no value is present for Actual, not even an explicit nil
func (o *HealthCheckDetail) UnsetActual() {
	o.Actual.Unset()
}

// GetPendingUncheckpointed returns the PendingUncheckpointed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetPendingUncheckpointed() int32 {
	if o == nil || IsNil(o.PendingUncheckpointed.Get()) {
		var ret int32
		return ret
	}
	return *o.PendingUncheckpointed.Get()
}

// GetPendingUncheckpointedOk returns a tuple with the PendingUncheckpointed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetPendingUncheckpointedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PendingUncheckpointed.Get(), o.PendingUncheckpointed.IsSet()
}

// HasPendingUncheckpointed returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasPendingUncheckpointed() bool {
	if o != nil && o.PendingUncheckpointed.IsSet() {
		return true
	}

	return false
}

// SetPendingUncheckpointed gets a reference to the given NullableInt32 and assigns it to the PendingUncheckpointed field.
func (o *HealthCheckDetail) SetPendingUncheckpointed(v int32) {
	o.PendingUncheckpointed.Set(&v)
}
// SetPendingUncheckpointedNil sets the value for PendingUncheckpointed to be an explicit nil
func (o *HealthCheckDetail) SetPendingUncheckpointedNil() {
	o.PendingUncheckpointed.Set(nil)
}

// UnsetPendingUncheckpointed ensures that no value is present for PendingUncheckpointed, not even an explicit nil
func (o *HealthCheckDetail) UnsetPendingUncheckpointed() {
	o.PendingUncheckpointed.Unset()
}

// GetLastCheckpointTx returns the LastCheckpointTx field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetLastCheckpointTx() int32 {
	if o == nil || IsNil(o.LastCheckpointTx.Get()) {
		var ret int32
		return ret
	}
	return *o.LastCheckpointTx.Get()
}

// GetLastCheckpointTxOk returns a tuple with the LastCheckpointTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetLastCheckpointTxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastCheckpointTx.Get(), o.LastCheckpointTx.IsSet()
}

// HasLastCheckpointTx returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasLastCheckpointTx() bool {
	if o != nil && o.LastCheckpointTx.IsSet() {
		return true
	}

	return false
}

// SetLastCheckpointTx gets a reference to the given NullableInt32 and assigns it to the LastCheckpointTx field.
func (o *HealthCheckDetail) SetLastCheckpointTx(v int32) {
	o.LastCheckpointTx.Set(&v)
}
// SetLastCheckpointTxNil sets the value for LastCheckpointTx to be an explicit nil
func (o *HealthCheckDetail) SetLastCheckpointTxNil() {
	o.LastCheckpointTx.Set(nil)
}

// UnsetLastCheckpointTx ensures that no value is present for LastCheckpointTx, not even an explicit nil
func (o *HealthCheckDetail) UnsetLastCheckpointTx() {
	o.LastCheckpointTx.Unset()
}

// GetActiveConnections returns the ActiveConnections field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetActiveConnections() int32 {
	if o == nil || IsNil(o.ActiveConnections.Get()) {
		var ret int32
		return ret
	}
	return *o.ActiveConnections.Get()
}

// GetActiveConnectionsOk returns a tuple with the ActiveConnections field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetActiveConnectionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveConnections.Get(), o.ActiveConnections.IsSet()
}

// HasActiveConnections returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasActiveConnections() bool {
	if o != nil && o.ActiveConnections.IsSet() {
		return true
	}

	return false
}

// SetActiveConnections gets a reference to the given NullableInt32 and assigns it to the ActiveConnections field.
func (o *HealthCheckDetail) SetActiveConnections(v int32) {
	o.ActiveConnections.Set(&v)
}
// SetActiveConnectionsNil sets the value for ActiveConnections to be an explicit nil
func (o *HealthCheckDetail) SetActiveConnectionsNil() {
	o.ActiveConnections.Set(nil)
}

// UnsetActiveConnections ensures that no value is present for ActiveConnections, not even an explicit nil
func (o *HealthCheckDetail) UnsetActiveConnections() {
	o.ActiveConnections.Unset()
}

// GetMaxConnections returns the MaxConnections field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetMaxConnections() int32 {
	if o == nil || IsNil(o.MaxConnections.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxConnections.Get()
}

// GetMaxConnectionsOk returns a tuple with the MaxConnections field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetMaxConnectionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxConnections.Get(), o.MaxConnections.IsSet()
}

// HasMaxConnections returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasMaxConnections() bool {
	if o != nil && o.MaxConnections.IsSet() {
		return true
	}

	return false
}

// SetMaxConnections gets a reference to the given NullableInt32 and assigns it to the MaxConnections field.
func (o *HealthCheckDetail) SetMaxConnections(v int32) {
	o.MaxConnections.Set(&v)
}
// SetMaxConnectionsNil sets the value for MaxConnections to be an explicit nil
func (o *HealthCheckDetail) SetMaxConnectionsNil() {
	o.MaxConnections.Set(nil)
}

// UnsetMaxConnections ensures that no value is present for MaxConnections, not even an explicit nil
func (o *HealthCheckDetail) UnsetMaxConnections() {
	o.MaxConnections.Unset()
}

// GetUtilization returns the Utilization field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetUtilization() string {
	if o == nil || IsNil(o.Utilization.Get()) {
		var ret string
		return ret
	}
	return *o.Utilization.Get()
}

// GetUtilizationOk returns a tuple with the Utilization field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetUtilizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Utilization.Get(), o.Utilization.IsSet()
}

// HasUtilization returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasUtilization() bool {
	if o != nil && o.Utilization.IsSet() {
		return true
	}

	return false
}

// SetUtilization gets a reference to the given NullableString and assigns it to the Utilization field.
func (o *HealthCheckDetail) SetUtilization(v string) {
	o.Utilization.Set(&v)
}
// SetUtilizationNil sets the value for Utilization to be an explicit nil
func (o *HealthCheckDetail) SetUtilizationNil() {
	o.Utilization.Set(nil)
}

// UnsetUtilization ensures that no value is present for Utilization, not even an explicit nil
func (o *HealthCheckDetail) UnsetUtilization() {
	o.Utilization.Unset()
}

// GetUsefulFactsRatio returns the UsefulFactsRatio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetUsefulFactsRatio() float32 {
	if o == nil || IsNil(o.UsefulFactsRatio.Get()) {
		var ret float32
		return ret
	}
	return *o.UsefulFactsRatio.Get()
}

// GetUsefulFactsRatioOk returns a tuple with the UsefulFactsRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetUsefulFactsRatioOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsefulFactsRatio.Get(), o.UsefulFactsRatio.IsSet()
}

// HasUsefulFactsRatio returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasUsefulFactsRatio() bool {
	if o != nil && o.UsefulFactsRatio.IsSet() {
		return true
	}

	return false
}

// SetUsefulFactsRatio gets a reference to the given NullableFloat32 and assigns it to the UsefulFactsRatio field.
func (o *HealthCheckDetail) SetUsefulFactsRatio(v float32) {
	o.UsefulFactsRatio.Set(&v)
}
// SetUsefulFactsRatioNil sets the value for UsefulFactsRatio to be an explicit nil
func (o *HealthCheckDetail) SetUsefulFactsRatioNil() {
	o.UsefulFactsRatio.Set(nil)
}

// UnsetUsefulFactsRatio ensures that no value is present for UsefulFactsRatio, not even an explicit nil
func (o *HealthCheckDetail) UnsetUsefulFactsRatio() {
	o.UsefulFactsRatio.Unset()
}

// GetDuplicatesRatio returns the DuplicatesRatio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetDuplicatesRatio() float32 {
	if o == nil || IsNil(o.DuplicatesRatio.Get()) {
		var ret float32
		return ret
	}
	return *o.DuplicatesRatio.Get()
}

// GetDuplicatesRatioOk returns a tuple with the DuplicatesRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetDuplicatesRatioOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DuplicatesRatio.Get(), o.DuplicatesRatio.IsSet()
}

// HasDuplicatesRatio returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasDuplicatesRatio() bool {
	if o != nil && o.DuplicatesRatio.IsSet() {
		return true
	}

	return false
}

// SetDuplicatesRatio gets a reference to the given NullableFloat32 and assigns it to the DuplicatesRatio field.
func (o *HealthCheckDetail) SetDuplicatesRatio(v float32) {
	o.DuplicatesRatio.Set(&v)
}
// SetDuplicatesRatioNil sets the value for DuplicatesRatio to be an explicit nil
func (o *HealthCheckDetail) SetDuplicatesRatioNil() {
	o.DuplicatesRatio.Set(nil)
}

// UnsetDuplicatesRatio ensures that no value is present for DuplicatesRatio, not even an explicit nil
func (o *HealthCheckDetail) UnsetDuplicatesRatio() {
	o.DuplicatesRatio.Unset()
}

// GetTotalFacts returns the TotalFacts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckDetail) GetTotalFacts() int32 {
	if o == nil || IsNil(o.TotalFacts.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalFacts.Get()
}

// GetTotalFactsOk returns a tuple with the TotalFacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckDetail) GetTotalFactsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalFacts.Get(), o.TotalFacts.IsSet()
}

// HasTotalFacts returns a boolean if a field has been set.
func (o *HealthCheckDetail) HasTotalFacts() bool {
	if o != nil && o.TotalFacts.IsSet() {
		return true
	}

	return false
}

// SetTotalFacts gets a reference to the given NullableInt32 and assigns it to the TotalFacts field.
func (o *HealthCheckDetail) SetTotalFacts(v int32) {
	o.TotalFacts.Set(&v)
}
// SetTotalFactsNil sets the value for TotalFacts to be an explicit nil
func (o *HealthCheckDetail) SetTotalFactsNil() {
	o.TotalFacts.Set(nil)
}

// UnsetTotalFacts ensures that no value is present for TotalFacts, not even an explicit nil
func (o *HealthCheckDetail) UnsetTotalFacts() {
	o.TotalFacts.Unset()
}

func (o HealthCheckDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthCheckDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if o.Detail.IsSet() {
		toSerialize["detail"] = o.Detail.Get()
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if o.Expected.IsSet() {
		toSerialize["expected"] = o.Expected.Get()
	}
	if o.Actual.IsSet() {
		toSerialize["actual"] = o.Actual.Get()
	}
	if o.PendingUncheckpointed.IsSet() {
		toSerialize["pending_uncheckpointed"] = o.PendingUncheckpointed.Get()
	}
	if o.LastCheckpointTx.IsSet() {
		toSerialize["last_checkpoint_tx"] = o.LastCheckpointTx.Get()
	}
	if o.ActiveConnections.IsSet() {
		toSerialize["active_connections"] = o.ActiveConnections.Get()
	}
	if o.MaxConnections.IsSet() {
		toSerialize["max_connections"] = o.MaxConnections.Get()
	}
	if o.Utilization.IsSet() {
		toSerialize["utilization"] = o.Utilization.Get()
	}
	if o.UsefulFactsRatio.IsSet() {
		toSerialize["useful_facts_ratio"] = o.UsefulFactsRatio.Get()
	}
	if o.DuplicatesRatio.IsSet() {
		toSerialize["duplicates_ratio"] = o.DuplicatesRatio.Get()
	}
	if o.TotalFacts.IsSet() {
		toSerialize["total_facts"] = o.TotalFacts.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HealthCheckDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthCheckDetail := _HealthCheckDetail{}

	err = json.Unmarshal(data, &varHealthCheckDetail)

	if err != nil {
		return err
	}

	*o = HealthCheckDetail(varHealthCheckDetail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "detail")
		delete(additionalProperties, "version")
		delete(additionalProperties, "expected")
		delete(additionalProperties, "actual")
		delete(additionalProperties, "pending_uncheckpointed")
		delete(additionalProperties, "last_checkpoint_tx")
		delete(additionalProperties, "active_connections")
		delete(additionalProperties, "max_connections")
		delete(additionalProperties, "utilization")
		delete(additionalProperties, "useful_facts_ratio")
		delete(additionalProperties, "duplicates_ratio")
		delete(additionalProperties, "total_facts")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHealthCheckDetail struct {
	value *HealthCheckDetail
	isSet bool
}

func (v NullableHealthCheckDetail) Get() *HealthCheckDetail {
	return v.value
}

func (v *NullableHealthCheckDetail) Set(val *HealthCheckDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheckDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheckDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheckDetail(val *HealthCheckDetail) *NullableHealthCheckDetail {
	return &NullableHealthCheckDetail{value: val, isSet: true}
}

func (v NullableHealthCheckDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheckDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


