/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GateStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GateStatusResponse{}

// GateStatusResponse struct for GateStatusResponse
type GateStatusResponse struct {
	Policy string `json:"policy"`
	TimeoutSeconds int32 `json:"timeout_seconds"`
	Pending *int32 `json:"pending,omitempty"`
	Approved *int32 `json:"approved,omitempty"`
	Denied *int32 `json:"denied,omitempty"`
	Expired *int32 `json:"expired,omitempty"`
	Executed *int32 `json:"executed,omitempty"`
	TotalAuditEntries *int32 `json:"total_audit_entries,omitempty"`
}

type _GateStatusResponse GateStatusResponse

// NewGateStatusResponse instantiates a new GateStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGateStatusResponse(policy string, timeoutSeconds int32) *GateStatusResponse {
	this := GateStatusResponse{}
	this.Policy = policy
	this.TimeoutSeconds = timeoutSeconds
	var pending int32 = 0
	this.Pending = &pending
	var approved int32 = 0
	this.Approved = &approved
	var denied int32 = 0
	this.Denied = &denied
	var expired int32 = 0
	this.Expired = &expired
	var executed int32 = 0
	this.Executed = &executed
	var totalAuditEntries int32 = 0
	this.TotalAuditEntries = &totalAuditEntries
	return &this
}

// NewGateStatusResponseWithDefaults instantiates a new GateStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGateStatusResponseWithDefaults() *GateStatusResponse {
	this := GateStatusResponse{}
	var pending int32 = 0
	this.Pending = &pending
	var approved int32 = 0
	this.Approved = &approved
	var denied int32 = 0
	this.Denied = &denied
	var expired int32 = 0
	this.Expired = &expired
	var executed int32 = 0
	this.Executed = &executed
	var totalAuditEntries int32 = 0
	this.TotalAuditEntries = &totalAuditEntries
	return &this
}

// GetPolicy returns the Policy field value
func (o *GateStatusResponse) GetPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *GateStatusResponse) SetPolicy(v string) {
	o.Policy = v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value
func (o *GateStatusResponse) GetTimeoutSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeoutSeconds, true
}

// SetTimeoutSeconds sets field value
func (o *GateStatusResponse) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = v
}

// GetPending returns the Pending field value if set, zero value otherwise.
func (o *GateStatusResponse) GetPending() int32 {
	if o == nil || IsNil(o.Pending) {
		var ret int32
		return ret
	}
	return *o.Pending
}

// GetPendingOk returns a tuple with the Pending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetPendingOk() (*int32, bool) {
	if o == nil || IsNil(o.Pending) {
		return nil, false
	}
	return o.Pending, true
}

// HasPending returns a boolean if a field has been set.
func (o *GateStatusResponse) HasPending() bool {
	if o != nil && !IsNil(o.Pending) {
		return true
	}

	return false
}

// SetPending gets a reference to the given int32 and assigns it to the Pending field.
func (o *GateStatusResponse) SetPending(v int32) {
	o.Pending = &v
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *GateStatusResponse) GetApproved() int32 {
	if o == nil || IsNil(o.Approved) {
		var ret int32
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetApprovedOk() (*int32, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *GateStatusResponse) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given int32 and assigns it to the Approved field.
func (o *GateStatusResponse) SetApproved(v int32) {
	o.Approved = &v
}

// GetDenied returns the Denied field value if set, zero value otherwise.
func (o *GateStatusResponse) GetDenied() int32 {
	if o == nil || IsNil(o.Denied) {
		var ret int32
		return ret
	}
	return *o.Denied
}

// GetDeniedOk returns a tuple with the Denied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetDeniedOk() (*int32, bool) {
	if o == nil || IsNil(o.Denied) {
		return nil, false
	}
	return o.Denied, true
}

// HasDenied returns a boolean if a field has been set.
func (o *GateStatusResponse) HasDenied() bool {
	if o != nil && !IsNil(o.Denied) {
		return true
	}

	return false
}

// SetDenied gets a reference to the given int32 and assigns it to the Denied field.
func (o *GateStatusResponse) SetDenied(v int32) {
	o.Denied = &v
}

// GetExpired returns the Expired field value if set, zero value otherwise.
func (o *GateStatusResponse) GetExpired() int32 {
	if o == nil || IsNil(o.Expired) {
		var ret int32
		return ret
	}
	return *o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetExpiredOk() (*int32, bool) {
	if o == nil || IsNil(o.Expired) {
		return nil, false
	}
	return o.Expired, true
}

// HasExpired returns a boolean if a field has been set.
func (o *GateStatusResponse) HasExpired() bool {
	if o != nil && !IsNil(o.Expired) {
		return true
	}

	return false
}

// SetExpired gets a reference to the given int32 and assigns it to the Expired field.
func (o *GateStatusResponse) SetExpired(v int32) {
	o.Expired = &v
}

// GetExecuted returns the Executed field value if set, zero value otherwise.
func (o *GateStatusResponse) GetExecuted() int32 {
	if o == nil || IsNil(o.Executed) {
		var ret int32
		return ret
	}
	return *o.Executed
}

// GetExecutedOk returns a tuple with the Executed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetExecutedOk() (*int32, bool) {
	if o == nil || IsNil(o.Executed) {
		return nil, false
	}
	return o.Executed, true
}

// HasExecuted returns a boolean if a field has been set.
func (o *GateStatusResponse) HasExecuted() bool {
	if o != nil && !IsNil(o.Executed) {
		return true
	}

	return false
}

// SetExecuted gets a reference to the given int32 and assigns it to the Executed field.
func (o *GateStatusResponse) SetExecuted(v int32) {
	o.Executed = &v
}

// GetTotalAuditEntries returns the TotalAuditEntries field value if set, zero value otherwise.
func (o *GateStatusResponse) GetTotalAuditEntries() int32 {
	if o == nil || IsNil(o.TotalAuditEntries) {
		var ret int32
		return ret
	}
	return *o.TotalAuditEntries
}

// GetTotalAuditEntriesOk returns a tuple with the TotalAuditEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GateStatusResponse) GetTotalAuditEntriesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalAuditEntries) {
		return nil, false
	}
	return o.TotalAuditEntries, true
}

// HasTotalAuditEntries returns a boolean if a field has been set.
func (o *GateStatusResponse) HasTotalAuditEntries() bool {
	if o != nil && !IsNil(o.TotalAuditEntries) {
		return true
	}

	return false
}

// SetTotalAuditEntries gets a reference to the given int32 and assigns it to the TotalAuditEntries field.
func (o *GateStatusResponse) SetTotalAuditEntries(v int32) {
	o.TotalAuditEntries = &v
}

func (o GateStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GateStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	toSerialize["timeout_seconds"] = o.TimeoutSeconds
	if !IsNil(o.Pending) {
		toSerialize["pending"] = o.Pending
	}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !IsNil(o.Denied) {
		toSerialize["denied"] = o.Denied
	}
	if !IsNil(o.Expired) {
		toSerialize["expired"] = o.Expired
	}
	if !IsNil(o.Executed) {
		toSerialize["executed"] = o.Executed
	}
	if !IsNil(o.TotalAuditEntries) {
		toSerialize["total_audit_entries"] = o.TotalAuditEntries
	}
	return toSerialize, nil
}

func (o *GateStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy",
		"timeout_seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGateStatusResponse := _GateStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGateStatusResponse)

	if err != nil {
		return err
	}

	*o = GateStatusResponse(varGateStatusResponse)

	return err
}

type NullableGateStatusResponse struct {
	value *GateStatusResponse
	isSet bool
}

func (v NullableGateStatusResponse) Get() *GateStatusResponse {
	return v.value
}

func (v *NullableGateStatusResponse) Set(val *GateStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGateStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGateStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGateStatusResponse(val *GateStatusResponse) *NullableGateStatusResponse {
	return &NullableGateStatusResponse{value: val, isSet: true}
}

func (v NullableGateStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGateStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


