/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TipsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TipsListResponse{}

// TipsListResponse Response for tip list endpoints.
type TipsListResponse struct {
	Tips []TipResponse `json:"tips"`
	// Number of tips returned
	Count int32 `json:"count"`
	Lang string `json:"lang"`
	Category NullableString `json:"category,omitempty"`
	Project NullableString `json:"project,omitempty"`
	TotalAvailable NullableInt32 `json:"total_available,omitempty"`
}

type _TipsListResponse TipsListResponse

// NewTipsListResponse instantiates a new TipsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTipsListResponse(tips []TipResponse, count int32, lang string) *TipsListResponse {
	this := TipsListResponse{}
	this.Tips = tips
	this.Count = count
	this.Lang = lang
	return &this
}

// NewTipsListResponseWithDefaults instantiates a new TipsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTipsListResponseWithDefaults() *TipsListResponse {
	this := TipsListResponse{}
	return &this
}

// GetTips returns the Tips field value
func (o *TipsListResponse) GetTips() []TipResponse {
	if o == nil {
		var ret []TipResponse
		return ret
	}

	return o.Tips
}

// GetTipsOk returns a tuple with the Tips field value
// and a boolean to check if the value has been set.
func (o *TipsListResponse) GetTipsOk() ([]TipResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tips, true
}

// SetTips sets field value
func (o *TipsListResponse) SetTips(v []TipResponse) {
	o.Tips = v
}

// GetCount returns the Count field value
func (o *TipsListResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TipsListResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TipsListResponse) SetCount(v int32) {
	o.Count = v
}

// GetLang returns the Lang field value
func (o *TipsListResponse) GetLang() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lang
}

// GetLangOk returns a tuple with the Lang field value
// and a boolean to check if the value has been set.
func (o *TipsListResponse) GetLangOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lang, true
}

// SetLang sets field value
func (o *TipsListResponse) SetLang(v string) {
	o.Lang = v
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TipsListResponse) GetCategory() string {
	if o == nil || IsNil(o.Category.Get()) {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TipsListResponse) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *TipsListResponse) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *TipsListResponse) SetCategory(v string) {
	o.Category.Set(&v)
}
// SetCategoryNil sets the value for Category to be an explicit nil
func (o *TipsListResponse) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *TipsListResponse) UnsetCategory() {
	o.Category.Unset()
}

// GetProject returns the Project field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TipsListResponse) GetProject() string {
	if o == nil || IsNil(o.Project.Get()) {
		var ret string
		return ret
	}
	return *o.Project.Get()
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TipsListResponse) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Project.Get(), o.Project.IsSet()
}

// HasProject returns a boolean if a field has been set.
func (o *TipsListResponse) HasProject() bool {
	if o != nil && o.Project.IsSet() {
		return true
	}

	return false
}

// SetProject gets a reference to the given NullableString and assigns it to the Project field.
func (o *TipsListResponse) SetProject(v string) {
	o.Project.Set(&v)
}
// SetProjectNil sets the value for Project to be an explicit nil
func (o *TipsListResponse) SetProjectNil() {
	o.Project.Set(nil)
}

// UnsetProject ensures that no value is present for Project, not even an explicit nil
func (o *TipsListResponse) UnsetProject() {
	o.Project.Unset()
}

// GetTotalAvailable returns the TotalAvailable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TipsListResponse) GetTotalAvailable() int32 {
	if o == nil || IsNil(o.TotalAvailable.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalAvailable.Get()
}

// GetTotalAvailableOk returns a tuple with the TotalAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TipsListResponse) GetTotalAvailableOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalAvailable.Get(), o.TotalAvailable.IsSet()
}

// HasTotalAvailable returns a boolean if a field has been set.
func (o *TipsListResponse) HasTotalAvailable() bool {
	if o != nil && o.TotalAvailable.IsSet() {
		return true
	}

	return false
}

// SetTotalAvailable gets a reference to the given NullableInt32 and assigns it to the TotalAvailable field.
func (o *TipsListResponse) SetTotalAvailable(v int32) {
	o.TotalAvailable.Set(&v)
}
// SetTotalAvailableNil sets the value for TotalAvailable to be an explicit nil
func (o *TipsListResponse) SetTotalAvailableNil() {
	o.TotalAvailable.Set(nil)
}

// UnsetTotalAvailable ensures that no value is present for TotalAvailable, not even an explicit nil
func (o *TipsListResponse) UnsetTotalAvailable() {
	o.TotalAvailable.Unset()
}

func (o TipsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TipsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tips"] = o.Tips
	toSerialize["count"] = o.Count
	toSerialize["lang"] = o.Lang
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if o.Project.IsSet() {
		toSerialize["project"] = o.Project.Get()
	}
	if o.TotalAvailable.IsSet() {
		toSerialize["total_available"] = o.TotalAvailable.Get()
	}
	return toSerialize, nil
}

func (o *TipsListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tips",
		"count",
		"lang",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTipsListResponse := _TipsListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTipsListResponse)

	if err != nil {
		return err
	}

	*o = TipsListResponse(varTipsListResponse)

	return err
}

type NullableTipsListResponse struct {
	value *TipsListResponse
	isSet bool
}

func (v NullableTipsListResponse) Get() *TipsListResponse {
	return v.value
}

func (v *NullableTipsListResponse) Set(val *TipsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTipsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTipsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTipsListResponse(val *TipsListResponse) *NullableTipsListResponse {
	return &NullableTipsListResponse{value: val, isSet: true}
}

func (v NullableTipsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTipsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


