/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckpointResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckpointResponse{}

// CheckpointResponse struct for CheckpointResponse
type CheckpointResponse struct {
	CheckpointId NullableCheckpointId `json:"checkpoint_id"`
	Message string `json:"message"`
	Status *string `json:"status,omitempty"`
}

type _CheckpointResponse CheckpointResponse

// NewCheckpointResponse instantiates a new CheckpointResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckpointResponse(checkpointId NullableCheckpointId, message string) *CheckpointResponse {
	this := CheckpointResponse{}
	this.CheckpointId = checkpointId
	this.Message = message
	var status string = "success"
	this.Status = &status
	return &this
}

// NewCheckpointResponseWithDefaults instantiates a new CheckpointResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckpointResponseWithDefaults() *CheckpointResponse {
	this := CheckpointResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetCheckpointId returns the CheckpointId field value
// If the value is explicit nil, the zero value for CheckpointId will be returned
func (o *CheckpointResponse) GetCheckpointId() CheckpointId {
	if o == nil || o.CheckpointId.Get() == nil {
		var ret CheckpointId
		return ret
	}

	return *o.CheckpointId.Get()
}

// GetCheckpointIdOk returns a tuple with the CheckpointId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckpointResponse) GetCheckpointIdOk() (*CheckpointId, bool) {
	if o == nil {
		return nil, false
	}
	return o.CheckpointId.Get(), o.CheckpointId.IsSet()
}

// SetCheckpointId sets field value
func (o *CheckpointResponse) SetCheckpointId(v CheckpointId) {
	o.CheckpointId.Set(&v)
}

// GetMessage returns the Message field value
func (o *CheckpointResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CheckpointResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CheckpointResponse) SetMessage(v string) {
	o.Message = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CheckpointResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckpointResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CheckpointResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CheckpointResponse) SetStatus(v string) {
	o.Status = &v
}

func (o CheckpointResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckpointResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["checkpoint_id"] = o.CheckpointId.Get()
	toSerialize["message"] = o.Message
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *CheckpointResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"checkpoint_id",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckpointResponse := _CheckpointResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckpointResponse)

	if err != nil {
		return err
	}

	*o = CheckpointResponse(varCheckpointResponse)

	return err
}

type NullableCheckpointResponse struct {
	value *CheckpointResponse
	isSet bool
}

func (v NullableCheckpointResponse) Get() *CheckpointResponse {
	return v.value
}

func (v *NullableCheckpointResponse) Set(val *CheckpointResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckpointResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckpointResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckpointResponse(val *CheckpointResponse) *NullableCheckpointResponse {
	return &NullableCheckpointResponse{value: val, isSet: true}
}

func (v NullableCheckpointResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckpointResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


