/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LedgerReportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LedgerReportResponse{}

// LedgerReportResponse struct for LedgerReportResponse
type LedgerReportResponse struct {
	Valid bool `json:"valid"`
	Violations []*map[string]interface{} `json:"violations"`
	TxChecked *int32 `json:"tx_checked,omitempty"`
	RootsChecked *int32 `json:"roots_checked,omitempty"`
	VotesChecked *int32 `json:"votes_checked,omitempty"`
	VoteCheckpointsChecked *int32 `json:"vote_checkpoints_checked,omitempty"`
}

type _LedgerReportResponse LedgerReportResponse

// NewLedgerReportResponse instantiates a new LedgerReportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLedgerReportResponse(valid bool, violations []*map[string]interface{}) *LedgerReportResponse {
	this := LedgerReportResponse{}
	this.Valid = valid
	this.Violations = violations
	var txChecked int32 = 0
	this.TxChecked = &txChecked
	var rootsChecked int32 = 0
	this.RootsChecked = &rootsChecked
	var votesChecked int32 = 0
	this.VotesChecked = &votesChecked
	var voteCheckpointsChecked int32 = 0
	this.VoteCheckpointsChecked = &voteCheckpointsChecked
	return &this
}

// NewLedgerReportResponseWithDefaults instantiates a new LedgerReportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLedgerReportResponseWithDefaults() *LedgerReportResponse {
	this := LedgerReportResponse{}
	var txChecked int32 = 0
	this.TxChecked = &txChecked
	var rootsChecked int32 = 0
	this.RootsChecked = &rootsChecked
	var votesChecked int32 = 0
	this.VotesChecked = &votesChecked
	var voteCheckpointsChecked int32 = 0
	this.VoteCheckpointsChecked = &voteCheckpointsChecked
	return &this
}

// GetValid returns the Valid field value
func (o *LedgerReportResponse) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *LedgerReportResponse) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *LedgerReportResponse) SetValid(v bool) {
	o.Valid = v
}

// GetViolations returns the Violations field value
func (o *LedgerReportResponse) GetViolations() []*map[string]interface{} {
	if o == nil {
		var ret []*map[string]interface{}
		return ret
	}

	return o.Violations
}

// GetViolationsOk returns a tuple with the Violations field value
// and a boolean to check if the value has been set.
func (o *LedgerReportResponse) GetViolationsOk() ([]*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Violations, true
}

// SetViolations sets field value
func (o *LedgerReportResponse) SetViolations(v []*map[string]interface{}) {
	o.Violations = v
}

// GetTxChecked returns the TxChecked field value if set, zero value otherwise.
func (o *LedgerReportResponse) GetTxChecked() int32 {
	if o == nil || IsNil(o.TxChecked) {
		var ret int32
		return ret
	}
	return *o.TxChecked
}

// GetTxCheckedOk returns a tuple with the TxChecked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LedgerReportResponse) GetTxCheckedOk() (*int32, bool) {
	if o == nil || IsNil(o.TxChecked) {
		return nil, false
	}
	return o.TxChecked, true
}

// HasTxChecked returns a boolean if a field has been set.
func (o *LedgerReportResponse) HasTxChecked() bool {
	if o != nil && !IsNil(o.TxChecked) {
		return true
	}

	return false
}

// SetTxChecked gets a reference to the given int32 and assigns it to the TxChecked field.
func (o *LedgerReportResponse) SetTxChecked(v int32) {
	o.TxChecked = &v
}

// GetRootsChecked returns the RootsChecked field value if set, zero value otherwise.
func (o *LedgerReportResponse) GetRootsChecked() int32 {
	if o == nil || IsNil(o.RootsChecked) {
		var ret int32
		return ret
	}
	return *o.RootsChecked
}

// GetRootsCheckedOk returns a tuple with the RootsChecked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LedgerReportResponse) GetRootsCheckedOk() (*int32, bool) {
	if o == nil || IsNil(o.RootsChecked) {
		return nil, false
	}
	return o.RootsChecked, true
}

// HasRootsChecked returns a boolean if a field has been set.
func (o *LedgerReportResponse) HasRootsChecked() bool {
	if o != nil && !IsNil(o.RootsChecked) {
		return true
	}

	return false
}

// SetRootsChecked gets a reference to the given int32 and assigns it to the RootsChecked field.
func (o *LedgerReportResponse) SetRootsChecked(v int32) {
	o.RootsChecked = &v
}

// GetVotesChecked returns the VotesChecked field value if set, zero value otherwise.
func (o *LedgerReportResponse) GetVotesChecked() int32 {
	if o == nil || IsNil(o.VotesChecked) {
		var ret int32
		return ret
	}
	return *o.VotesChecked
}

// GetVotesCheckedOk returns a tuple with the VotesChecked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LedgerReportResponse) GetVotesCheckedOk() (*int32, bool) {
	if o == nil || IsNil(o.VotesChecked) {
		return nil, false
	}
	return o.VotesChecked, true
}

// HasVotesChecked returns a boolean if a field has been set.
func (o *LedgerReportResponse) HasVotesChecked() bool {
	if o != nil && !IsNil(o.VotesChecked) {
		return true
	}

	return false
}

// SetVotesChecked gets a reference to the given int32 and assigns it to the VotesChecked field.
func (o *LedgerReportResponse) SetVotesChecked(v int32) {
	o.VotesChecked = &v
}

// GetVoteCheckpointsChecked returns the VoteCheckpointsChecked field value if set, zero value otherwise.
func (o *LedgerReportResponse) GetVoteCheckpointsChecked() int32 {
	if o == nil || IsNil(o.VoteCheckpointsChecked) {
		var ret int32
		return ret
	}
	return *o.VoteCheckpointsChecked
}

// GetVoteCheckpointsCheckedOk returns a tuple with the VoteCheckpointsChecked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LedgerReportResponse) GetVoteCheckpointsCheckedOk() (*int32, bool) {
	if o == nil || IsNil(o.VoteCheckpointsChecked) {
		return nil, false
	}
	return o.VoteCheckpointsChecked, true
}

// HasVoteCheckpointsChecked returns a boolean if a field has been set.
func (o *LedgerReportResponse) HasVoteCheckpointsChecked() bool {
	if o != nil && !IsNil(o.VoteCheckpointsChecked) {
		return true
	}

	return false
}

// SetVoteCheckpointsChecked gets a reference to the given int32 and assigns it to the VoteCheckpointsChecked field.
func (o *LedgerReportResponse) SetVoteCheckpointsChecked(v int32) {
	o.VoteCheckpointsChecked = &v
}

func (o LedgerReportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LedgerReportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["valid"] = o.Valid
	toSerialize["violations"] = o.Violations
	if !IsNil(o.TxChecked) {
		toSerialize["tx_checked"] = o.TxChecked
	}
	if !IsNil(o.RootsChecked) {
		toSerialize["roots_checked"] = o.RootsChecked
	}
	if !IsNil(o.VotesChecked) {
		toSerialize["votes_checked"] = o.VotesChecked
	}
	if !IsNil(o.VoteCheckpointsChecked) {
		toSerialize["vote_checkpoints_checked"] = o.VoteCheckpointsChecked
	}
	return toSerialize, nil
}

func (o *LedgerReportResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"valid",
		"violations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLedgerReportResponse := _LedgerReportResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLedgerReportResponse)

	if err != nil {
		return err
	}

	*o = LedgerReportResponse(varLedgerReportResponse)

	return err
}

type NullableLedgerReportResponse struct {
	value *LedgerReportResponse
	isSet bool
}

func (v NullableLedgerReportResponse) Get() *LedgerReportResponse {
	return v.value
}

func (v *NullableLedgerReportResponse) Set(val *LedgerReportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLedgerReportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLedgerReportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLedgerReportResponse(val *LedgerReportResponse) *NullableLedgerReportResponse {
	return &NullableLedgerReportResponse{value: val, isSet: true}
}

func (v NullableLedgerReportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLedgerReportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


