/*
CORTEX - Sovereign Memory API

Local-first memory infrastructure for AI agents. Vector search, temporal facts, cryptographic ledger.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MissionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MissionResponse{}

// MissionResponse struct for MissionResponse
type MissionResponse struct {
	IntentId int32 `json:"intent_id"`
	ResultId NullableInt32 `json:"result_id,omitempty"`
	Status string `json:"status"`
	Stdout NullableString `json:"stdout,omitempty"`
	Stderr NullableString `json:"stderr,omitempty"`
}

type _MissionResponse MissionResponse

// NewMissionResponse instantiates a new MissionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMissionResponse(intentId int32, status string) *MissionResponse {
	this := MissionResponse{}
	this.IntentId = intentId
	this.Status = status
	return &this
}

// NewMissionResponseWithDefaults instantiates a new MissionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMissionResponseWithDefaults() *MissionResponse {
	this := MissionResponse{}
	return &this
}

// GetIntentId returns the IntentId field value
func (o *MissionResponse) GetIntentId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IntentId
}

// GetIntentIdOk returns a tuple with the IntentId field value
// and a boolean to check if the value has been set.
func (o *MissionResponse) GetIntentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntentId, true
}

// SetIntentId sets field value
func (o *MissionResponse) SetIntentId(v int32) {
	o.IntentId = v
}

// GetResultId returns the ResultId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MissionResponse) GetResultId() int32 {
	if o == nil || IsNil(o.ResultId.Get()) {
		var ret int32
		return ret
	}
	return *o.ResultId.Get()
}

// GetResultIdOk returns a tuple with the ResultId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MissionResponse) GetResultIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultId.Get(), o.ResultId.IsSet()
}

// HasResultId returns a boolean if a field has been set.
func (o *MissionResponse) HasResultId() bool {
	if o != nil && o.ResultId.IsSet() {
		return true
	}

	return false
}

// SetResultId gets a reference to the given NullableInt32 and assigns it to the ResultId field.
func (o *MissionResponse) SetResultId(v int32) {
	o.ResultId.Set(&v)
}
// SetResultIdNil sets the value for ResultId to be an explicit nil
func (o *MissionResponse) SetResultIdNil() {
	o.ResultId.Set(nil)
}

// UnsetResultId ensures that no value is present for ResultId, not even an explicit nil
func (o *MissionResponse) UnsetResultId() {
	o.ResultId.Unset()
}

// GetStatus returns the Status field value
func (o *MissionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MissionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MissionResponse) SetStatus(v string) {
	o.Status = v
}

// GetStdout returns the Stdout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MissionResponse) GetStdout() string {
	if o == nil || IsNil(o.Stdout.Get()) {
		var ret string
		return ret
	}
	return *o.Stdout.Get()
}

// GetStdoutOk returns a tuple with the Stdout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MissionResponse) GetStdoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stdout.Get(), o.Stdout.IsSet()
}

// HasStdout returns a boolean if a field has been set.
func (o *MissionResponse) HasStdout() bool {
	if o != nil && o.Stdout.IsSet() {
		return true
	}

	return false
}

// SetStdout gets a reference to the given NullableString and assigns it to the Stdout field.
func (o *MissionResponse) SetStdout(v string) {
	o.Stdout.Set(&v)
}
// SetStdoutNil sets the value for Stdout to be an explicit nil
func (o *MissionResponse) SetStdoutNil() {
	o.Stdout.Set(nil)
}

// UnsetStdout ensures that no value is present for Stdout, not even an explicit nil
func (o *MissionResponse) UnsetStdout() {
	o.Stdout.Unset()
}

// GetStderr returns the Stderr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MissionResponse) GetStderr() string {
	if o == nil || IsNil(o.Stderr.Get()) {
		var ret string
		return ret
	}
	return *o.Stderr.Get()
}

// GetStderrOk returns a tuple with the Stderr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MissionResponse) GetStderrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stderr.Get(), o.Stderr.IsSet()
}

// HasStderr returns a boolean if a field has been set.
func (o *MissionResponse) HasStderr() bool {
	if o != nil && o.Stderr.IsSet() {
		return true
	}

	return false
}

// SetStderr gets a reference to the given NullableString and assigns it to the Stderr field.
func (o *MissionResponse) SetStderr(v string) {
	o.Stderr.Set(&v)
}
// SetStderrNil sets the value for Stderr to be an explicit nil
func (o *MissionResponse) SetStderrNil() {
	o.Stderr.Set(nil)
}

// UnsetStderr ensures that no value is present for Stderr, not even an explicit nil
func (o *MissionResponse) UnsetStderr() {
	o.Stderr.Unset()
}

func (o MissionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MissionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["intent_id"] = o.IntentId
	if o.ResultId.IsSet() {
		toSerialize["result_id"] = o.ResultId.Get()
	}
	toSerialize["status"] = o.Status
	if o.Stdout.IsSet() {
		toSerialize["stdout"] = o.Stdout.Get()
	}
	if o.Stderr.IsSet() {
		toSerialize["stderr"] = o.Stderr.Get()
	}
	return toSerialize, nil
}

func (o *MissionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"intent_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMissionResponse := _MissionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMissionResponse)

	if err != nil {
		return err
	}

	*o = MissionResponse(varMissionResponse)

	return err
}

type NullableMissionResponse struct {
	value *MissionResponse
	isSet bool
}

func (v NullableMissionResponse) Get() *MissionResponse {
	return v.value
}

func (v *NullableMissionResponse) Set(val *MissionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMissionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMissionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMissionResponse(val *MissionResponse) *NullableMissionResponse {
	return &NullableMissionResponse{value: val, isSet: true}
}

func (v NullableMissionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMissionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


