import os

ROOT = "."

def update_taxonomy():
    old_yaml = os.path.join(ROOT, "cortex", "ontology", "1000_space_taxonomy.yaml")
    new_yaml = os.path.join(ROOT, "cortex", "ontology", "10000_space_taxonomy.yaml")
    
    with open(old_yaml, 'r') as f:
        content = f.read()
        
    content = content.replace("1000-SPACE", "10000-SPACE")
    content = content.replace("1000 Unique Operational States", "10000 Unique Operational States")
    content = content.replace("[Domain][Primitive][Modifier]", "[Domain][Primitive][Modifier][Target]")
    
    targets = """
Targets_Vector:
  0: "LOCAL"     # Local System
  1: "NETWORK"   # External Network
  2: "SWARM"     # Agent Swarm
  3: "LEDGER"    # BFT Ledger
  4: "MEMORY"    # Cortex Memory
  5: "DISPATCH"  # Task Dispatch
  6: "UI"        # Visual Interface
  7: "SYSTEM"    # OS Level
  8: "BFT"       # Byzantine Consensus
  9: "CORE"      # Core Kernel
"""
    content += targets
    
    with open(new_yaml, 'w') as f:
        f.write(content)
        
    if os.path.exists(old_yaml):
        os.remove(old_yaml)

def update_generate_primitives():
    path = os.path.join(ROOT, "scripts", "generate_primitives.py")
    with open(path, 'r') as f:
        content = f.read()
        
    content = content.replace('1000_space_taxonomy.yaml', '10000_space_taxonomy.yaml')
    content = content.replace('modifiers = {}', 'modifiers = {}\n    targets = {}')
    content = content.replace("elif line.startswith('Modifiers_Constraint:'):", "elif line.startswith('Modifiers_Constraint:'):\n            current_section = 'modifiers'\n            continue\n        elif line.startswith('Targets_Vector:'):")
    content = content.replace("current_section = 'modifiers'\n            continue", "current_section = 'targets'\n            continue") # wait, careful
    
    # Let's just rewrite generate_primitives.py
    new_content = """import os
import re

def main():
    yaml_path = "cortex/ontology/10000_space_taxonomy.yaml"
    output_path = "src-tauri/src/primitives_generated.rs"
    
    with open(yaml_path, 'r') as f:
        content = f.read()
    
    domains, primitives, modifiers, targets = {}, {}, {}, {}
    
    current_section = None
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if line.startswith('Domains_Context:'):
            current_section = 'domains'
            continue
        elif line.startswith('Primitives_Action:'):
            current_section = 'primitives'
            continue
        elif line.startswith('Modifiers_Constraint:'):
            current_section = 'modifiers'
            continue
        elif line.startswith('Targets_Vector:'):
            current_section = 'targets'
            continue
            
        match = re.match(r'(\d+):\s*"([^"]+)"', line)
        if match:
            idx = int(match.group(1))
            val = match.group(2)
            if current_section == 'domains': domains[idx] = val
            elif current_section == 'primitives': primitives[idx] = val
            elif current_section == 'modifiers': modifiers[idx] = val
            elif current_section == 'targets': targets[idx] = val

    assert len(domains) == 10
    assert len(primitives) == 10
    assert len(modifiers) == 10
    assert len(targets) == 10
    
    cases = []
    for d in range(10):
        for p in range(10):
            for m in range(10):
                for t in range(10):
                    code = d * 1000 + p * 100 + m * 10 + t
                    name = f"{domains[d]}-{primitives[p]}-{modifiers[m]}-{targets[t]}"
                    cases.append(f"        {code} => Some(|id| {{ println!(\\\"⚡ [{code:04}] {name} executed via generated retro-membrane.\\\"); }}),")
    
    rust_code = f\"\"\"// This file is auto-generated by generate_primitives.py. Do not edit.
use crate::kernel::PrimitiveIdentity;

pub fn get_generated_action(index: usize) -> Option<fn(&PrimitiveIdentity)> {{
    match index {{
{chr(10).join(cases)}
        _ => None,
    }}
}}
\"\"\"
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(rust_code)
    print(f"Generated {len(cases)} primitives in {output_path}")

if __name__ == "__main__":
    main()
"""
    with open(path, 'w') as f:
        f.write(new_content)

def update_audit_taxonomy():
    path = os.path.join(ROOT, "scripts", "audit_taxonomy.go")
    
    # A bit complex to regex replace, let's rewrite it based on what we saw
    new_content = """package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	yamlPath := "cortex/ontology/10000_space_taxonomy.yaml"
	primitivesDir := "primitives"
	reportPath := "AUDITORIA_TAXONOMIA_REPORT.md"

	content, err := ioutil.ReadFile(yamlPath)
	if err != nil {
		fmt.Printf("Error reading taxonomy file: %v\\n", err)
		os.Exit(1)
	}

	lines := strings.Split(string(content), "\\n")

	domains := make(map[int]string)
	primitives := make(map[int]string)
	modifiers := make(map[int]string)
	targets := make(map[int]string)

	var currentSection string
	re := regexp.MustCompile(`(\\d+):\\s*"([^"]+)"`)

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "Domains_Context:") {
			currentSection = "domains"
			continue
		} else if strings.HasPrefix(line, "Primitives_Action:") {
			currentSection = "primitives"
			continue
		} else if strings.HasPrefix(line, "Modifiers_Constraint:") {
			currentSection = "modifiers"
			continue
		} else if strings.HasPrefix(line, "Targets_Vector:") {
			currentSection = "targets"
			continue
		}

		matches := re.FindStringSubmatch(line)
		if len(matches) == 3 {
			idx, _ := strconv.Atoi(matches[1])
			val := matches[2]
			switch currentSection {
			case "domains":
				domains[idx] = val
			case "primitives":
				primitives[idx] = val
			case "modifiers":
				modifiers[idx] = val
			case "targets":
				targets[idx] = val
			}
		}
	}

	errors := []string{}
	if len(domains) != 10 {
		errors = append(errors, fmt.Sprintf("Audit Error: Expected 10 domains, found %d", len(domains)))
	}
	if len(primitives) != 10 {
		errors = append(errors, fmt.Sprintf("Audit Error: Expected 10 primitives, found %d", len(primitives)))
	}
	if len(modifiers) != 10 {
		errors = append(errors, fmt.Sprintf("Audit Error: Expected 10 modifiers, found %d", len(modifiers)))
	}
	if len(targets) != 10 {
		errors = append(errors, fmt.Sprintf("Audit Error: Expected 10 targets, found %d", len(targets)))
	}

	for i := 0; i < 10; i++ {
		if _, ok := domains[i]; !ok { errors = append(errors, fmt.Sprintf("Audit Error: Missing domain index %d", i)) }
		if _, ok := primitives[i]; !ok { errors = append(errors, fmt.Sprintf("Audit Error: Missing primitive index %d", i)) }
		if _, ok := modifiers[i]; !ok { errors = append(errors, fmt.Sprintf("Audit Error: Missing modifier index %d", i)) }
		if _, ok := targets[i]; !ok { errors = append(errors, fmt.Sprintf("Audit Error: Missing target index %d", i)) }
	}

	auditStatus := "SUCCESS"
	if len(errors) > 0 {
		auditStatus = "FAILED"
		fmt.Printf("Taxonomy Audit failed with errors:\\n%s\\n", strings.Join(errors, "\\n"))
	} else {
		fmt.Println("Taxonomy Audit SUCCESS. All 10000 states verified mathematically.")
	}

	var goCode strings.Builder
	goCode.WriteString(`// Code generated by audit_taxonomy.go. DO NOT EDIT.
package primitives

import (
	"errors"
	"fmt"
)

type Domain int
type Primitive int
type Modifier int
type Target int

const (
`)
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tDomain%s Domain = %d\\n", strings.Title(strings.ToLower(domains[i])), i))
	}
	goCode.WriteString("\\n\\t// Primitives\\n")
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tPrimitive%s Primitive = %d\\n", strings.Title(strings.ToLower(primitives[i])), i))
	}
	goCode.WriteString("\\n\\t// Modifiers\\n")
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tModifier%s Modifier = %d\\n", strings.Title(strings.ToLower(modifiers[i])), i))
	}
	goCode.WriteString("\\n\\t// Targets\\n")
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tTarget%s Target = %d\\n", strings.Title(strings.ToLower(targets[i])), i))
	}
	goCode.WriteString(`)

func (d Domain) String() string {
	switch d {
`)
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tcase %d: return %q\\n", i, domains[i]))
	}
	goCode.WriteString(`	default: return "UNKNOWN"
	}
}

func (p Primitive) String() string {
	switch p {
`)
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tcase %d: return %q\\n", i, primitives[i]))
	}
	goCode.WriteString(`	default: return "UNKNOWN"
	}
}

func (m Modifier) String() string {
	switch m {
`)
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tcase %d: return %q\\n", i, modifiers[i]))
	}
	goCode.WriteString(`	default: return "UNKNOWN"
	}
}

func (t Target) String() string {
	switch t {
`)
	for i := 0; i < 10; i++ {
		goCode.WriteString(fmt.Sprintf("\\tcase %d: return %q\\n", i, targets[i]))
	}
	goCode.WriteString(`	default: return "UNKNOWN"
	}
}

type PrimitiveIdentity struct {
	Domain    Domain
	Primitive Primitive
	Modifier  Modifier
	Target    Target
	Code      uint16
	Name      string
}

func ResolveIdentity(d, p, m, t byte) (PrimitiveIdentity, error) {
	if d > 9 || p > 9 || m > 9 || t > 9 {
		return PrimitiveIdentity{}, errors.New("invalid parameter indices out of range [0-9]")
	}
	code := uint16(d)*1000 + uint16(p)*100 + uint16(m)*10 + uint16(t)
	name := fmt.Sprintf("%s-%s-%s-%s", Domain(d).String(), Primitive(p).String(), Modifier(m).String(), Target(t).String())
	return PrimitiveIdentity{
		Domain:    Domain(d),
		Primitive: Primitive(p),
		Modifier:  Modifier(m),
		Target:    Target(t),
		Code:      code,
		Name:      name,
	}, nil
}

type Action func(identity PrimitiveIdentity)

var KernelTable [10000]Action

func defaultDispatchHandler(identity PrimitiveIdentity) {
	fmt.Printf("⚡ [%04d] %s executed via Go transductor.\\n", identity.Code, identity.Name)
}

func InitKernel() {
	for i := 0; i < 10000; i++ {
		KernelTable[i] = defaultDispatchHandler
	}
	
`)
	for d := 0; d < 10; d++ {
		for p := 0; p < 10; p++ {
			for m := 0; m < 10; m++ {
				for t := 0; t < 10; t++ {
					code := d*1000 + p*100 + m*10 + t
					name := fmt.Sprintf("%s-%s-%s-%s", domains[d], primitives[p], modifiers[m], targets[t])
					goCode.WriteString(fmt.Sprintf("\\tKernelTable[%d] = func(id PrimitiveIdentity) { fmt.Printf(\\\"⚡ [%04d] %s (Go retro-membrane)\\\\n\\\") }\\n", code, code, name))
				}
			}
		}
	}
	goCode.WriteString(`}

func Dispatch(d, p, m, t byte) error {
	identity, err := ResolveIdentity(d, p, m, t)
	if err != nil {
		return err
	}
	
	if KernelTable[identity.Code] == nil {
		return errors.New("kernel not initialized")
	}
	
	if identity.Modifier == 4 { // ModifierAsync
		go KernelTable[identity.Code](identity)
		return nil
	}
	
	KernelTable[identity.Code](identity)
	return nil
}
`)

	err = os.MkdirAll(primitivesDir, 0755)
	if err != nil {
		fmt.Printf("Error creating directory: %v\\n", err)
		os.Exit(1)
	}

	err = ioutil.WriteFile(filepath.Join(primitivesDir, "primitives.go"), []byte(goCode.String()), 0644)
	if err != nil {
		fmt.Printf("Error writing primitives.go: %v\\n", err)
		os.Exit(1)
	}

	var report strings.Builder
	report.WriteString("# AUDITORIA DE TAXONOMIA — INFORME DE COBERTURA C5-REAL\\n\\n")
	report.WriteString(fmt.Sprintf("## Estado de Auditoría: %s\\n\\n", auditStatus))
	report.WriteString("### Parámetros Generativos:\\n")
	report.WriteString(fmt.Sprintf("- **Dominios:** %d/10\\n", len(domains)))
	for i := 0; i < 10; i++ { report.WriteString(fmt.Sprintf("  - %d: %s\\n", i, domains[i])) }
	report.WriteString(fmt.Sprintf("- **Primitivas:** %d/10\\n", len(primitives)))
	for i := 0; i < 10; i++ { report.WriteString(fmt.Sprintf("  - %d: %s\\n", i, primitives[i])) }
	report.WriteString(fmt.Sprintf("- **Modificadores:** %d/10\\n", len(modifiers)))
	for i := 0; i < 10; i++ { report.WriteString(fmt.Sprintf("  - %d: %s\\n", i, modifiers[i])) }
	report.WriteString(fmt.Sprintf("- **Targets:** %d/10\\n", len(targets)))
	for i := 0; i < 10; i++ { report.WriteString(fmt.Sprintf("  - %d: %s\\n", i, targets[i])) }

	report.WriteString("\\n### Errores Encontrados:\\n")
	if len(errors) == 0 {
		report.WriteString("- Ninguno. Cobertura matemática del 100% de los 10000 estados.\\n")
	} else {
		for _, errStr := range errors {
			report.WriteString(fmt.Sprintf("- %s\\n", errStr))
		}
	}

	report.WriteString("\\n### Consenso BFT e Invariante de Exergía:\\n")
	report.WriteString("El motor de Go ha compilado de forma segura las 10000 combinaciones de la matriz de estados. ")
	report.WriteString("Toda primitiva ejecutada de forma asíncrona (modificador `4` / `ASYNC`) será despachada en una goroutine aislada.\\n")

	err = ioutil.WriteFile(reportPath, []byte(report.String()), 0644)
	if err != nil {
		fmt.Printf("Error writing report: %v\\n", err)
		os.Exit(1)
	}

	fmt.Println("Report and code generated successfully.")
}
"""
    with open(path, 'w') as f:
        f.write(new_content)

def update_kernel_rs():
    path = os.path.join(ROOT, "src-tauri", "src", "kernel.rs")
    with open(path, 'r') as f:
        content = f.read()

    # Add Target enum
    target_enum = """
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Target {
    Local = 0,
    Network = 1,
    Swarm = 2,
    Ledger = 3,
    Memory = 4,
    Dispatch = 5,
    Ui = 6,
    System = 7,
    Bft = 8,
    Core = 9,
}

impl TryFrom<u8> for Target {
    type Error = &'static str;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Target::Local),
            1 => Ok(Target::Network),
            2 => Ok(Target::Swarm),
            3 => Ok(Target::Ledger),
            4 => Ok(Target::Memory),
            5 => Ok(Target::Dispatch),
            6 => Ok(Target::Ui),
            7 => Ok(Target::System),
            8 => Ok(Target::Bft),
            9 => Ok(Target::Core),
            _ => Err("Invalid Target index"),
        }
    }
}

impl Target {
    pub fn as_str(&self) -> &'static str {
        match self {
            Target::Local => "LOCAL",
            Target::Network => "NETWORK",
            Target::Swarm => "SWARM",
            Target::Ledger => "LEDGER",
            Target::Memory => "MEMORY",
            Target::Dispatch => "DISPATCH",
            Target::Ui => "UI",
            Target::System => "SYSTEM",
            Target::Bft => "BFT",
            Target::Core => "CORE",
        }
    }
}
"""
    # Insert before PrimitiveIdentity
    content = content.replace("#[derive(Debug, Clone)]\npub struct PrimitiveIdentity {", target_enum + "\n#[derive(Debug, Clone)]\npub struct PrimitiveIdentity {")
    content = content.replace("pub modifier: Modifier,", "pub modifier: Modifier,\n    pub target: Target,")
    
    # Update new()
    content = content.replace("pub fn new(d: u8, p: u8, m: u8) -> Result<Self, &'static str> {", "pub fn new(d: u8, p: u8, m: u8, t: u8) -> Result<Self, &'static str> {")
    content = content.replace("let modifier = Modifier::try_from(m)?;", "let modifier = Modifier::try_from(m)?;\n        let target = Target::try_from(t)?;")
    content = content.replace("let code = (d as u16 * 100) + (p as u16 * 10) + m as u16;", "let code = (d as u16 * 1000) + (p as u16 * 100) + (m as u16 * 10) + t as u16;")
    content = content.replace("modifier,\n            code,", "modifier,\n            target,\n            code,")
    
    # Update to_string()
    content = content.replace("self.domain.as_str(), self.primitive.as_str(), self.modifier.as_str()", "self.domain.as_str(), self.primitive.as_str(), self.modifier.as_str(), self.target.as_str()")
    content = content.replace('"{}-{}-{}"', '"{}-{}-{}-{}"')
    
    # Update KERNEL_TABLE size
    content = content.replace("OnceLock<[Action; 1000]>", "OnceLock<[Action; 10000]>")
    content = content.replace("[default_dispatch_handler as Action; 1000]", "[default_dispatch_handler as Action; 10000]")
    content = content.replace("for i in 0..1000 {", "for i in 0..10000 {")
    content = content.replace("if index < 1000 {", "if index < 10000 {")
    content = content.replace("{:03}", "{:04}")
    
    # Update dispatch command
    content = content.replace("pub fn dispatch(d: u8, p: u8, m: u8)", "pub fn dispatch(d: u8, p: u8, m: u8, t: u8)")
    content = content.replace("PrimitiveIdentity::new(d, p, m)", "PrimitiveIdentity::new(d, p, m, t)")

    with open(path, 'w') as f:
        f.write(content)

def update_app_tsx():
    path = os.path.join(ROOT, "src", "App.tsx")
    with open(path, 'r') as f:
        content = f.read()

    content = content.replace("const dispatch = (d: number, p: number, m: number) => {", "const dispatch = (d: number, p: number, m: number, t: number) => {")
    content = content.replace("invoke('dispatch', { d, p, m });", "invoke('dispatch', { d, p, m, t });")
    content = content.replace("dispatch(0, 0, 0)", "dispatch(0, 0, 0, 0)")
    
    with open(path, 'w') as f:
        f.write(content)

if __name__ == "__main__":
    update_taxonomy()
    update_generate_primitives()
    update_audit_taxonomy()
    update_kernel_rs()
    update_app_tsx()
    print("REFACTOR. LEGION 10K. APPLIED.")
