/*
CORTEX - Sovereign Memory API

Testing FactsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package cortex

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/cortex"
)

func Test_cortex_FactsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FactsAPIService BatchStoreV1FactsBatchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FactsAPI.BatchStoreV1FactsBatchPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService CastVoteV1FactsFactIdVotePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.CastVoteV1FactsFactIdVotePost(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService CastVoteV2V1FactsFactIdVoteV2Post", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.CastVoteV2V1FactsFactIdVoteV2Post(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService DeprecateFactV1FactsFactIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.DeprecateFactV1FactsFactIdDelete(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService GetCausalChainV1FactsFactIdChainGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.GetCausalChainV1FactsFactIdChainGet(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService GetFactByIdV1FactsFactIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.GetFactByIdV1FactsFactIdGet(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService GetFactHistoryV1FactsFactIdHistoryGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.GetFactHistoryV1FactsFactIdHistoryGet(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService ListAllFactsV1FactsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FactsAPI.ListAllFactsV1FactsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService ListVotesV1FactsFactIdVotesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.ListVotesV1FactsFactIdVotesGet(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService PropagateTaintV1FactsFactIdTaintPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var factId int32

		resp, httpRes, err := apiClient.FactsAPI.PropagateTaintV1FactsFactIdTaintPost(context.Background(), factId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService RecallFactsV1ProjectsProjectFactsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.FactsAPI.RecallFactsV1ProjectsProjectFactsGet(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService SearchFactsV1FactsSearchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FactsAPI.SearchFactsV1FactsSearchPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService StoreFactV1FactsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FactsAPI.StoreFactV1FactsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FactsAPIService VerifyLedgerV1FactsVerifyGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FactsAPI.VerifyLedgerV1FactsVerifyGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
