/*
CORTEX - Sovereign Memory API

Testing TipsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package cortex

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/cortex"
)

func Test_cortex_TipsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TipsAPIService GetTipsByCategoryTipsCategoryCategoryGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var category string

		resp, httpRes, err := apiClient.TipsAPI.GetTipsByCategoryTipsCategoryCategoryGet(context.Background(), category).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TipsAPIService GetTipsByProjectTipsProjectProjectGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.TipsAPI.GetTipsByProjectTipsProjectProjectGet(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TipsAPIService GetTipsTipsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TipsAPI.GetTipsTipsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TipsAPIService ListCategoriesTipsCategoriesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TipsAPI.ListCategoriesTipsCategoriesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
