/*
CORTEX - Sovereign Memory API

Testing ExergyProxyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package cortex

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/cortex"
)

func Test_cortex_ExergyProxyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ExergyProxyAPIService ProxyChatCompletionsLlmProxyV1ChatCompletionsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ExergyProxyAPI.ProxyChatCompletionsLlmProxyV1ChatCompletionsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
