from typing import Any, Optional

class CortexRsSubstrate:
    def __init__(self, bin_path: str, dimension: int) -> None: ...
    def read_tensor(self) -> list[float]: ...
    def apply_decay(self, rate: float) -> None: ...
    def record(self, key: str, value: str) -> None: ...
    def get_address(self) -> int: ...

class ZeroCopyRingBuffer:
    def __init__(self, bin_path: str, capacity: int | None = None) -> None: ...
    def enqueue(self, agent_id: bytes, payload: bytes) -> bool: ...
    def fetch_pending(self) -> list[tuple[int, float, bytes, bytes]]: ...
    def get_address(self) -> int: ...
    def reset(self) -> None: ...
    def process_all_native(self, num_threads: int | None = None) -> tuple[int, float]: ...

class UltramapSubstrate:
    def __init__(self, bin_path: str, capacity: int | None = None) -> None: ...
    def update_agent_position(
        self, agent_idx: int, x: float, y: float, z: float, target: str, entropy: float
    ) -> bool: ...
    def calculate_exergy_distance(self, agent_idx: int, target_hash: str) -> float: ...
    def get_agent_state(self, agent_idx: int) -> dict[str, Any]: ...
    def volume_transmit_hormones(
        self,
        origin_x: float,
        origin_y: float,
        origin_z: float,
        radius: float,
        dopamine: float,
        cortisol: float,
        serotonin: float,
        adrenaline: float,
    ) -> int: ...
    def get_address(self) -> int: ...

class McpNativeClient:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class McpSovereignHost:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class AntiLimerenceTopology:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class AutoCurativeEngine:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class FitnessOracleRs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class GenomeMutatorRs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class IsaDispatcher:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class OuroborosExecutionGraph:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyWasmSwarm:
    def __init__(self) -> None: ...
    def spawn_agent(self, agent_id: str, wasm_bytes: bytes) -> None: ...
    def kill_agent(self, agent_id: str) -> None: ...
    def cycle_friction(self, agent_id: str, friction_signal: float) -> float: ...
    def active_count(self) -> int: ...
