"""MOSKV-Aether — Red Team Agent.

Generates hostile characterization tests (Golden Master) over a codebase
BEFORE execution/refactoring occurs, cementing the current behavior into
tests to ensure zero functional drift (Immunitas-Omega D4 Siege).
"""

from __future__ import annotations

import logging
import re
import uuid
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cortex.extensions.thinking.orchestra import ThoughtOrchestra

from cortex.extensions.aether.tools import AgentToolkit

__all__ = ["RedTeamAgent"]

logger = logging.getLogger("cortex.extensions.aether.redteam")

_SYSTEM_PROMPT = """You are Immunitas-Omega Red Team. Your goal is to forge Characterization Tests (Golden Master/Siege tests).
You are given the CURRENT SOURCE CODE of a Python target before a refactor occurs.
You must generate a strict `pytest` test suite that exhaustively tests the target's current behavior, covering all known branches, edge cases, and side-effects.

RULES:
- Emit ONLY pure Python code. No markdown formatting blocks around it.
- Your code must be a valid pytest file.
- Use `unittest.mock` to mock external dependencies or side-effects if needed, but focus on asserting outputs for known inputs.
- Your objective is to ensure that if the agent replacing this code breaks the logic or changes the return value, YOUR TEST WILL FAIL (Zero-drift policy).
"""


class RedTeamAgent:
    """Forges adversarial tests (Siege) prior to code mutation."""

    def __init__(self, orchestra: ThoughtOrchestra) -> None:
        self._orchestra = orchestra

    async def siege(self, task_description: str, toolkit: AgentToolkit) -> list[str]:
        """
        Analyze the task intent, extract target files, generate and write
        characterization tests. Returns a list of generated test paths.
        """
        logger.info("🛡️  Immunitas-Omega Red Team Deploying (D4 Pre-Siege)...")

        # 1. Extract target files using a quick heuristic
        # (Look for filenames ending in .py in the description)
        targets = set(re.findall(r"[\w/.\-]+\.py", task_description))

        generated_tests = []
        for target in targets:
            # Enforce AgentToolkit sandbox (_safe_path) via read_file
            code_content = toolkit.read_file(target)
            if code_content.startswith("[ERROR]"):
                logger.warning("Skipping target %s: %s", target, code_content)
                continue

            logger.info("🛡️ Forging Golden Master for: %s", target)

            prompt = (
                f"TARGET FILE: {target}\n"
                f"TASK DESCRIPTION (Context): {task_description}\n\n"
                f"CURRENT SOURCE CODE:\n```python\n{code_content}\n```\n\n"
                f"Write the Pytest file now. Ensure you import the target correctly (assume the test is run from {toolkit.repo_path})."
            )

            from cortex.extensions.thinking.presets import ThinkingMode

            fused = await self._orchestra.think(
                prompt,
                mode=ThinkingMode.OMEGA,
                system=_SYSTEM_PROMPT,
            )
            raw_test = fused.content

            raw_test = raw_test.strip()
            if raw_test.startswith("```"):
                lines = raw_test.splitlines()
                # Remove triple backticks
                if lines[0].startswith("```python"):
                    lines = lines[1:]
                elif lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                raw_test = "\n".join(lines).strip()

            # Define output path
            tests_dir = toolkit.repo_path / "tests" / "autogenerated"
            tests_dir.mkdir(parents=True, exist_ok=True)

            test_id = uuid.uuid4().hex[:6]
            test_filename = f"test_siege_{Path(target).stem}_{test_id}.py"
            test_file_path = tests_dir / test_filename

            test_file_path.write_text(raw_test, encoding="utf-8")
            generated_tests.append(str(test_file_path.relative_to(toolkit.repo_path)))

            # Create __init__.py if not exists to make it a module
            init_file = tests_dir / "__init__.py"
            if not init_file.exists():
                init_file.write_text("")

            # If `tests` dir doesn't have an __init__.py, create it too just in case
            parent_init = toolkit.repo_path / "tests" / "__init__.py"
            if not parent_init.exists() and (toolkit.repo_path / "tests").exists():
                parent_init.write_text("")

        if generated_tests:
            logger.info("🛡️ Characterization suite forged: %s", generated_tests)
        else:
            logger.info("🛡️ Red Team found no explicit file targets to siege; passing through.")

        return generated_tests
